# Generated by Django 5.1.2 on 2025-10-22 22:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.CharField(
                        help_text="Caminho completo do arquivo importado",
                        max_length=255,
                    ),
                ),
                (
                    "sha256",
                    models.CharField(
                        db_index=True, help_text="Hash SHA256 do arquivo", max_length=64
                    ),
                ),
                (
                    "rows_processed",
                    models.IntegerField(
                        default=0, help_text="Número de linhas processadas"
                    ),
                ),
                (
                    "rows_success",
                    models.IntegerField(
                        default=0, help_text="Linhas importadas com sucesso"
                    ),
                ),
                (
                    "rows_failed",
                    models.IntegerField(default=0, help_text="Linhas que falharam"),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ok",
                    models.BooleanField(
                        default=False, help_text="Import concluído com sucesso"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, default="", help_text="Mensagem de erro (se houver)"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Metadados adicionais"
                    ),
                ),
            ],
            options={
                "verbose_name": "Import Log",
                "verbose_name_plural": "Import Logs",
                "db_table": "dat_import_log",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["file", "sha256"], name="dat_import__file_dbf301_idx"
                    ),
                    models.Index(
                        fields=["ok", "started_at"], name="dat_import__ok_760c91_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StgMunicipio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("uf", models.CharField(max_length=2)),
                ("ativo", models.BooleanField(default=True)),
                ("src", models.CharField(max_length=100)),
                ("rownum", models.IntegerField()),
            ],
            options={
                "verbose_name": "Staging Municipio",
                "verbose_name_plural": "Staging Municipios",
                "db_table": "stg_municipio",
                "indexes": [
                    models.Index(
                        fields=["nome", "uf"], name="stg_municip_nome_5eb9b4_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StgProjeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("descricao", models.TextField(blank=True, default="")),
                ("ativo", models.BooleanField(default=True)),
                ("src", models.CharField(max_length=100)),
                ("rownum", models.IntegerField()),
            ],
            options={
                "verbose_name": "Staging Projeto",
                "verbose_name_plural": "Staging Projetos",
                "db_table": "stg_projeto",
                "indexes": [
                    models.Index(fields=["nome"], name="stg_projeto_nome_c24133_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="StgTipoEvento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True, default="")),
                ("cor", models.CharField(blank=True, default="", max_length=7)),
                ("src", models.CharField(max_length=100)),
                ("rownum", models.IntegerField()),
            ],
            options={
                "verbose_name": "Staging Tipo Evento",
                "verbose_name_plural": "Staging Tipos Evento",
                "db_table": "stg_tipo_evento",
                "indexes": [
                    models.Index(fields=["nome"], name="stg_tipo_ev_nome_1130fa_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="StgUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("cpf", models.CharField(blank=True, default="", max_length=11)),
                ("telefone", models.CharField(blank=True, default="", max_length=20)),
                ("perfil", models.CharField(max_length=50)),
                ("ativo", models.BooleanField(default=True)),
                ("src", models.CharField(max_length=100)),
                ("rownum", models.IntegerField()),
            ],
            options={
                "verbose_name": "Staging Usuario",
                "verbose_name_plural": "Staging Usuarios",
                "db_table": "stg_usuario",
                "indexes": [
                    models.Index(fields=["email"], name="stg_usuario_email_ade1e6_idx"),
                    models.Index(fields=["src"], name="stg_usuario_src_a99cde_idx"),
                ],
            },
        ),
    ]
