# Generated by Django 5.1.15 on 2026-03-04 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dat_ingest", "0002_add_stg_municipio_referencia"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="stgmunicipioreferencia",
            new_name="stg_municip_fonte_b66622_idx",
            old_name="stg_municipio_ref_fonte_codigo_idx",
        ),
        migrations.RenameIndex(
            model_name="stgmunicipioreferencia",
            new_name="stg_municip_nome_f02d9f_idx",
            old_name="stg_municipio_ref_nome_uf_idx",
        ),
    ]
