# Generated by Django 5.2.4 on 2025-09-30 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20250929_2125'),
    ]

    operations = [
    ]
