# Generated by Django 4.2.25 on 2025-10-02 03:00
# Hotfix Dia 3: Adiciona campo origem em MarcadorPlanilha

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_add_origem_to_aprovacao_historico_hotfix_dia3"),
    ]

    operations = [
        # Adicionar campo origem ao MarcadorPlanilha
        migrations.AddField(
            model_name='marcadorplanilha',
            name='origem',
            field=models.CharField(
                default='planilha',
                help_text='Ex: planilha, sistema, api',
                max_length=32,
                verbose_name='Origem'
            ),
        ),
    ]
