# Generated by Django 4.2.25 on 2025-10-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_add_can_controlar_preagenda_permission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formador",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="E-mail",
            ),
        ),
    ]
