# Generated by Django 4.2.25 on 2025-10-07 20:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_add_vinculo_constraints"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="deslocamento",
            name="data_not_too_far_future",
        ),
        migrations.RemoveConstraint(
            model_name="vinculousuariosetor",
            name="ck_vinculo_papel_valid",
        ),
        migrations.RemoveIndex(
            model_name="vinculousuariosetor",
            name="idx_vinculo_user_papel",
        ),
        migrations.AlterField(
            model_name="vinculousuariosetor",
            name="papel",
            field=models.CharField(
                choices=[
                    ("GERENTE", "Gerente"),
                    ("COORDENADOR", "Coordenador"),
                    ("FORMADOR", "Formador"),
                    ("CONTROLE", "Controle"),
                    ("SUPER", "Superintendência"),
                ],
                max_length=20,
                verbose_name="Papel",
            ),
        ),
        migrations.AddConstraint(
            model_name="deslocamento",
            constraint=models.CheckConstraint(
                check=models.Q(("data__lte", datetime.date(2026, 10, 7))),
                name="data_not_too_far_future",
                violation_error_message="Data não pode ser mais de 1 ano no futuro.",
            ),
        ),
    ]
