# Generated by Django 4.2.25 on 2025-10-07 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_remove_marcadorplanilha_disponibilidade_and_more"),
    ]

    operations = [
        # Esses campos não existem na tabela real; evitar erro em migrate
        migrations.AddField(
            model_name="deslocamento",
            name="pessoa_1_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deslocamentos_p1_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Pessoa 1 (Usuário)",
            ),
        ),
        migrations.AddField(
            model_name="deslocamento",
            name="pessoa_2_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deslocamentos_p2_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Pessoa 2 (Usuário)",
            ),
        ),
        migrations.AddField(
            model_name="deslocamento",
            name="pessoa_3_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deslocamentos_p3_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Pessoa 3 (Usuário)",
            ),
        ),
        migrations.AddField(
            model_name="deslocamento",
            name="pessoa_4_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deslocamentos_p4_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Pessoa 4 (Usuário)",
            ),
        ),
        migrations.AddField(
            model_name="deslocamento",
            name="pessoa_5_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deslocamentos_p5_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Pessoa 5 (Usuário)",
            ),
        ),
        migrations.AddField(
            model_name="deslocamento",
            name="pessoa_6_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deslocamentos_p6_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Pessoa 6 (Usuário)",
            ),
        ),
    ]
