# Generated by Django 4.2.25 on 2025-10-07 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_remove_marcadorplanilha_disponibilidade_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsuarioAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alias", models.CharField(db_index=True, max_length=150, unique=True)),
                ("origem", models.CharField(default="manual", max_length=50)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Alias de Usuário",
                "verbose_name_plural": "Aliases de Usuário",
                "indexes": [models.Index(fields=["alias"], name="idx_alias_alias")],
            },
        ),
    ]
