# Generated by Django 4.2.25 on 2025-10-08 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0055_remove_marcadorplanilha_disponibilidade_and_more"),
    ]

    operations = [
        # Campos nunca existiram na tabela - migração no-op
    ]
