# Generated by Django 4.2.25 on 2025-10-09 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0057_add_calendar_sync_log"),
        ("core", "0056_remove_marcadorplanilha_disponibilidade_and_more"),
    ]

    operations = []
