"""
Django settings for AS v2 project.

Generated by Django 5.2.4.
"""

import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ================================================================
# CLAUSULA PETREA: REQUIRE_DOCKER=1
# ================================================================
# v2 DEVE rodar apenas em Docker. Validação obrigatória.
REQUIRE_DOCKER = os.getenv("REQUIRE_DOCKER", "0") == "1"

if REQUIRE_DOCKER and not os.path.exists("/.dockerenv"):
    print("❌ ERRO: v2 deve rodar apenas em Docker (REQUIRE_DOCKER=1)", file=sys.stderr)
    print("   Execute: cd v2/infra && docker-compose up", file=sys.stderr)
    sys.exit(1)

# ================================================================
# ENVIRONMENT
# ================================================================
ENVIRONMENT = os.getenv("ENVIRONMENT", "development")
DEBUG = os.getenv("DEBUG", "0") == "1"

print("AS v2 inicializado; legado arquivado e bloqueado")
# ================================================================
# SECRET KEY
# ================================================================
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-dev-key-CHANGE-IN-PRODUCTION-abcd1234efgh5678ijkl9012mnop3456qrst",
)

# ================================================================
# ALLOWED HOSTS
# ================================================================
ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")

# ================================================================
# INSTALLED APPS
# ================================================================
INSTALLED_APPS = [
    # Django core
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party
    "rest_framework",
    "corsheaders",
    "django_celery_beat",
    "django_celery_results",
    # AS v2 apps
    "apps.core",
    "apps.dat_ingest",
]

# ================================================================
# AUTH USER MODEL
# ================================================================
# Cláusula Pétrea: Usuario customizado (SSOT)
AUTH_USER_MODEL = "core.Usuario"

# ================================================================
# MIDDLEWARE
# ================================================================
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# ================================================================
# ROOT URL CONF
# ================================================================
ROOT_URLCONF = "config.urls"

# ================================================================
# TEMPLATES
# ================================================================
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# ================================================================
# WSGI
# ================================================================
WSGI_APPLICATION = "config.wsgi.application"

# ================================================================
# DATABASE
# ================================================================
# Cláusula Pétrea: PostgreSQL obrigatório (SSOT)
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME", "aprender_db"),
        "USER": os.getenv("DB_USER", "aprender_user"),
        "PASSWORD": os.getenv("DB_PASSWORD", "aprender_password"),
        "HOST": os.getenv("DB_HOST", "db"),
        "PORT": os.getenv("DB_PORT", "5432"),
        "CONN_MAX_AGE": 600,
        "OPTIONS": {
            "connect_timeout": 10,
        },
    }
}

# ================================================================
# CACHE (Redis)
# ================================================================
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://{os.getenv('REDIS_HOST', 'redis')}:{os.getenv('REDIS_PORT', '6379')}/0",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "SOCKET_CONNECT_TIMEOUT": 5,
            "SOCKET_TIMEOUT": 5,
        },
    }
}

# ================================================================
# PASSWORD VALIDATION
# ================================================================
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# ================================================================
# INTERNATIONALIZATION
# ================================================================
# Cláusula Pétrea: timezone America/Fortaleza
LANGUAGE_CODE = "pt-br"
TIME_ZONE = "America/Fortaleza"
USE_I18N = True
USE_TZ = True

# ================================================================
# STATIC FILES
# ================================================================
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"] if (BASE_DIR / "static").exists() else []
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# ================================================================
# MEDIA FILES
# ================================================================
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# ================================================================
# DEFAULT PRIMARY KEY
# ================================================================
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ================================================================
# CORS
# ================================================================
CORS_ALLOWED_ORIGINS = os.getenv(
    "CORS_ALLOWED_ORIGINS",
    "http://localhost:3000,http://localhost:5173,http://localhost:5174,http://localhost:5175,http://localhost:5176,http://localhost:8000",
).split(",")
CORS_ALLOW_CREDENTIALS = True

# ================================================================
# CSRF
# ================================================================
CSRF_TRUSTED_ORIGINS = os.getenv(
    "CSRF_TRUSTED_ORIGINS",
    "http://localhost:3000,http://localhost:5173,http://localhost:5174,http://localhost:5175,http://localhost:5176,http://localhost:8000",
).split(",")
CSRF_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript to read CSRF token

# ================================================================
# REST FRAMEWORK
# ================================================================
REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 100,
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
        "rest_framework.throttling.ScopedRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/hour",
        "user": "1000/hour",
        "availability_check": "60/min",  # 60 requests por minuto para availability check
    },
}

# ================================================================
# CELERY
# ================================================================
CELERY_BROKER_URL = (
    f"redis://{os.getenv('REDIS_HOST', 'redis')}:{os.getenv('REDIS_PORT', '6379')}/1"
)
CELERY_RESULT_BACKEND = "django-db"
CELERY_CACHE_BACKEND = "default"
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes

# Celery Beat Schedule (tarefas periódicas)
CELERY_BEAT_SCHEDULE = {
    "gcal-sync-every-5-minutes": {
        "task": "apps.core.tasks.preview_then_apply_gcal",
        "schedule": 300.0,  # 5 minutos (em segundos)
        "options": {
            "expires": 60.0,  # Tarefa expira após 60s se não iniciar
        },
    },
}

# ================================================================
# LOGGING
# ================================================================
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{levelname}] {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
        "apps": {
            "handlers": ["console"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
    },
}

# ================================================================
# GOOGLE CALENDAR / SHEETS
# ================================================================
GOOGLE_SERVICE_ACCOUNT_JSON = os.getenv("GOOGLE_SERVICE_ACCOUNT_JSON", "")
GCAL_CALENDAR_ID = os.getenv("GCAL_CALENDAR_ID", "")

# Calendar client type: 'fake' (in-memory, safe) or 'google' (real API)
# Default: 'fake' para evitar publicações acidentais até implementar GoogleCalendarClient
GCAL_CLIENT = os.getenv("GCAL_CLIENT", "fake")

# Google Calendar color mapping (optional)
# Maps TipoEvento.nome → Google Calendar colorId (1-11)
# https://developers.google.com/calendar/api/v3/reference/colors
GCAL_COLOR_MAP = {
    # Example mappings (customize as needed):
    # "Formação": 9,           # Blue
    # "Acompanhamento": 10,    # Green
    # "Reunião": 11,           # Red
}

# ================================================================
# AVAILABILITY & ETL SETTINGS (Cláusulas Pétreas RD-01..RD-08)
# ================================================================
# RD-06: Timezone do projeto (America/Fortaleza)
TZ_PROJECT = TIME_ZONE  # Herda do TIME_ZONE acima

# RD-05: Limite diário de horas por formador (configurável)
AVAILABILITY_DAILY_LIMIT_HOURS = int(os.getenv("AVAILABILITY_DAILY_LIMIT_HOURS", "8"))

# RD-04: Buffer de deslocamento entre municípios distintos (minutos)
TRAVEL_BUFFER_MINUTES = int(os.getenv("TRAVEL_BUFFER_MINUTES", "120"))

# ETL: Diretório padrão para importação de arquivos
DATA_IMPORT_DIR = os.getenv("DATA_IMPORT_DIR", "/app/data/csv-import")

# ================================================================
# SECURITY (Production)
# ================================================================
if not DEBUG:
    SECURE_SSL_REDIRECT = ENVIRONMENT != "testing"  # Disable in tests to avoid 301 redirects
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"
