"""
Django settings for AS v2 project.

Generated by Django 5.2.4.
"""

# pyright: reportConstantRedefinition=false

from __future__ import annotations

import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ================================================================
# CLAUSULA PETREA: REQUIRE_DOCKER=1
# ================================================================
# v2 DEVE rodar apenas em Docker. Validação obrigatória.
REQUIRE_DOCKER = os.getenv("REQUIRE_DOCKER", "0") == "1"

if REQUIRE_DOCKER and not os.path.exists("/.dockerenv"):
    print("❌ ERRO: v2 deve rodar apenas em Docker (REQUIRE_DOCKER=1)", file=sys.stderr)
    print("   Execute: cd v2/infra && docker-compose up", file=sys.stderr)
    sys.exit(1)

# ================================================================
# ENVIRONMENT
# ================================================================
ENVIRONMENT = os.getenv("ENVIRONMENT", "development")
DEBUG = os.getenv("DEBUG", "0") == "1"
# Detect if running under pytest (for disabling debug toolbar during tests)
TESTING = "pytest" in sys.modules or "PYTEST_CURRENT_TEST" in os.environ

print("Aprender Sistema Inicializado")
# ================================================================
# SECRET KEY
# ================================================================
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-dev-key-CHANGE-IN-PRODUCTION-abcd1234efgh5678ijkl9012mnop3456qrst",
)

# ================================================================
# ALLOWED HOSTS
# ================================================================
# MP1: Include 'web' for Prometheus internal scraping
ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1,0.0.0.0,testserver,web").split(",")

# ================================================================
# PRODUCTION GUARD RAILS (P1.4)
# ================================================================
# Bloquear configurações inseguras em produção
if ENVIRONMENT == "production":
    # CRITICAL: DEBUG=True em produção
    if DEBUG:
        print("❌ ERRO CRÍTICO: DEBUG=True em produção é inseguro", file=sys.stderr)
        print("   Configure DEBUG=0 em produção", file=sys.stderr)
        sys.exit(1)

    # CRITICAL: ALLOWED_HOSTS vazio ou wildcard em produção
    if not ALLOWED_HOSTS or ALLOWED_HOSTS == ["*"]:
        print("❌ ERRO CRÍTICO: ALLOWED_HOSTS=['*'] em produção é inseguro", file=sys.stderr)
        print("   Configure ALLOWED_HOSTS com domínios específicos", file=sys.stderr)
        sys.exit(1)

    # WARNING: SECRET_KEY muito curta
    if len(SECRET_KEY) < 50:
        print("⚠️  WARNING: SECRET_KEY muito curta (recomendado: 50+ caracteres)", file=sys.stderr)
        print("   Gere uma chave mais segura para produção", file=sys.stderr)

    # WARNING: GCAL_CLIENT=fake em produção
    if os.getenv("GCAL_CLIENT", "fake") == "fake":
        print("⚠️  WARNING: GCAL_CLIENT=fake em produção", file=sys.stderr)
        print("   Eventos não serão sincronizados com Google Calendar", file=sys.stderr)
        print("   Configure GCAL_CLIENT=google para integração real", file=sys.stderr)

# ================================================================
# INSTALLED APPS
# ================================================================
# ETL Module (dat_ingest) - Opcional em produção
# Default: True (inclui ETL para manter compatibilidade)
# Para excluir do deploy: INCLUDE_ETL=false
INCLUDE_ETL = os.getenv("INCLUDE_ETL", "true").lower() == "true"

# Dev Tools Module (dev_tools) - Seeds, backfills, fixtures
# Default: True (inclui para manter compatibilidade)
# Para excluir do deploy: INCLUDE_DEV_TOOLS=false
INCLUDE_DEV_TOOLS = os.getenv("INCLUDE_DEV_TOOLS", "true").lower() == "true"

INSTALLED_APPS = [
    # Django core
    "django.contrib.admin.apps.SimpleAdminConfig",  # Disables autodiscover (custom admin site)
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party
    "rest_framework",
    "drf_spectacular",  # API documentation (Swagger/ReDoc)
    "corsheaders",
    "django_prometheus",  # MP1: Metrics collection
    "django_celery_beat",
    "django_celery_results",
    # AS v2 apps
    "apps.core",
]

# Incluir ETL apenas se INCLUDE_ETL=true
if INCLUDE_ETL:
    INSTALLED_APPS.append("apps.dat_ingest")

# Incluir Dev Tools apenas se INCLUDE_DEV_TOOLS=true
if INCLUDE_DEV_TOOLS:
    INSTALLED_APPS.append("apps.dev_tools")

# ================================================================
# AUTH USER MODEL
# ================================================================
# Cláusula Pétrea: Usuario customizado (SSOT)
AUTH_USER_MODEL = "core.Usuario"

# ================================================================
# AUTHENTICATION BACKENDS
# ================================================================
# Custom backend: permite login por CPF ou username
AUTHENTICATION_BACKENDS = [
    "apps.core.auth_backends.CPFOrUsernameBackend",  # Custom: CPF or username
    "django.contrib.auth.backends.ModelBackend",  # Fallback: default Django
]

# ================================================================
# MIDDLEWARE
# ================================================================
MIDDLEWARE = [
    "django_prometheus.middleware.PrometheusBeforeMiddleware",  # MP1: Metrics start
    "apps.core.middleware.RequestIDMiddleware",  # MP2: Correlation ID for structured logging
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "apps.core.middleware_security.SecurityHeadersMiddleware",  # Security Audit 2025-01: CSP + Permissions-Policy
    "django_prometheus.middleware.PrometheusAfterMiddleware",  # MP1: Metrics end
]

# ================================================================
# ROOT URL CONF
# ================================================================
ROOT_URLCONF = "config.urls"

# ================================================================
# TEMPLATES
# ================================================================
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# ================================================================
# WSGI
# ================================================================
WSGI_APPLICATION = "config.wsgi.application"

# ================================================================
# DATABASE
# ================================================================
# Cláusula Pétrea: PostgreSQL obrigatório (SSOT)
DATABASES = {
    "default": {
        # MP1: Use Prometheus-wrapped PostgreSQL backend for query metrics
        "ENGINE": "django_prometheus.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME", "aprender_db"),
        "USER": os.getenv("DB_USER", "aprender_user"),
        "PASSWORD": os.getenv("DB_PASSWORD", "aprender_password"),
        "HOST": os.getenv("DB_HOST", "db"),
        "PORT": os.getenv("DB_PORT", "5432"),
        "CONN_MAX_AGE": 60,  # Reutiliza conexões por 60s
        "CONN_HEALTH_CHECKS": True,  # Valida conexões antes de reutilizar
        "OPTIONS": {
            "connect_timeout": 10,
            # 30s query timeout em produção (evita queries lentas)
            "options": "-c statement_timeout=30000" if ENVIRONMENT == "production" else "",
        },
    }
}

# ================================================================
# CACHE (Redis)
# ================================================================
CACHES = {
    "default": {
        # MP1: Use Prometheus-wrapped Redis cache for cache hit/miss metrics
        "BACKEND": "django_prometheus.cache.backends.redis.RedisCache",
        "LOCATION": f"redis://:{os.getenv('REDIS_PASSWORD', '')}@{os.getenv('REDIS_HOST', 'redis')}:{os.getenv('REDIS_PORT', '6379')}/0",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "SOCKET_CONNECT_TIMEOUT": 5,
            "SOCKET_TIMEOUT": 5,
            "CONNECTION_POOL_KWARGS": {"max_connections": 50},  # Pool de conexões
        },
        "KEY_PREFIX": "as2",  # Namespace para evitar colisões
        "TIMEOUT": 300,  # 5 minutos default TTL
    }
}

# ================================================================
# SESSION BACKEND (CP2 - Redis Sessions)
# ================================================================
# Migrado de database para Redis cache (100x faster)
# Benefits:
# - 100x melhor performance em operações de sessão
# - Redução de ~4.3M queries/dia (sessões ociosas)
# - Suporte a escala horizontal (múltiplos containers)
# - Redução de contenção no PostgreSQL
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"  # Redis já configurado acima

# Session cookie settings (CP2 + PLANO_OTIMIZACAO_COMPLETO Fase 1)
# Timeout de 2 horas (balanceamento entre segurança e usabilidade)
SESSION_COOKIE_AGE = int(os.getenv("SESSION_COOKIE_AGE", 60 * 60 * 2))  # 2 horas (default)
SESSION_SAVE_EVERY_REQUEST = os.getenv("SESSION_SAVE_EVERY_REQUEST", "True") == "True"  # Renova a cada request
SESSION_EXPIRE_AT_BROWSER_CLOSE = os.getenv("SESSION_EXPIRE_AT_BROWSER_CLOSE", "True") == "True"
SESSION_COOKIE_NAME = os.getenv("SESSION_COOKIE_NAME", "asv2sid")  # Custom name
SESSION_COOKIE_HTTPONLY = True  # Segurança: JavaScript não pode acessar
SESSION_COOKIE_SAMESITE = "Lax"  # Django Admin same-origin
SESSION_COOKIE_SECURE = False if ENVIRONMENT == "development" else True  # HTTPS only em produção

# ================================================================
# PASSWORD VALIDATION
# ================================================================
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# ================================================================
# INTERNATIONALIZATION
# ================================================================
# Cláusula Pétrea: timezone America/Fortaleza
LANGUAGE_CODE = "pt-br"
TIME_ZONE = "America/Fortaleza"
USE_I18N = True
USE_TZ = True

# ================================================================
# STATIC FILES
# ================================================================
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"] if (BASE_DIR / "static").exists() else []
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# ================================================================
# MEDIA FILES
# ================================================================
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# S3 storage for media files (horizontal scaling ready)
# When AWS_STORAGE_BUCKET_NAME is set, media files go to S3 instead of local disk.
# Currently no models use FileField/ImageField — all uploads are temp CSV/XLSX
# processed and deleted. This config prepares for future persistent uploads.
_s3_bucket = os.getenv("AWS_STORAGE_BUCKET_NAME", "")
if _s3_bucket:
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
            "OPTIONS": {
                "bucket_name": _s3_bucket,
                "region_name": os.getenv("AWS_S3_REGION_NAME", "us-east-1"),
                "default_acl": "private",
                "file_overwrite": False,
                "querystring_auth": True,
            },
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

# ================================================================
# DEFAULT PRIMARY KEY
# ================================================================
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ================================================================
# OAUTH PORT CONFIGURATION
# ================================================================
# Issue #442: Centralize port numbers for OAuth flow
FRONTEND_DEV_PORT = os.getenv("FRONTEND_DEV_PORT", "5173")
BACKEND_PORT = os.getenv("BACKEND_PORT", "8002")

# ================================================================
# TIMEOUTS & CACHE (Issue #443)
# ================================================================
# Centralized timeout constants for consistent configuration

# Cache TTL (matches frontend hook CACHE_TTL)
CACHE_DEFAULT_TIMEOUT = int(os.getenv("CACHE_DEFAULT_TIMEOUT", 300))  # 5 minutes

# Redis distributed lock
REDIS_LOCK_TIMEOUT = int(os.getenv("REDIS_LOCK_TIMEOUT", 300))  # 5 minutes

# Google API timeouts
GOOGLE_API_TIMEOUT = int(os.getenv("GOOGLE_API_TIMEOUT", 10))  # 10 seconds
GOOGLE_OAUTH_TIMEOUT = int(os.getenv("GOOGLE_OAUTH_TIMEOUT", 600))  # 10 minutes
GOOGLE_API_MAX_RETRIES = int(os.getenv("GOOGLE_API_MAX_RETRIES", 3))

# Circuit Breaker (GCal)
GCAL_CIRCUIT_BREAKER_FAIL_MAX = int(os.getenv("GCAL_CB_FAIL_MAX", 5))
GCAL_CIRCUIT_BREAKER_RESET_TIMEOUT = int(os.getenv("GCAL_CB_RESET_TIMEOUT", 60))

# Celery task retry
CELERY_DEFAULT_RETRY_DELAY = int(os.getenv("CELERY_RETRY_DELAY", 300))  # 5 minutes
CELERY_CIRCUIT_BREAKER_COUNTDOWN = int(os.getenv("CELERY_CB_COUNTDOWN", 60))  # 1 minute

# ================================================================
# EXTERNAL PLATFORMS (Issue #446)
# ================================================================
FORMAR_PLATFORM_BASE_URL = os.getenv("FORMAR_PLATFORM_URL", "https://www.aprenderformar.com.br/plataforma")

# ================================================================
# CORS
# ================================================================
CORS_ALLOWED_ORIGINS = os.getenv(
    "CORS_ALLOWED_ORIGINS",
    "http://localhost:3000,http://localhost:5173,http://localhost:5174,http://localhost:5175,http://localhost:5176,http://localhost:8000,http://localhost:8002",
).split(",")
CORS_ALLOW_CREDENTIALS = True

# ================================================================
# CSRF
# ================================================================
CSRF_TRUSTED_ORIGINS = os.getenv(
    "CSRF_TRUSTED_ORIGINS",
    "http://localhost:3000,http://localhost:5173,http://localhost:5174,http://localhost:5175,http://localhost:5176,http://localhost:8000,http://localhost:8002",
).split(",")
CSRF_COOKIE_SAMESITE = "Lax"
# Issue #135: XSS protection - JavaScript não pode ler o cookie diretamente
# Frontend usa endpoint /api/csrf/ para obter token quando necessário
CSRF_COOKIE_HTTPONLY = True

# ================================================================
# SESSION COOKIE (moved to SESSION BACKEND section - CP2)
# ================================================================
# Configurações de session movidas para a seção "SESSION BACKEND (CP2)" acima
# para centralizar todas as configs relacionadas a sessões Redis

# ================================================================
# REST FRAMEWORK
# ================================================================
REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 100,
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
        "rest_framework.throttling.ScopedRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/hour",
        "user": "1000/hour",
        # Scopes para endpoints específicos (#409)
        "availability_check": "60/min",  # 60 requests por minuto para availability check
        "metrics": "30/min",  # Geo queries + aggregations
        "reports": "30/min",  # Heavy aggregations
        "gcal_read": "60/min",  # Google Calendar reads
        "gcal_write": "10/min",  # Google Calendar writes (publish)
        "export": "10/min",  # CSV/JSON exports
    },
    # Custom exception handler for standardized error responses
    "EXCEPTION_HANDLER": "apps.core.exceptions.custom_exception_handler",
    # API Schema (drf-spectacular)
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    # API Versioning (#410)
    "DEFAULT_VERSIONING_CLASS": "rest_framework.versioning.URLPathVersioning",
    "DEFAULT_VERSION": "v1",
    "ALLOWED_VERSIONS": ["v1"],
    "VERSION_PARAM": "version",
}

# ================================================================
# DRF SPECTACULAR (API Documentation)
# ================================================================
SPECTACULAR_SETTINGS = {
    "TITLE": "Aprender Sistema API",
    "DESCRIPTION": "API para gestão de eventos de formação e solicitações do Aprender Sistema.",
    "VERSION": "2.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "SCHEMA_PATH_PREFIX": "/api/",
    # Contact info
    "CONTACT": {
        "name": "Equipe AS v2",
    },
    # Tags for endpoint grouping
    "TAGS": [
        {"name": "auth", "description": "Autenticação e sessões"},
        {"name": "solicitacoes", "description": "Gestão de solicitações de eventos"},
        {"name": "availability", "description": "Disponibilidade e bloqueios"},
        {"name": "gcal", "description": "Integração Google Calendar"},
        {"name": "dat", "description": "Módulo DAT (cadastros, ações, compras)"},
        {"name": "metrics", "description": "Métricas e relatórios"},
        {"name": "options", "description": "Opções para formulários"},
        {"name": "admin", "description": "Administração de entidades"},
    ],
    # Swagger UI settings (Issue #415)
    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "persistAuthorization": True,
        "displayOperationId": True,
        "filter": True,
        "tryItOutEnabled": True,
    },
}

# Relax throttling in development
if ENVIRONMENT == "development":
    REST_FRAMEWORK["DEFAULT_THROTTLE_RATES"] = {
        "anon": "10000/hour",
        "user": "100000/hour",
        # 10x mais permissivo em dev
        "availability_check": "600/min",
        "metrics": "300/min",
        "reports": "300/min",
        "gcal_read": "600/min",
        "gcal_write": "100/min",
        "export": "100/min",
    }

# ================================================================
# CELERY
# ================================================================
CELERY_BROKER_URL = f"redis://{os.getenv('REDIS_HOST', 'redis')}:{os.getenv('REDIS_PORT', '6379')}/1"
CELERY_RESULT_BACKEND = "django-db"
CELERY_CACHE_BACKEND = "default"
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes

# Auto-apply GCal (Celery task preview_then_apply_gcal) - Fase 3
# Default: False (desativado por padrão para consolidar governança via /pre-agenda)
# Quando True: Celery beat executa preview_then_apply_gcal periodicamente
# Quando False: Task retorna status="SKIPPED" sem executar sync
# Fase 3 - Governança GCal: única via de criação é /pre-agenda (individual + massa)
FEATURE_AUTO_APPLY_ENABLED = os.getenv("FEATURE_AUTO_APPLY_ENABLED", "0") == "1"

# Celery Beat Schedule (tarefas periódicas)
# Governança Fase 3: schedule só é registrado quando FEATURE_AUTO_APPLY_ENABLED=True
if FEATURE_AUTO_APPLY_ENABLED:
    CELERY_BEAT_SCHEDULE = {
        "gcal-sync-every-5-minutes": {
            "task": "apps.core.tasks.preview_then_apply_gcal",
            "schedule": 300.0,  # 5 minutos (em segundos)
            "options": {
                "expires": 60.0,  # Tarefa expira após 60s se não iniciar
            },
        },
    }
else:
    CELERY_BEAT_SCHEDULE = {}

# ================================================================
# LOGGING (MP2: Structured Logging)
# ================================================================
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        # JSON formatter para structured logging (MP2)
        "json": {
            "()": "pythonjsonlogger.jsonlogger.JsonFormatter",
            "format": "%(asctime)s %(levelname)s %(name)s %(message)s %(request_id)s %(environment)s %(service)s",
            "timestamp": True,
        },
        # Fallback para desenvolvimento local (human-readable)
        "verbose": {
            "format": "[{levelname}] {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
    },
    "filters": {
        # Filtro para adicionar request_id aos logs (MP2)
        "request_id": {
            "()": "apps.core.logging_filters.RequestIDFilter",
        },
        # Filtro para adicionar contexto (environment, service)
        "context": {
            "()": "apps.core.logging_filters.ContextFilter",
            "environment": ENVIRONMENT,
            "service": os.getenv("SERVICE_NAME", "web"),  # web/worker/beat
        },
    },
    "handlers": {
        # Handler JSON para stdout (production/staging)
        "console_json": {
            "class": "logging.StreamHandler",
            "formatter": "json",
            "filters": ["request_id", "context"],
        },
        # Handler human-readable para development
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        # Usar JSON em produção/staging, verbose em dev
        "handlers": ["console_json"] if ENVIRONMENT in ["production", "staging"] else ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console_json"] if ENVIRONMENT in ["production", "staging"] else ["console"],
            "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
        "apps": {
            "handlers": ["console_json"] if ENVIRONMENT in ["production", "staging"] else ["console"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
        "celery": {
            "handlers": ["console_json"] if ENVIRONMENT in ["production", "staging"] else ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# ================================================================
# GOOGLE CALENDAR / SHEETS
# ================================================================
GOOGLE_SERVICE_ACCOUNT_JSON = os.getenv("GOOGLE_SERVICE_ACCOUNT_JSON", "")
GCAL_CALENDAR_ID = os.getenv("GCAL_CALENDAR_ID", "")

# Calendar client type: 'fake' (in-memory, safe) or 'google' (real API)
# Default: 'fake' para evitar publicações acidentais até implementar GoogleCalendarClient
GCAL_CLIENT = os.getenv("GCAL_CLIENT", "fake")

# Google Calendar authentication mode: 'service_account' (default) or 'oauth'
# - service_account: Uses GOOGLE_SERVICE_ACCOUNT_JSON for server-to-server auth
# - oauth: Uses user OAuth credentials from GoogleOAuthCredential model
# Note: GCAL_CLIENT must be 'google' for either mode to work
GCAL_AUTH_MODE = os.getenv("GCAL_AUTH_MODE", "service_account")

# Google Calendar sendUpdates parameter (RF05/RF06 - PR19)
# Controls whether email notifications are sent to attendees:
# - 'none': No emails (default, recommended for testing)
# - 'all': Emails to all attendees
# - 'externalOnly': Emails only to external attendees
# https://developers.google.com/calendar/api/v3/reference/events/insert#parameters
GCAL_SEND_UPDATES = os.getenv("GCAL_SEND_UPDATES", "none")

# Validate GCAL_SEND_UPDATES
_VALID_SEND_UPDATES = {"none", "all", "externalOnly"}
if GCAL_SEND_UPDATES not in _VALID_SEND_UPDATES:
    print(
        f"❌ ERRO: GCAL_SEND_UPDATES='{GCAL_SEND_UPDATES}' inválido. "
        f"Valores permitidos: {', '.join(_VALID_SEND_UPDATES)}",
        file=sys.stderr,
    )
    sys.exit(1)

# Google Calendar color mapping (optional)
# Maps TipoEvento.nome → Google Calendar colorId (1-11)
# https://developers.google.com/calendar/api/v3/reference/colors
GCAL_COLOR_MAP = {
    # Example mappings (customize as needed):
    # "Formação": 9,           # Blue
    # "Acompanhamento": 10,    # Green
    # "Reunião": 11,           # Red
}

# ================================================================
# AVAILABILITY & ETL SETTINGS (Cláusulas Pétreas RD-01..RD-08)
# ================================================================
# RD-06: Timezone do projeto (America/Fortaleza)
TZ_PROJECT = TIME_ZONE  # Herda do TIME_ZONE acima

# RD-05: Limite diário de horas por formador (configurável)
AVAILABILITY_DAILY_LIMIT_HOURS = int(os.getenv("AVAILABILITY_DAILY_LIMIT_HOURS", "8"))

# RD-04: Buffer de deslocamento entre municípios distintos (minutos)
TRAVEL_BUFFER_MINUTES = int(os.getenv("TRAVEL_BUFFER_MINUTES", "120"))

# ETL: Diretórios configuráveis para importação/exportação
ETL_OUTPUT_DIR = os.getenv("ETL_OUTPUT_DIR", str(BASE_DIR / "out_etl"))
ETL_DATA_DIR = os.getenv("ETL_DATA_DIR", str(BASE_DIR / "data" / "csv-import"))

# ETL: Diretório padrão para importação de arquivos (backwards compatibility)
# NOTE: ETL_DATA_DIR é o padrão preferido. DATA_IMPORT_DIR mantido para
# compatibilidade com management commands existentes (etl_all, etl_load_xlsx).
DATA_IMPORT_DIR = os.getenv("DATA_IMPORT_DIR", "/app/data/csv-import")

# ================================================================
# BACKUP (MP5)
# ================================================================
BACKUP_DIR = os.getenv("BACKUP_DIR", "/backups")
BACKUP_RETENTION_DAYS = int(os.getenv("BACKUP_RETENTION_DAYS", "7"))
# S3 bucket name (without s3://). Use empty string to disable uploads.
BACKUP_S3_BUCKET = os.getenv("BACKUP_S3_BUCKET", "")

# ================================================================
# PR21: external_hash v2 + Data Quality Gates
# ================================================================
# Feature flag: usa hash v2 (17 campos) ao invés de v1 (8 campos)
USE_EXTERNAL_HASH_V2 = os.getenv("USE_EXTERNAL_HASH_V2", "True") == "True"

# Data Quality Gates: limites para abortar ETL apply
ETL_MAX_DUPLICATES_PCT = float(os.getenv("ETL_MAX_DUPLICATES_PCT", "1.0"))  # 1.0% máximo de duplicatas

ETL_MAX_UNKNOWN_USERS = int(os.getenv("ETL_MAX_UNKNOWN_USERS", "100"))  # Máximo de pessoas sem cadastro

ETL_REQUIRE_ZERO_INVALID_INTERVALS = (
    os.getenv("ETL_REQUIRE_ZERO_INVALID_INTERVALS", "True") == "True"
)  # Se True, aborta se houver intervalos inválidos (fim <= início)

ETL_REQUIRE_ZERO_INVALID_DATES = (
    os.getenv("ETL_REQUIRE_ZERO_INVALID_DATES", "True") == "True"
)  # Se True, aborta se houver datas/horas inválidas

# ================================================================
# RBAC: Grupos permitidos para usuários (Issue #254)
# ================================================================
# Fonte única de verdade: apps/core/constants.py
# Importado aqui para manter compatibilidade com código que lê settings.ALLOWED_USER_GROUPS
from apps.core.constants import ALLOWED_USER_GROUPS  # noqa: E402, F401

# ================================================================
# SECURITY (Production)
# ================================================================
# Security Audit 2025-01: Implementação de headers de segurança
# Refs: OWASP, API Security Checklist, vibe-security

if not DEBUG:
    # --- SSL/TLS ---
    _ssl_default = "1" if ENVIRONMENT not in ("testing", "development") else "0"
    SECURE_SSL_REDIRECT = os.getenv("SECURE_SSL_REDIRECT", _ssl_default) == "1"
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # --- Reverse Proxy Support ---
    # Required when running behind Nginx with SSL termination
    # Nginx sets X-Forwarded-Proto header to indicate original protocol
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

    # --- HSTS (HTTP Strict Transport Security) ---
    # Força navegadores a usar HTTPS por 1 ano
    # Previne ataques SSL stripping e downgrade
    SECURE_HSTS_SECONDS = 31536000  # 1 ano
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True  # Permite inclusão na lista de preload dos browsers

    # --- Content Security Headers ---
    SECURE_BROWSER_XSS_FILTER = True  # X-XSS-Protection (legacy, mas ainda útil)
    SECURE_CONTENT_TYPE_NOSNIFF = True  # X-Content-Type-Options: nosniff
    X_FRAME_OPTIONS = "DENY"  # Previne clickjacking

    # --- Referrer Policy ---
    # Controla quanta informação é enviada no header Referer
    SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"

    # --- Cross-Origin Headers ---
    # Previne ataques de opener e embedder
    SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"

# ================================================================
# ACCOUNT LOCKOUT (Brute Force Protection)
# ================================================================
# Bloqueia conta após N tentativas falhas de login
# Refs: OWASP Authentication Cheat Sheet
ACCOUNT_LOCKOUT_THRESHOLD = int(os.getenv("ACCOUNT_LOCKOUT_THRESHOLD", "10"))  # Tentativas
ACCOUNT_LOCKOUT_DURATION = int(os.getenv("ACCOUNT_LOCKOUT_DURATION", "900"))  # 15 min (segundos)

# ================================================================
# SENTRY APM (MP3: Distributed Tracing & Error Tracking)
# ================================================================
# Refs: Issue #167, PLANO_MELHORIAS_DETALHADO.md (MP3)
SENTRY_DSN = os.getenv("SENTRY_DSN", "")  # Empty string disables Sentry

if SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.celery import CeleryIntegration
    from sentry_sdk.integrations.django import DjangoIntegration

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        # Integrations
        integrations=[
            DjangoIntegration(
                # Capture SQL queries (useful for N+1 detection)
                transaction_style="url",  # Group by URL pattern
                middleware_spans=True,  # Track middleware execution
                signals_spans=True,  # Track Django signals
            ),
            CeleryIntegration(
                # Monitor async tasks (worker + beat)
                monitor_beat_tasks=True,  # Track beat scheduler
                propagate_traces=True,  # Distributed tracing across tasks
            ),
        ],
        # Performance monitoring
        traces_sample_rate=float(os.getenv("SENTRY_TRACES_SAMPLE_RATE", "0.1")),  # 10% of transactions
        # Error sampling (100% = capture all errors)
        sample_rate=1.0,
        # Environment & Release tracking
        environment=ENVIRONMENT,  # development/staging/production
        release=os.getenv("GIT_COMMIT_SHA", "unknown"),  # Track deployments
        # Additional context
        send_default_pii=False,  # Don't send PII (LGPD/GDPR compliance)
        attach_stacktrace=True,  # Include stack traces for breadcrumbs
        # Performance options
        profiles_sample_rate=float(os.getenv("SENTRY_PROFILES_SAMPLE_RATE", "0.0")),  # Profiling (disabled by default)
        # Before send hook (optional: filter errors)
        # before_send=lambda event, hint: event if should_send_to_sentry(event) else None,
    )

    # Optional: Set user context in views/middleware
    # from sentry_sdk import set_user
    # set_user({"id": user.id, "email": user.email, "username": user.username})

# ================================================================
# QUERY PROFILING (Development & Staging)
# ================================================================
# Gap 5: Query Profiling tools for N+1 detection and performance analysis

# Django Debug Toolbar (DEBUG mode only, must be installed)
try:
    import debug_toolbar  # noqa: F401

    if DEBUG:
        INSTALLED_APPS += ["debug_toolbar"]
        MIDDLEWARE.insert(0, "debug_toolbar.middleware.DebugToolbarMiddleware")
        INTERNAL_IPS = ["127.0.0.1", "localhost", "0.0.0.0"]
        DEBUG_TOOLBAR_CONFIG: dict[str, object] = {
            # Disable toolbar during tests to avoid NoReverseMatch errors
            "SHOW_TOOLBAR_CALLBACK": lambda request: DEBUG and not TESTING,  # type: ignore[misc]
            "DISABLE_PANELS": {
                "debug_toolbar.panels.redirects.RedirectsPanel",
                "debug_toolbar.panels.profiling.ProfilingPanel",
            },
            "SHOW_TEMPLATE_CONTEXT": True,
        }
except ImportError:
    pass  # Not installed in production image

# Django Silk (Staging profiler, must be installed)
try:
    import silk  # noqa: F401

    if ENVIRONMENT == "staging":
        INSTALLED_APPS += ["silk"]
        MIDDLEWARE += ["silk.middleware.SilkyMiddleware"]
        SILKY_PYTHON_PROFILER = True
        SILKY_PYTHON_PROFILER_BINARY = True
        SILKY_META = True
        SILKY_MAX_REQUEST_BODY_SIZE = -1  # Unlimited
        SILKY_MAX_RESPONSE_BODY_SIZE = 1024  # 1KB
        SILKY_INTERCEPT_PERCENT = 100  # Profile all requests
except ImportError:
    pass  # Not installed in production image
