from typing import Any, List, TypeVar, Union

from django.db.models import QuerySet
from rest_framework.filters import BaseFilterBackend
from rest_framework.views import APIView

_Q = TypeVar("_Q", bound=Union[QuerySet[Any], Any])

class DjangoFilterBackend(BaseFilterBackend):
    def filter_queryset(self, request: Any, queryset: _Q, view: APIView) -> _Q: ...
    def get_filterset_class(self, view: Any, queryset: Any | None = ...) -> Any: ...
    def get_filterset(self, request: Any, queryset: Any, view: Any) -> Any: ...
    def get_schema_fields(self, view: APIView) -> List[Any]: ...
    def get_schema_operation_parameters(self, view: APIView) -> Any: ...
