from typing import Any

from rest_framework.filters import BaseFilterBackend

class DjangoFilterBackend(BaseFilterBackend):
    def filter_queryset(self, request: Any, queryset: Any, view: Any) -> Any: ...
    def get_filterset_class(self, view: Any, queryset: Any | None = ...) -> Any: ...
    def get_filterset(self, request: Any, queryset: Any, view: Any) -> Any: ...
    def get_schema_fields(self, view: Any) -> list[Any]: ...
    def get_schema_operation_parameters(self, view: Any) -> list[dict[str, Any]]: ...
