services:
  db:
    image: postgres:15
    container_name: aprender_db
    environment:
      POSTGRES_DB: aprender_sistema_db
      POSTGRES_USER: adm_aprender
      POSTGRES_PASSWORD: aprender123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U adm_aprender -d aprender_sistema_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build: .
    container_name: aprender_web
    environment:
      DB_NAME: aprender_sistema_db
      DB_USER: adm_aprender
      DB_PASSWORD: aprender123456
      DB_HOST: db
      DB_PORT: "5432"
      DJANGO_ENV: development
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_data: