# Generated by Django 5.2.4 on 2025-09-30 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20250925_1733'),
    ]

    operations = [
    ]
