# Generated by Django 4.2.25 on 2025-10-01 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_auto_20250929_2132"),
    ]

    operations = [
        # ====================================
        # NOVOS MODELOS CANÔNICOS
        # ====================================

        # VinculoUsuarioSetor
        migrations.CreateModel(
            name='VinculoUsuarioSetor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('GERENTE', 'Gerente'), ('COORDENADOR', 'Coordenador'), ('FORMADOR', 'Formador')], max_length=20, verbose_name='Papel')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_usuarios', to='core.setor', verbose_name='Setor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_setores', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Vínculo Usuário-Setor',
                'verbose_name_plural': 'Vínculos Usuário-Setor',
                'ordering': ['setor__nome', 'papel', 'usuario__username'],
            },
        ),
        migrations.AddIndex(
            model_name='vinculousuariosetor',
            index=models.Index(fields=['usuario', 'setor'], name='core_vincul_usuario_idx'),
        ),
        migrations.AddIndex(
            model_name='vinculousuariosetor',
            index=models.Index(fields=['setor', 'papel'], name='core_vincul_setor_i_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vinculousuariosetor',
            unique_together={('usuario', 'setor', 'papel')},
        ),

        # Participante
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('FORMADOR', 'Formador'), ('COORDENADOR', 'Coordenador'), ('APOIO', 'Apoio')], max_length=20, verbose_name='Papel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='core.solicitacao', verbose_name='Solicitação')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participacoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
                'ordering': ['solicitacao', 'papel', 'usuario__username'],
            },
        ),
        migrations.AddIndex(
            model_name='participante',
            index=models.Index(fields=['solicitacao', 'papel'], name='core_partic_solicit_idx'),
        ),
        migrations.AddIndex(
            model_name='participante',
            index=models.Index(fields=['usuario', 'papel'], name='core_partic_usuario_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='participante',
            unique_together={('solicitacao', 'usuario', 'papel')},
        ),

        # MarcadorPlanilha
        migrations.CreateModel(
            name='MarcadorPlanilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_hash', models.CharField(db_index=True, help_text='SHA256 dos dados brutos da planilha', max_length=64, unique=True, verbose_name='Hash Externo')),
                ('tipo_entidade', models.CharField(db_index=True, help_text='Ex: usuario, evento, disponibilidade', max_length=50, verbose_name='Tipo de Entidade')),
                ('entidade_id', models.UUIDField(blank=True, help_text='UUID do registro criado/atualizado', null=True, verbose_name='ID da Entidade')),
                ('raw_data', models.JSONField(help_text='Snapshot dos dados originais da planilha', verbose_name='Dados Brutos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Marcador de Planilha',
                'verbose_name_plural': 'Marcadores de Planilhas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='marcadorplanilha',
            index=models.Index(fields=['tipo_entidade', 'external_hash'], name='core_marcad_tipo_en_idx'),
        ),
        migrations.AddIndex(
            model_name='marcadorplanilha',
            index=models.Index(fields=['entidade_id'], name='core_marcad_entidad_idx'),
        ),
        migrations.AddIndex(
            model_name='marcadorplanilha',
            index=models.Index(fields=['-created_at'], name='core_marcad_created_idx'),
        ),

        # AprovacaoHistorico
        migrations.CreateModel(
            name='AprovacaoHistorico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status_anterior', models.CharField(choices=[('Pendente', 'Pendente'), ('PreAgenda', 'Pré-Agenda'), ('Agendado', 'Agendado'), ('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado'), ('Realizado', 'Realizado'), ('Cancelado', 'Cancelado')], max_length=20, verbose_name='Status Anterior')),
                ('status_novo', models.CharField(choices=[('Pendente', 'Pendente'), ('PreAgenda', 'Pré-Agenda'), ('Agendado', 'Agendado'), ('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado'), ('Realizado', 'Realizado'), ('Cancelado', 'Cancelado')], max_length=20, verbose_name='Status Novo')),
                ('decisao', models.CharField(choices=[('Aprovado', 'Aprovado'), ('Reprovado', 'Reprovado')], max_length=20, verbose_name='Decisão')),
                ('justificativa', models.TextField(blank=True, null=True, verbose_name='Justificativa')),
                ('data_decisao', models.DateTimeField(auto_now_add=True)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_aprovacoes', to='core.solicitacao', verbose_name='Solicitação')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisoes_historico', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
            options={
                'verbose_name': 'Histórico de Aprovação',
                'verbose_name_plural': 'Históricos de Aprovações',
                'ordering': ['-data_decisao'],
            },
        ),
        migrations.AddIndex(
            model_name='aprovacaohistorico',
            index=models.Index(fields=['solicitacao', '-data_decisao'], name='core_aprova_solicit_idx'),
        ),
        migrations.AddIndex(
            model_name='aprovacaohistorico',
            index=models.Index(fields=['usuario', '-data_decisao'], name='core_aprova_usuario_idx'),
        ),
        migrations.AddIndex(
            model_name='aprovacaohistorico',
            index=models.Index(fields=['-data_decisao'], name='core_aprova_data_de_idx'),
        ),

        # ====================================
        # NOVOS STATUS EM SOLICITACAOSTATUS
        # ====================================
        migrations.AlterField(
            model_name='solicitacao',
            name='status',
            field=models.CharField(
                choices=[
                    ('Pendente', 'Pendente'),
                    ('PreAgenda', 'Pré-Agenda'),
                    ('Agendado', 'Agendado'),
                    ('Aprovado', 'Aprovado'),
                    ('Reprovado', 'Reprovado'),
                    ('Realizado', 'Realizado'),
                    ('Cancelado', 'Cancelado'),
                ],
                default='Pendente',
                max_length=20
            ),
        ),

        # ====================================
        # NOVO CAMPO: Solicitacao.remarcado_para
        # ====================================
        migrations.AddField(
            model_name='solicitacao',
            name='remarcado_para',
            field=models.ForeignKey(
                blank=True,
                help_text='Se esta solicitação foi remarcada, referência para a nova solicitação',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='remarcacoes_anteriores',
                to='core.solicitacao',
                verbose_name='Remarcado Para'
            ),
        ),

        # ====================================
        # NOVOS CAMPOS: EventoGoogleCalendar (idempotência)
        # ====================================
        migrations.AddField(
            model_name='eventogooglecalendar',
            name='request_id',
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text='ID único da requisição para idempotência',
                max_length=64,
                null=True,
                verbose_name='Request ID'
            ),
        ),
        migrations.AddField(
            model_name='eventogooglecalendar',
            name='hash_payload',
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text='SHA256 do payload enviado ao Google Calendar',
                max_length=64,
                null=True,
                verbose_name='Hash do Payload'
            ),
        ),
        migrations.AddField(
            model_name='eventogooglecalendar',
            name='tentativas',
            field=models.PositiveIntegerField(
                default=0,
                help_text='Número de tentativas de sincronização',
                verbose_name='Tentativas'
            ),
        ),
        migrations.AddField(
            model_name='eventogooglecalendar',
            name='ultimo_erro',
            field=models.TextField(
                blank=True,
                help_text='Descrição do último erro ocorrido',
                null=True,
                verbose_name='Último Erro'
            ),
        ),
        migrations.AddField(
            model_name='eventogooglecalendar',
            name='ultima_tentativa',
            field=models.DateTimeField(
                blank=True,
                help_text='Data/hora da última tentativa de sincronização',
                null=True,
                verbose_name='Última Tentativa'
            ),
        ),
    ]
