# Generated by Django 4.2.25 on 2025-10-02 00:46
# Hotfix Dia 3: Adiciona campo origem em AprovacaoHistorico e torna usuario opcional

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_status_rename"),
    ]

    operations = [
        # Primeiro tornar campo usuario opcional
        migrations.AlterField(
            model_name='aprovacaohistorico',
            name='usuario',
            field=models.ForeignKey(
                blank=True,
                help_text='Usuário que tomou a decisão (null para importações de planilha)',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='decisoes_historico',
                to='core.usuario',
                verbose_name='Usuário Responsável'
            ),
        ),
        # Adicionar campo origem
        migrations.AddField(
            model_name='aprovacaohistorico',
            name='origem',
            field=models.CharField(
                default='sistema',
                help_text='Ex: planilha, sistema, api',
                max_length=50,
                verbose_name='Origem'
            ),
        ),
    ]
