# Generated by Django 4.2.25 on 2025-10-03 00:04

import core.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0039_usuario_not_null"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="disponibilidadeformadores",
            options={
                "ordering": ["usuario", "data_bloqueio", "hora_inicio"],
                "verbose_name": "Disponibilidade de Formador",
                "verbose_name_plural": "Disponibilidades de Formadores",
            },
        ),
        migrations.AlterModelOptions(
            name="marcadorplanilha",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Marcador de Planilha",
                "verbose_name_plural": "Marcadores de Planilha",
            },
        ),
        migrations.AlterModelManagers(
            name="usuario",
            managers=[
                ("objects", core.models.UsuarioManager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="deslocamento",
            name="data_not_too_far_future",
        ),
        migrations.RemoveConstraint(
            model_name="projetocursolink",
            name="unique_projeto_curso_link",
        ),
        migrations.RemoveIndex(
            model_name="marcadorplanilha",
            name="core_marcad_tipo_en_idx",
        ),
        migrations.RemoveIndex(
            model_name="marcadorplanilha",
            name="core_marcad_entidad_idx",
        ),
        migrations.RemoveIndex(
            model_name="marcadorplanilha",
            name="core_marcad_created_idx",
        ),
        migrations.RenameIndex(
            model_name="aprovacaohistorico",
            new_name="core_aprova_solicit_8b8b12_idx",
            old_name="core_aprova_solicit_idx",
        ),
        migrations.RenameIndex(
            model_name="aprovacaohistorico",
            new_name="core_aprova_usuario_31c880_idx",
            old_name="core_aprova_usuario_idx",
        ),
        migrations.RenameIndex(
            model_name="aprovacaohistorico",
            new_name="core_aprova_data_de_cc4005_idx",
            old_name="core_aprova_data_de_idx",
        ),
        migrations.RenameIndex(
            model_name="cursoplataforma",
            new_name="core_cursop_id_curs_4c4954_idx",
            old_name="core_cursop_id_curs_8cbbee_idx",
        ),
        migrations.RenameIndex(
            model_name="cursoplataforma",
            new_name="core_cursop_categor_82d243_idx",
            old_name="core_cursop_categor_c0ee04_idx",
        ),
        migrations.RenameIndex(
            model_name="cursoplataforma",
            new_name="core_cursop_ano_8e7e79_idx",
            old_name="core_cursop_ano_91bd6f_idx",
        ),
        migrations.RenameIndex(
            model_name="participante",
            new_name="core_partic_solicit_accc93_idx",
            old_name="core_partic_solicit_idx",
        ),
        migrations.RenameIndex(
            model_name="participante",
            new_name="core_partic_usuario_766e54_idx",
            old_name="core_partic_usuario_idx",
        ),
        migrations.RenameIndex(
            model_name="vinculousuariosetor",
            new_name="core_vincul_usuario_b03f42_idx",
            old_name="core_vincul_usuario_idx",
        ),
        migrations.RenameIndex(
            model_name="vinculousuariosetor",
            new_name="core_vincul_setor_i_dc4e22_idx",
            old_name="core_vincul_setor_i_idx",
        ),
        migrations.RemoveField(
            model_name="marcadorplanilha",
            name="entidade_id",
        ),
        migrations.RemoveField(
            model_name="marcadorplanilha",
            name="raw_data",
        ),
        migrations.RemoveField(
            model_name="marcadorplanilha",
            name="tipo_entidade",
        ),
        migrations.AddField(
            model_name="marcadorplanilha",
            name="cancelado_flag",
            field=models.BooleanField(
                default=False,
                help_text="Se o evento foi marcado como cancelado na planilha",
            ),
        ),
        migrations.AddField(
            model_name="marcadorplanilha",
            name="disponibilidade",
            field=models.ForeignKey(
                blank=True,
                help_text="Disponibilidade associada (se aplicável)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="marcadores_planilha",
                to="core.disponibilidadeformadores",
            ),
        ),
        migrations.AddField(
            model_name="marcadorplanilha",
            name="gid",
            field=models.CharField(
                blank=True,
                help_text="ID da linha na planilha (Google Sheets gid)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="marcadorplanilha",
            name="linha",
            field=models.IntegerField(
                blank=True, help_text="Número da linha na planilha", null=True
            ),
        ),
        migrations.AddField(
            model_name="marcadorplanilha",
            name="origem_aba",
            field=models.CharField(
                blank=True, help_text="Nome da aba de origem", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="marcadorplanilha",
            name="remarcado_para",
            field=models.ForeignKey(
                blank=True,
                help_text="Marcador da nova data (para eventos remarcados)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="remarcado_de",
                to="core.marcadorplanilha",
            ),
        ),
        migrations.AddField(
            model_name="marcadorplanilha",
            name="solicitacao",
            field=models.ForeignKey(
                blank=True,
                help_text="Solicitação associada (se aplicável)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="marcadores_planilha",
                to="core.solicitacao",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="is_provisorio",
            field=models.BooleanField(
                default=False,
                help_text="Usuário criado automaticamente pela importação, aguardando reconciliação com planilha Ativos",
                verbose_name="Cadastro Provisório",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="origem",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Origem do cadastro: 'planilha', 'manual', etc.",
                max_length=50,
                verbose_name="Origem do Cadastro",
            ),
        ),
        migrations.AlterField(
            model_name="aprovacaohistorico",
            name="status_anterior",
            field=models.CharField(
                choices=[
                    ("CRIADO", "Criado"),
                    ("APROVADO", "Aprovado"),
                    ("AGENDADO", "Agendado"),
                    ("REALIZADO", "Realizado"),
                    ("CANCELADO", "Cancelado"),
                ],
                max_length=20,
                verbose_name="Status Anterior",
            ),
        ),
        migrations.AlterField(
            model_name="aprovacaohistorico",
            name="status_novo",
            field=models.CharField(
                choices=[
                    ("CRIADO", "Criado"),
                    ("APROVADO", "Aprovado"),
                    ("AGENDADO", "Agendado"),
                    ("REALIZADO", "Realizado"),
                    ("CANCELADO", "Cancelado"),
                ],
                max_length=20,
                verbose_name="Status Novo",
            ),
        ),
        migrations.AlterField(
            model_name="marcadorplanilha",
            name="external_hash",
            field=models.CharField(
                db_index=True,
                help_text="Hash SHA256 para garantir idempotência da importação",
                max_length=64,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="marcadorplanilha",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="marcadorplanilha",
            name="origem",
            field=models.CharField(
                blank=True,
                help_text="Fonte da importação (sheets:aba ou csv:arquivo)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="participante",
            name="papel",
            field=models.CharField(
                choices=[
                    ("FORMADOR", "Formador"),
                    ("COORDENADOR", "Coordenador"),
                    ("COORDENADOR_ACOMPANHA", "Coordenador Acompanha"),
                    ("CONVIDADO", "Convidado"),
                    ("APOIO", "Apoio"),
                ],
                max_length=30,
                verbose_name="Papel",
            ),
        ),
        migrations.AlterField(
            model_name="solicitacao",
            name="formadores",
            field=models.ManyToManyField(
                related_name="solicitacoes_como_formador",
                through="core.FormadoresSolicitacao",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="solicitacao",
            name="status",
            field=models.CharField(
                choices=[
                    ("CRIADO", "Criado"),
                    ("APROVADO", "Aprovado"),
                    ("AGENDADO", "Agendado"),
                    ("REALIZADO", "Realizado"),
                    ("CANCELADO", "Cancelado"),
                ],
                default="CRIADO",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="area_atuacao",
            field=models.ForeignKey(
                blank=True,
                help_text="Área de atuação como Group (compatibilidade com Formador)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usuarios_area_atuacao",
                to="auth.group",
                verbose_name="Área de Atuação (Group)",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to.",
                related_name="usuarios",
                related_query_name="usuario",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="usuarios",
                related_query_name="usuario",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="projetocursolink",
            unique_together={("projeto", "curso_plataforma")},
        ),
        migrations.AddIndex(
            model_name="marcadorplanilha",
            index=models.Index(
                fields=["external_hash"], name="core_marcad_externa_54f757_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="marcadorplanilha",
            index=models.Index(
                fields=["origem_aba", "linha"], name="core_marcad_origem__56d076_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="marcadorplanilha",
            index=models.Index(
                fields=["cancelado_flag"], name="core_marcad_cancela_343514_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="deslocamento",
            constraint=models.CheckConstraint(
                check=models.Q(("data__lte", datetime.date(2026, 10, 3))),
                name="data_not_too_far_future",
                violation_error_message="Data não pode ser mais de 1 ano no futuro.",
            ),
        ),
    ]
