# Generated by Django 4.2.25 on 2025-10-03 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_sync_marcador_and_usuario_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="solicitacao",
            options={
                "ordering": ["-data_solicitacao"],
                "permissions": [
                    ("sync_calendar", "Can sync with Google Calendar"),
                    (
                        "view_own_solicitacoes",
                        "Can view own solicitações (Coordenador)",
                    ),
                    (
                        "can_controlar_preagenda",
                        "Can manage pre-agenda queue (Controle)",
                    ),
                ],
            },
        ),
    ]
