# Generated by Django 4.2.25 on 2025-10-04 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_formador_email_nullable"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="deslocamento",
            name="data_not_too_far_future",
        ),
        migrations.AddConstraint(
            model_name="deslocamento",
            constraint=models.CheckConstraint(
                check=models.Q(("data__lte", datetime.date(2026, 10, 4))),
                name="data_not_too_far_future",
                violation_error_message="Data não pode ser mais de 1 ano no futuro.",
            ),
        ),
    ]
