# Generated by Django 4.2.25 on 2025-10-05 15:34

from django.db import migrations


def forwards(apps, schema_editor):
    """
    Arquiva a tabela legacy ingestao_disp_staging:
    1. Renomeia para ingestao_disp_staging_archive_20251005
    2. Cria VIEW com nome original para compatibilidade
    """
    with schema_editor.connection.cursor() as cursor:
        # Renomear tabela (apenas se existir)
        cursor.execute("""
            DO $$
            BEGIN
              IF to_regclass('public.ingestao_disp_staging') IS NOT NULL THEN
                ALTER TABLE public.ingestao_disp_staging
                RENAME TO ingestao_disp_staging_archive_20251005;
              END IF;
            END $$;
        """)

        # Criar VIEW compatível
        cursor.execute("""
            DROP VIEW IF EXISTS public.ingestao_disp_staging;
            CREATE VIEW public.ingestao_disp_staging AS
              SELECT * FROM public.ingestao_disp_staging_archive_20251005;
        """)


def backwards(apps, schema_editor):
    """
    Reverte o arquivamento:
    1. Remove VIEW
    2. Renomeia tabela archive de volta ao nome original
    """
    with schema_editor.connection.cursor() as cursor:
        # Remover VIEW
        cursor.execute("DROP VIEW IF EXISTS public.ingestao_disp_staging;")

        # Renomear tabela de volta (apenas se existir)
        cursor.execute("""
            DO $$
            BEGIN
              IF to_regclass('public.ingestao_disp_staging_archive_20251005') IS NOT NULL THEN
                ALTER TABLE public.ingestao_disp_staging_archive_20251005
                RENAME TO ingestao_disp_staging;
              END IF;
            END $$;
        """)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_disponibilidades_staging"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
