# Generated by Django - Normalização de papéis em VinculoUsuarioSetor
from django.db import migrations


def forwards(apps, schema_editor):
    """
    Normaliza valores de papel para padrão canônico em CAIXA ALTA.
    Mapeia variantes em minúsculas e nomes alternativos para valores canônicos.
    """
    VinculoUsuarioSetor = apps.get_model('core', 'VinculoUsuarioSetor')

    # Mapeamento de variantes para valores canônicos
    mapping = {
        'formador': 'FORMADOR',
        'coordenador': 'COORDENADOR',
        'controle': 'CONTROLE',
        'super': 'SUPER',
        'superintendencia': 'SUPER',
        'superintendência': 'SUPER',
        'gerente': 'GERENTE',
    }

    total_updated = 0
    for old_value, new_value in mapping.items():
        # Usar iexact para case-insensitive
        count = VinculoUsuarioSetor.objects.filter(papel__iexact=old_value).update(papel=new_value)
        if count > 0:
            print(f"  ✓ Normalizados {count} vínculos de '{old_value}' → '{new_value}'")
            total_updated += count

    if total_updated == 0:
        print("  ℹ Nenhum vínculo precisou ser normalizado")
    else:
        print(f"  ✓ Total: {total_updated} vínculos normalizados")


def backwards(apps, schema_editor):
    """
    Não é necessário reverter pois os valores em CAIXA ALTA são compatíveis.
    """
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0046_remove_deslocamento_data_not_too_far_future_and_more'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
