# Generated by Django - Constraints e índices para VinculoUsuarioSetor
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0047_normalize_papel_vinculos'),
    ]

    operations = [
        # Adicionar índice (usuario, papel) para otimizar buscas por papel de usuário
        # Nota: O índice (usuario, setor) já existe na Meta do modelo
        migrations.AddIndex(
            model_name='vinculousuariosetor',
            index=models.Index(fields=['usuario', 'papel'], name='idx_vinculo_user_papel'),
        ),

        # Adicionar constraint de validação de papel
        # Garante que apenas valores canônicos sejam aceitos
        migrations.AddConstraint(
            model_name='vinculousuariosetor',
            constraint=models.CheckConstraint(
                name='ck_vinculo_papel_valid',
                check=Q(papel__in=['GERENTE', 'COORDENADOR', 'FORMADOR', 'CONTROLE', 'SUPER']),
                violation_error_message='Papel deve ser um dos valores canônicos: GERENTE, COORDENADOR, FORMADOR, CONTROLE, SUPER'
            ),
        ),

        # Nota: unique_together já existe no Meta do modelo como (usuario, setor, papel)
        # Não é necessário adicionar UniqueConstraint separado
    ]
