# Generated by Django 4.2.25 on 2025-10-08 01:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0053_map_deslocamento_users"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="deslocamento",
            name="data_not_too_far_future",
        ),
        # Campos abaixo nunca existiram na tabela (comentados para fake)
        # migrations.RemoveField(
        #     model_name="marcadorplanilha",
        #     name="disponibilidade",
        # ),
        # migrations.RemoveField(
        #     model_name="marcadorplanilha",
        #     name="remarcado_para",
        # ),
        # migrations.RemoveField(
        #     model_name="marcadorplanilha",
        #     name="solicitacao",
        # ),
        migrations.AddConstraint(
            model_name="deslocamento",
            constraint=models.CheckConstraint(
                check=models.Q(("data__lte", datetime.date(2026, 10, 8))),
                name="data_not_too_far_future",
                violation_error_message="Data não pode ser mais de 1 ano no futuro.",
            ),
        ),
    ]
