# Generated by Django 4.2.25 on 2025-10-08 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_remove_deslocamento_data_not_too_far_future_and_more"),
    ]

    operations = [
        # Campos nunca existiram na tabela - migração no-op
    ]
