# Django REST Framework Type Stubs
# Custom type hints for DRF-specific patterns in Aprender Sistema v2

from typing import Any, Generic, TypeVar

from django.db import models

_T = TypeVar("_T", bound=models.Model)

# ModelSerializer with Generic support
class ModelSerializer(Generic[_T]):
    def __init__(self, instance: _T | None = None, data: dict[str, Any] | None = None, **kwargs): ...
    def is_valid(self, raise_exception: bool = False) -> bool: ...
    def save(self, **kwargs) -> _T: ...
    def create(self, validated_data: dict[str, Any]) -> _T: ...
    def update(self, instance: _T, validated_data: dict[str, Any]) -> _T: ...
    @property
    def validated_data(self) -> dict[str, Any]: ...
    @property
    def errors(self) -> dict[str, list[str]]: ...
    @property
    def data(self) -> dict[str, Any]: ...

# ViewSet with Generic support
class ModelViewSet(Generic[_T]):
    queryset: models.QuerySet[_T]
    serializer_class: type[ModelSerializer[_T]]

    def get_queryset(self) -> models.QuerySet[_T]: ...
    def get_object(self) -> _T: ...
    def get_serializer(self, *args, **kwargs) -> ModelSerializer[_T]: ...
    def get_serializer_class(self) -> type[ModelSerializer[_T]]: ...

# Response
class Response:
    def __init__(self, data: Any = None, status: int | None = None, **kwargs): ...

# Request
class Request:
    user: Any
    data: dict[str, Any]
    query_params: dict[str, Any]
    META: dict[str, Any]
