# Generated by Django 4.2.25 on 2025-10-09 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StgControleUnificado",
            fields=[
                (
                    "row_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA1(municipio|projeto|uf|gerencia)",
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("municipio", models.CharField(blank=True, default="", max_length=200)),
                ("projeto", models.CharField(blank=True, default="", max_length=200)),
                ("uf", models.CharField(blank=True, default="", max_length=2)),
                ("gerencia", models.CharField(blank=True, default="", max_length=200)),
                ("qtd_compras", models.IntegerField(default=0)),
                ("soma_quant", models.IntegerField(default=0)),
                ("primeira_data_compra", models.DateField(blank=True, null=True)),
                ("data_entrega", models.DateField(blank=True, null=True)),
                ("data_carta", models.DateField(blank=True, null=True)),
                ("data_reuniao_alinhamento", models.DateField(blank=True, null=True)),
                ("contato_inicial", models.TextField(blank=True, default="")),
                ("observacao_concat", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Staging Controle Unificado",
                "verbose_name_plural": "Staging Controle Unificado",
                "db_table": "stg_controle_unificado",
                "ordering": ["municipio", "projeto"],
            },
        ),
        migrations.CreateModel(
            name="StgDispBloqueio",
            fields=[
                (
                    "row_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA1(data_inicial|data_final|tipo|responsavel)",
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("data_inicial", models.DateField(blank=True, null=True)),
                ("data_final", models.DateField(blank=True, null=True)),
                ("tipo", models.CharField(blank=True, default="", max_length=100)),
                (
                    "responsavel",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Staging Bloqueio Disponibilidade",
                "verbose_name_plural": "Staging Bloqueios Disponibilidade",
                "db_table": "stg_disp_bloqueio",
                "ordering": ["-data_inicial", "responsavel"],
            },
        ),
        migrations.CreateModel(
            name="StgDispDeslocamento",
            fields=[
                (
                    "row_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA1(origem|data|destino|responsavel)",
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("origem", models.CharField(blank=True, default="", max_length=200)),
                ("data", models.DateField(blank=True, null=True)),
                ("destino", models.CharField(blank=True, default="", max_length=200)),
                (
                    "responsavel",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Staging Deslocamento",
                "verbose_name_plural": "Staging Deslocamentos",
                "db_table": "stg_disp_deslocamento",
                "ordering": ["-data", "responsavel"],
            },
        ),
        migrations.CreateModel(
            name="StgEvento",
            fields=[
                (
                    "external_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA1 hash da linha original (chave única)",
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("planilha", models.CharField(blank=True, default="", max_length=200)),
                ("aba", models.CharField(blank=True, default="", max_length=100)),
                ("fluxo", models.CharField(blank=True, default="", max_length=50)),
                ("aprovacao", models.CharField(blank=True, default="", max_length=100)),
                (
                    "aprovado_futuro",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                (
                    "criado_na_agenda",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                (
                    "municipio",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=200
                    ),
                ),
                ("encontro", models.CharField(blank=True, default="", max_length=50)),
                ("tipo", models.CharField(blank=True, default="", max_length=200)),
                ("data", models.DateField(blank=True, db_index=True, null=True)),
                ("hora_inicio", models.TimeField(blank=True, null=True)),
                ("hora_fim", models.TimeField(blank=True, null=True)),
                ("projeto", models.CharField(blank=True, default="", max_length=200)),
                ("segmento", models.CharField(blank=True, default="", max_length=200)),
                (
                    "coord_acompanha",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "coordenador",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("formadores", models.TextField(blank=True, default="")),
                ("convidados", models.TextField(blank=True, default="")),
                (
                    "cancelado_info",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "solicitante",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "status_temporal",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="passado, futuro, indefinido",
                        max_length=20,
                    ),
                ),
                (
                    "tempo_alerta",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Staging Evento",
                "verbose_name_plural": "Staging Eventos",
                "db_table": "stg_evento",
                "ordering": ["-data", "-hora_inicio"],
            },
        ),
        migrations.CreateModel(
            name="StgEventoPessoa",
            fields=[
                (
                    "row_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA1(event_external_hash|role|name)",
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("COORDENADOR", "Coordenador"),
                            ("FORMADOR", "Formador"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("matched", models.BooleanField(default=False)),
                ("email", models.EmailField(blank=True, default="", max_length=200)),
                ("cargo", models.CharField(blank=True, default="", max_length=200)),
                ("gerencia", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_external_hash",
                    models.ForeignKey(
                        db_column="event_external_hash",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pessoas",
                        to="dat_ingest.stgevento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Staging Pessoa por Evento",
                "verbose_name_plural": "Staging Pessoas por Evento",
                "db_table": "stg_evento_pessoa",
                "ordering": ["event_external_hash", "role", "name"],
            },
        ),
        migrations.AddIndex(
            model_name="stgevento",
            index=models.Index(
                fields=["municipio", "data"], name="stg_evento_municip_ebf940_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stgevento",
            index=models.Index(
                fields=["status_temporal"], name="stg_evento_status__0be758_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stgevento",
            index=models.Index(
                fields=["fluxo", "aprovado_futuro"], name="stg_evento_fluxo_8a3f34_idx"
            ),
        ),
    ]
