# Django Type Stubs
# Custom type hints for Django-specific patterns in Aprender Sistema v2

from typing import Generic, TypeVar

from django.db import models

_T = TypeVar("_T", bound=models.Model)

# QuerySet with Generic support
class QuerySet(Generic[_T]):
    def filter(self, **kwargs) -> QuerySet[_T]: ...
    def exclude(self, **kwargs) -> QuerySet[_T]: ...
    def get(self, **kwargs) -> _T: ...
    def first(self) -> _T | None: ...
    def last(self) -> _T | None: ...
    def count(self) -> int: ...
    def exists(self) -> bool: ...
    def select_related(self, *fields: str) -> QuerySet[_T]: ...
    def prefetch_related(self, *lookups: str) -> QuerySet[_T]: ...
    def order_by(self, *fields: str) -> QuerySet[_T]: ...
    def distinct(self, *field_names: str) -> QuerySet[_T]: ...
    def all(self) -> QuerySet[_T]: ...
    def values(self, *fields: str) -> QuerySet[dict]: ...
    def values_list(self, *fields: str, flat: bool = False) -> QuerySet: ...

# Manager with Generic support
class Manager(Generic[_T]):
    def get_queryset(self) -> QuerySet[_T]: ...
    def filter(self, **kwargs) -> QuerySet[_T]: ...
    def exclude(self, **kwargs) -> QuerySet[_T]: ...
    def get(self, **kwargs) -> _T: ...
    def create(self, **kwargs) -> _T: ...
    def get_or_create(self, defaults=None, **kwargs) -> tuple[_T, bool]: ...
    def update_or_create(self, defaults=None, **kwargs) -> tuple[_T, bool]: ...
    def all(self) -> QuerySet[_T]: ...
    def count(self) -> int: ...
    def first(self) -> _T | None: ...
    def last(self) -> _T | None: ...
