# Generated by Django 5.1.2 on 2025-10-11 16:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tipoevento'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(help_text='Início do bloqueio (UTC)')),
                ('fim', models.DateTimeField(help_text='Fim do bloqueio (UTC)')),
                ('tipo', models.CharField(choices=[('T', 'Total'), ('P', 'Parcial')], default='T', max_length=1)),
                ('motivo', models.CharField(blank=True, help_text='Motivo do bloqueio', max_length=255)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='pendente', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='availability_blocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bloqueio de Disponibilidade',
                'verbose_name_plural': 'Bloqueios de Disponibilidade',
                'db_table': 'core_availability_block',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['usuario', 'inicio'], name='core_availa_usuario_722815_idx'), models.Index(fields=['usuario', 'fim'], name='core_availa_usuario_878adf_idx'), models.Index(fields=['status'], name='core_availa_status_0aa355_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('fim__gt', models.F('inicio'))), name='availability_block_fim_gt_inicio')],
            },
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(help_text='Início do evento (UTC)')),
                ('fim', models.DateTimeField(help_text='Fim do evento (UTC)')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='pendente', help_text='PA-01: Sempre começa pendente', max_length=10)),
                ('observacoes', models.TextField(blank=True, help_text='Observações adicionais sobre o evento')),
                ('external_event_id', models.CharField(blank=True, help_text='ID do evento no Google Calendar (para idempotência)', max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('municipio', models.ForeignKey(blank=True, help_text='Município onde ocorrerá o evento', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to='core.municipio')),
                ('tipo_evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to='core.tipoevento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação de Evento',
                'verbose_name_plural': 'Solicitações de Evento',
                'db_table': 'core_solicitacao',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['usuario', 'inicio'], name='core_solici_usuario_192c3c_idx'), models.Index(fields=['usuario', 'fim'], name='core_solici_usuario_eb5c54_idx'), models.Index(fields=['status'], name='core_solici_status_3aa1ea_idx'), models.Index(fields=['external_event_id'], name='core_solici_externa_b5c13b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('fim__gt', models.F('inicio'))), name='solicitacao_fim_gt_inicio')],
            },
        ),
    ]
