# Generated by Django 5.1.2 on 2025-10-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_availabilityblock_solicitacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='last_sync_action',
            field=models.CharField(blank=True, choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('ADOPT', 'Adopt'), ('DELETE', 'Delete'), ('SKIP', 'Skip')], help_text='Última ação de sync executada', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='last_sync_error',
            field=models.TextField(blank=True, help_text='Mensagem de erro da última tentativa de sync (se houver)', null=True),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='Última vez que sync foi executado (sucesso ou falha)', null=True),
        ),
        migrations.AddIndex(
            model_name='solicitacao',
            index=models.Index(fields=['status', 'inicio', 'fim', 'updated_at'], name='core_solici_status_a99aab_idx'),
        ),
    ]
