# Generated by Django 5.1.2 on 2025-10-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_sync_observability_fields'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='solicitacao',
            index=models.Index(fields=['updated_at', 'last_synced_at'], name='core_solici_updated_84dd12_idx'),
        ),
    ]
