# Generated by Django 5.1.2 on 2025-10-12 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_sync_timestamp_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, help_text="Chave da configuração (ex: 'availability', 'gcal_sync')", max_length=80, unique=True)),
                ('value', models.JSONField(default=dict, help_text='Valor da configuração (dict JSON)')),
                ('effective_at', models.DateTimeField(blank=True, help_text='Data de vigência (opcional, para config futura)', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração',
                'verbose_name_plural': 'Configurações',
                'db_table': 'core_config',
                'ordering': ['-effective_at', '-updated_at'],
                'indexes': [models.Index(fields=['key', 'updated_at'], name='core_config_key_fccd7c_idx')],
            },
        ),
    ]
