# Generated by Django 5.1.2 on 2025-10-12 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='key',
            field=models.CharField(db_index=True, help_text="Chave da configuração (ex: 'availability', 'gcal_sync')", max_length=80),
        ),
    ]
