# Generated by Django 5.1.2 on 2025-10-17 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_config_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='codigo',
            field=models.CharField(blank=True, db_index=True, help_text='Código único do projeto (ex: ACERTA, NLENDO)', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='fluxo',
            field=models.CharField(choices=[('SUPER', 'Superintendência'), ('OUTROS', 'Outros')], db_index=True, default='OUTROS', help_text='SUPER: requer aprovação da Superintendência. OUTROS: auto-aprovado.', max_length=12),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='projeto',
            field=models.ForeignKey(blank=True, help_text='Projeto associado ao evento (determina fluxo de aprovação)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to='core.projeto'),
        ),
    ]
