# Generated by Django 5.1.2 on 2025-10-17 21:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_projeto_codigo_projeto_fluxo_solicitacao_projeto"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        db_index=True,
                        help_text="Ação executada (ex: CELERY_GCAL_SYNC, approve, reject)",
                        max_length=50,
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        default=dict,
                        help_text="Detalhes da operação (status, applied, reason, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuário que executou a ação (se aplicável)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Auditoria",
                "verbose_name_plural": "Logs de Auditoria",
                "db_table": "core_audit_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["action", "created_at"],
                        name="core_audit__action_5c03c3_idx",
                    ),
                    models.Index(
                        fields=["usuario", "created_at"],
                        name="core_audit__usuario_2d54d6_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Compra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True,
                        help_text="Código da compra (ex: COMP-001)",
                        max_length=50,
                    ),
                ),
                (
                    "quantidade",
                    models.IntegerField(help_text="Quantidade de itens comprados"),
                ),
                ("data", models.DateField(help_text="Data da compra")),
                (
                    "uso",
                    models.TextField(
                        help_text="Uso/finalidade da compra (ex: Formação inicial)"
                    ),
                ),
                (
                    "external_hash",
                    models.CharField(
                        db_index=True,
                        help_text="Hash SHA256 para idempotência de import",
                        max_length=64,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "municipio",
                    models.ForeignKey(
                        help_text="Município destino da compra",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="compras",
                        to="core.municipio",
                    ),
                ),
                (
                    "projeto",
                    models.ForeignKey(
                        help_text="Projeto vinculado à compra",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="compras",
                        to="core.projeto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compra",
                "verbose_name_plural": "Compras",
                "db_table": "core_compra",
                "ordering": ["-data", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["codigo", "data"], name="core_compra_codigo_4b65d3_idx"
                    ),
                    models.Index(
                        fields=["projeto", "municipio"],
                        name="core_compra_projeto_64e2a0_idx",
                    ),
                    models.Index(
                        fields=["external_hash"], name="core_compra_externa_8494aa_idx"
                    ),
                ],
            },
        ),
    ]
