# Generated by Django 5.1.2 on 2025-10-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_auditlog_compra"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="model_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Nome do modelo relacionado (opcional, ex: Solicitacao, Compra)",
                max_length=60,
                null=True,
            ),
        ),
    ]
