# Generated by Django 5.1.2 on 2025-10-20 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_auditlog_model_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Participation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("COORDENADOR", "Coordenador"),
                            ("FORMADOR", "Formador"),
                            ("COORD_ACOMPANHA", "Coord. Acompanha"),
                            ("CONVIDADO", "Convidado"),
                        ],
                        max_length=20,
                        verbose_name="Papel",
                    ),
                ),
                (
                    "ch_horas",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="CH (horas)",
                    ),
                ),
                (
                    "observacao",
                    models.TextField(blank=True, null=True, verbose_name="Observação"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "solicitacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to="core.solicitacao",
                        verbose_name="Solicitação",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="event_participations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participação",
                "verbose_name_plural": "Participações",
                "db_table": "core_participation",
                "ordering": ["solicitacao_id", "role", "usuario_id"],
            },
        ),
        migrations.AddConstraint(
            model_name="participation",
            constraint=models.UniqueConstraint(
                fields=("solicitacao", "usuario", "role"),
                name="core_participation_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="participation",
            index=models.Index(
                fields=["solicitacao", "role"], name="core_partic_solicit_f8e42a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="participation",
            index=models.Index(
                fields=["usuario", "role"], name="core_partic_usuario_4c5a8d_idx"
            ),
        ),
    ]
