# Generated by Django 5.1.2 on 2025-10-20

from django.conf import settings
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_participation"),
    ]

    operations = [
        # Alterar campo usuario para permitir null/blank e usar AUTH_USER_MODEL
        migrations.AlterField(
            model_name="participation",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.deletion.PROTECT,
                related_name="event_participations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        # Adicionar guest_email
        migrations.AddField(
            model_name="participation",
            name="guest_email",
            field=models.EmailField(
                max_length=254, null=True, blank=True, verbose_name="E-mail do convidado"
            ),
        ),
        # Remover constraint antiga de unicidade
        migrations.RemoveConstraint(
            model_name="participation",
            name="core_participation_unique",
        ),
        # Novas constraints e índices
        migrations.AddConstraint(
            model_name="participation",
            constraint=models.CheckConstraint(
                name="core_participation_user_or_email",
                check=(Q(usuario__isnull=False) | Q(guest_email__isnull=False)),
            ),
        ),
        migrations.AddConstraint(
            model_name="participation",
            constraint=models.CheckConstraint(
                name="core_participation_user_required_when_not_guest",
                check=(Q(role="CONVIDADO") | (Q(role__in=["COORDENADOR", "FORMADOR", "COORD_ACOMPANHA"]) & Q(usuario__isnull=False))),
            ),
        ),
        migrations.AddConstraint(
            model_name="participation",
            constraint=models.UniqueConstraint(
                fields=("solicitacao", "usuario", "role"),
                name="core_participation_unique_user",
                condition=Q(usuario__isnull=False),
            ),
        ),
        migrations.AddConstraint(
            model_name="participation",
            constraint=models.UniqueConstraint(
                fields=("solicitacao", "guest_email", "role"),
                name="core_participation_unique_guest",
                condition=Q(guest_email__isnull=False),
            ),
        ),
        migrations.AddIndex(
            model_name="participation",
            index=models.Index(fields=["guest_email"], name="core_partic_guest_email_idx"),
        ),
    ]

