# Generated by Django 5.1.2 on 2025-10-20 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_participation_guest_email_and_constraints"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="participation",
            new_name="core_partic_solicit_953868_idx",
            old_name="core_partic_solicit_f8e42a_idx",
        ),
        migrations.RenameIndex(
            model_name="participation",
            new_name="core_partic_usuario_5accd8_idx",
            old_name="core_partic_usuario_4c5a8d_idx",
        ),
        migrations.RenameIndex(
            model_name="participation",
            new_name="core_partic_guest_e_bc9acd_idx",
            old_name="core_partic_guest_email_idx",
        ),
    ]
