# Generated by Django 5.1.2 on 2025-10-21 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_add_external_hash_to_solicitacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacao",
            name="external_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Hash SHA1 para identificar evento de fonte externa (ETL)",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
    ]
