# Generated by Django 5.1.2 on 2025-10-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_add_external_hash_field"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="compra",
            constraint=models.UniqueConstraint(
                fields=["external_hash"],
                name="core_compra_external_hash_unique",
            ),
        ),
    ]
