# Generated by Django 5.1.2 on 2025-10-21 15:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_add_compra_external_hash_unique_constraint"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deslocamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "origem",
                    models.CharField(
                        help_text="Município/local de origem", max_length=200
                    ),
                ),
                (
                    "destino",
                    models.CharField(
                        help_text="Município/local de destino", max_length=200
                    ),
                ),
                (
                    "start_date",
                    models.DateField(help_text="Data de início do deslocamento"),
                ),
                ("end_date", models.DateField(help_text="Data de fim do deslocamento")),
                (
                    "observacao",
                    models.TextField(
                        blank=True,
                        help_text="Observações sobre o deslocamento",
                        null=True,
                    ),
                ),
                (
                    "external_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Hash SHA1 para idempotência de import",
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        help_text="Usuário que realizou o deslocamento",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deslocamentos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Deslocamento",
                "verbose_name_plural": "Deslocamentos",
                "db_table": "core_deslocamento",
                "ordering": ["usuario_id", "start_date", "end_date"],
                "indexes": [
                    models.Index(
                        fields=["usuario", "start_date", "end_date"],
                        name="core_desloc_usuario_f041bf_idx",
                    ),
                    models.Index(
                        fields=["external_hash"], name="core_desloc_externa_7d7f97_idx"
                    ),
                ],
            },
        ),
    ]
