# Generated by Django 5.1.2 on 2025-10-21 19:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_create_deslocamento"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcaoControle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_entrega",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data da Entrega"
                    ),
                ),
                (
                    "data_carta",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data da Carta"
                    ),
                ),
                (
                    "contato_inicial",
                    models.DateField(
                        blank=True, null=True, verbose_name="Contato inicial"
                    ),
                ),
                (
                    "data_reuniao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Reunião Alinhamento"
                    ),
                ),
                (
                    "observacao",
                    models.TextField(blank=True, null=True, verbose_name="Observação"),
                ),
                (
                    "external_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        null=True,
                        unique=True,
                        verbose_name="External Hash",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "coordenador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acoes_controle",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Coordenador",
                    ),
                ),
                (
                    "municipio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acoes_controle",
                        to="core.municipio",
                        verbose_name="Município",
                    ),
                ),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acoes_controle",
                        to="core.projeto",
                        verbose_name="Projeto",
                    ),
                ),
            ],
            options={
                "db_table": "core_acao_controle",
                "ordering": ["-data_reuniao", "-data_entrega", "municipio_id"],
                "indexes": [
                    models.Index(
                        fields=["municipio", "projeto"],
                        name="core_acao_c_municip_c18002_idx",
                    ),
                    models.Index(
                        fields=["coordenador"], name="core_acao_c_coorden_a8036a_idx"
                    ),
                    models.Index(
                        fields=["external_hash"], name="core_acao_c_externa_1fde30_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AcaoDAT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_acao",
                    models.CharField(max_length=120, verbose_name="Tipo de ação"),
                ),
                (
                    "observacao",
                    models.TextField(blank=True, null=True, verbose_name="Observação"),
                ),
                (
                    "data_registro",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de registro"
                    ),
                ),
                (
                    "external_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        null=True,
                        unique=True,
                        verbose_name="External Hash",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "municipio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acoes_dat",
                        to="core.municipio",
                        verbose_name="Município",
                    ),
                ),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acoes_dat",
                        to="core.projeto",
                        verbose_name="Projeto",
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acoes_dat",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsável",
                    ),
                ),
            ],
            options={
                "db_table": "core_acao_dat",
                "ordering": ["-data_registro", "municipio_id"],
                "indexes": [
                    models.Index(
                        fields=["municipio", "projeto"],
                        name="core_acao_d_municip_a6f0f0_idx",
                    ),
                    models.Index(
                        fields=["tipo_acao"], name="core_acao_d_tipo_ac_7474f1_idx"
                    ),
                    models.Index(
                        fields=["external_hash"], name="core_acao_d_externa_6288b8_idx"
                    ),
                ],
            },
        ),
    ]
