# Generated by Django 5.1.2 on 2025-10-22 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_acoes_controle_dat"),
    ]

    operations = [
        migrations.AddField(
            model_name="municipio",
            name="ibge_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Código IBGE de 7 dígitos do município",
                max_length=7,
                null=True,
                unique=True,
                verbose_name="Código IBGE",
            ),
        ),
    ]
