# Generated by Django 5.1.2 on 2025-10-22 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_add_ibge_code_to_municipio"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacao",
            name="coordenador",
            field=models.ForeignKey(
                blank=True,
                help_text="Coordenador responsável pelo evento",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="eventos_coordenados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="solicitacao",
            name="coordenador_acompanha",
            field=models.BooleanField(
                default=False, help_text="Indica se o coordenador acompanha o evento"
            ),
        ),
        migrations.AddField(
            model_name="solicitacao",
            name="encontro",
            field=models.CharField(
                blank=True,
                help_text="Identificação do encontro (ex: Encontro 1)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="solicitacao",
            name="formadores",
            field=models.ManyToManyField(
                blank=True,
                help_text="Formadores que participam do evento",
                related_name="eventos_como_formador",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="solicitacao",
            name="segmento",
            field=models.CharField(
                blank=True,
                help_text="Segmento educacional (ex: Fundamental I, Fundamental II)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="solicitacao",
            name="tipo",
            field=models.CharField(
                blank=True,
                help_text="Tipo de solicitação (ex: evento, reunião)",
                max_length=50,
                null=True,
            ),
        ),
    ]
