# Generated by Django 5.1.2 on 2025-10-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_add_solicitacao_pr8_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacao",
            name="gcal_last_error",
            field=models.TextField(
                blank=True,
                help_text="Mensagem de erro da última tentativa de publicação",
                null=True,
                verbose_name="Último erro GCal",
            ),
        ),
        migrations.AddField(
            model_name="solicitacao",
            name="gcal_last_sync_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp da última tentativa de sincronização com GCal",
                null=True,
                verbose_name="Último sync GCal",
            ),
        ),
        migrations.AddField(
            model_name="solicitacao",
            name="gcal_payload_hash",
            field=models.CharField(
                blank=True,
                help_text="SHA1 do payload aplicado no GCal (drift detection)",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="solicitacao",
            name="gcal_status",
            field=models.CharField(
                choices=[
                    ("NONE", "Não publicado"),
                    ("PENDING", "Aguardando publicação"),
                    ("PUBLISHED", "Publicado"),
                    ("ERROR", "Erro na publicação"),
                ],
                db_index=True,
                default="NONE",
                help_text="Status de sincronização com Google Calendar",
                max_length=16,
                verbose_name="Status GCal",
            ),
        ),
        migrations.AddIndex(
            model_name="solicitacao",
            index=models.Index(
                fields=["gcal_status", "status"], name="core_solici_gcal_st_bf940e_idx"
            ),
        ),
    ]
