# Generated by Django 5.1.2 on 2025-10-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_backfill_is_online"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solicitacao",
            name="is_online",
            field=models.BooleanField(
                default=False,
                help_text="Evento online? Gera link do Google Meet no APPLY.",
                verbose_name="Evento online",
            ),
        ),
    ]
