# Generated by Django 5.1.2 on 2025-10-30 16:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_alter_solicitacao_is_online"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="cpf",
            field=models.CharField(
                db_index=True,
                max_length=11,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_cpf",
                        message="CPF deve conter exatamente 11 dígitos numéricos.",
                        regex="^\\d{11}$",
                    )
                ],
            ),
        ),
    ]
