# Generated by Django 5.1.2 on 2025-11-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_add_google_oauth_credential"),
    ]

    operations = [
        # Step 1: Remove unique constraint from Projeto.codigo
        migrations.AlterField(
            model_name='projeto',
            name='codigo',
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text='Código único do projeto (ex: ACERTA, NLENDO). Unique apenas quando preenchido.',
                max_length=50,
                null=True
            ),
        ),
        # Auto-generated: Index renames for GoogleOAuthCredential
        migrations.RenameIndex(
            model_name="googleoauthcredential",
            new_name="core_google_user_id_ad5a2b_idx",
            old_name="core_google_user_id_4f8f1e_idx",
        ),
        migrations.RenameIndex(
            model_name="googleoauthcredential",
            new_name="core_google_google__583f52_idx",
            old_name="core_google_google__62ff5d_idx",
        ),
        migrations.RenameIndex(
            model_name="googleoauthcredential",
            new_name="core_google_token_e_0c307d_idx",
            old_name="core_google_token_e_3b0c3e_idx",
        ),
    ]
