# Generated by Django 5.1.2 on 2025-11-06 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_remove_codigo_unique"),
    ]

    operations = [
        # Convert NULL codigo values to empty string
        migrations.RunSQL(
            sql="UPDATE core_projeto SET codigo = '' WHERE codigo IS NULL;",
            reverse_sql="UPDATE core_projeto SET codigo = NULL WHERE codigo = '';",
        ),
    ]
