# Generated by Django 5.1.2 on 2025-11-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_normalize_codigo_null"),
    ]

    operations = [
        # Step 1: Make codigo non-nullable with empty string default
        migrations.AlterField(
            model_name='projeto',
            name='codigo',
            field=models.CharField(
                blank=True,
                db_index=True,
                default='',
                help_text='Código único do projeto (ex: ACERTA, NLENDO). Unique apenas quando preenchido.',
                max_length=50,
                null=False
            ),
        ),
        # Step 2: Add partial unique constraint (only when codigo is not empty)
        migrations.AddConstraint(
            model_name='projeto',
            constraint=models.UniqueConstraint(
                condition=~models.Q(codigo=''),
                fields=('codigo',),
                name='unique_projeto_codigo_nonempty',
            ),
        ),
    ]
