# Generated by Django 5.1.2 on 2025-11-06 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_make_codigo_nonnull_with_partial_unique"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="participation",
            name="core_participation_user_required_when_not_guest",
        ),
    ]
