# Generated by Django 5.1.2 on 2025-11-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_remove_participation_constraint"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="availabilityblock",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["pendente", "aprovado", "reprovado"])
                ),
                name="availability_block_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="availabilityblock",
            constraint=models.CheckConstraint(
                condition=models.Q(("tipo__in", ["T", "P"])),
                name="availability_block_tipo_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="projeto",
            constraint=models.CheckConstraint(
                condition=models.Q(("fluxo__in", ["SUPER", "NAO_SUPER"])),
                name="projeto_fluxo_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="solicitacao",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["pendente", "aprovado", "reprovado"])
                ),
                name="solicitacao_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="solicitacao",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("gcal_status__in", ["NONE", "PENDING", "PUBLISHED", "ERROR"])
                ),
                name="solicitacao_gcal_status_valid",
            ),
        ),
    ]
