# Generated by Django 5.1.2 on 2025-11-15 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_add_choice_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="projeto",
            name="is_test",
            field=models.BooleanField(
                default=False,
                help_text="Marca projeto como teste (não exibir em produção)",
            ),
        ),
        migrations.CreateModel(
            name="Gerencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        db_index=True,
                        help_text="Nome da gerência (ex: GERENCIA 2, SUPERINTENDENCIA)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "nome_setor",
                    models.CharField(
                        help_text="Nome comercial/operacional do setor (ex: Vidas, ACerta, Fluir)",
                        max_length=100,
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("descricao", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gerente",
                    models.ForeignKey(
                        blank=True,
                        help_text="Gerente responsável pela gerência",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gerencias_gerenciadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Gerência",
                "verbose_name_plural": "Gerências",
                "db_table": "core_gerencia",
                "ordering": ["nome"],
            },
        ),
        migrations.AddField(
            model_name="projeto",
            name="gerencia",
            field=models.ForeignKey(
                blank=True,
                help_text="Gerência à qual o projeto pertence (ex: GERENCIA 2 - Vidas)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="projetos",
                to="core.gerencia",
            ),
        ),
    ]
