# Generated by Django 5.1.2 on 2025-11-15 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_add_choice_constraints"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compra",
            name="codigo",
            field=models.CharField(
                db_index=True,
                help_text="Código da compra (ex: COMP-001) - DEPRECATED: Use produto FK",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        db_index=True,
                        help_text="Código único (ex: NL-C1, GE-KB)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome completo do produto", max_length=200
                    ),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, help_text="Descrição detalhada"),
                ),
                (
                    "ativo",
                    models.BooleanField(default=True, help_text="Produto disponível"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "projeto",
                    models.ForeignKey(
                        help_text="Projeto vinculado",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="produtos",
                        to="core.projeto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
                "db_table": "core_produto",
                "ordering": ["codigo"],
            },
        ),
        migrations.AddField(
            model_name="compra",
            name="produto",
            field=models.ForeignKey(
                blank=True,
                help_text="Produto comprado (substitui codigo string)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="compras",
                to="core.produto",
            ),
        ),
        migrations.AddIndex(
            model_name="produto",
            index=models.Index(
                fields=["codigo", "ativo"], name="core_produt_codigo_70381d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="produto",
            index=models.Index(
                fields=["projeto"], name="core_produt_projeto_6db4af_idx"
            ),
        ),
    ]
