# Generated by Django 5.1.2 on 2025-11-15 01:04

from django.db import migrations


def populate_compra_produto(apps, schema_editor):
    """
    Populate Compra.produto FK based on Compra.codigo.

    Strategy:
    1. For each Compra without produto_id:
        a. Try match: Produto.codigo == Compra.codigo
        b. If no match and Compra.projeto exists, create orphan Produto
        c. Update Compra.produto_id
    """
    Compra = apps.get_model("core", "Compra")
    Produto = apps.get_model("core", "Produto")
    Projeto = apps.get_model("core", "Projeto")

    compras_sem_produto = Compra.objects.filter(produto__isnull=True)
    total = compras_sem_produto.count()

    if total == 0:
        print("  ✓ No compras to populate (produto already set)")
        return

    print(f"  Populating {total} compras with produto FK...")

    matched = 0
    created_orphans = 0
    errors = 0

    for compra in compras_sem_produto.iterator():
        try:
            # Try to match by codigo
            produto = Produto.objects.filter(codigo=compra.codigo).first()

            if not produto:
                # Create orphan produto
                projeto = compra.projeto if compra.projeto else None
                if not projeto:
                    # Fallback: try to get any active project
                    projeto = Projeto.objects.filter(ativo=True).first()

                if projeto:
                    produto = Produto.objects.create(
                        codigo=compra.codigo,
                        nome=f"Produto {compra.codigo} (orphan)",
                        projeto=projeto,
                        ativo=False,  # Marked as inactive (needs review)
                    )
                    created_orphans += 1
                else:
                    print(f"    ❌ Cannot create produto for compra {compra.id}: no projeto available")
                    errors += 1
                    continue

            # Update compra.produto
            compra.produto = produto
            compra.save(update_fields=["produto"])
            matched += 1

        except Exception as e:
            print(f"    ❌ Error processing compra {compra.id}: {e}")
            errors += 1

    print(
        f"  ✓ Populated: {matched} matched, {created_orphans} orphans created, "
        f"{errors} errors"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_add_produto_model"),
    ]

    operations = [
        migrations.RunPython(populate_compra_produto, reverse_code=migrations.RunPython.noop),
    ]
