# Generated by Django 5.1.2 on 2025-11-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_mark_test_projects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="availabilityblock",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("aprovado", "Aprovado"),
                    ("reprovado", "Reprovado"),
                ],
                default="aprovado",
                max_length=10,
            ),
        ),
    ]
