# Generated by Django 5.1.2 on 2025-11-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_auto_approve_availability_blocks"),
    ]

    operations = [
        migrations.AddField(
            model_name="municipio",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Latitude em graus decimais (-90 a 90)",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="municipio",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Longitude em graus decimais (-180 a 180)",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="municipio",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("latitude__gte", -90), ("latitude__lte", 90)),
                    ("latitude__isnull", True),
                    _connector="OR",
                ),
                name="latitude_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="municipio",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("longitude__gte", -180), ("longitude__lte", 180)),
                    ("longitude__isnull", True),
                    _connector="OR",
                ),
                name="longitude_range",
            ),
        ),
    ]
