# Generated by Django 5.1.2 on 2025-12-02 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_add_municipio_coordinates"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipeGerencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "papel",
                    models.CharField(
                        choices=[
                            ("GERENTE", "Gerente"),
                            ("COORDENADOR", "Coordenador"),
                            ("APOIO", "Apoio de Coordenação"),
                            ("FORMADOR", "Formador"),
                        ],
                        help_text="Papel do usuário nesta gerência",
                        max_length=15,
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(
                        default=True, help_text="Se esta atribuição está ativa"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "coordenador_supervisor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Coordenador que este apoio auxilia (apenas para papel APOIO)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="apoios_supervisionados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "gerencia",
                    models.ForeignKey(
                        help_text="Gerência/setor ao qual o usuário pertence",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipes",
                        to="core.gerencia",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        help_text="Usuário membro da equipe",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipe de Gerência",
                "verbose_name_plural": "Equipes de Gerências",
                "db_table": "core_equipe_gerencia",
                "ordering": ["gerencia", "papel", "usuario"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("papel", "APOIO"), _negated=True),
                            ("coordenador_supervisor__isnull", False),
                            _connector="OR",
                        ),
                        name="apoio_requires_supervisor",
                        violation_error_message="Apoio de Coordenação deve ter um coordenador supervisor",
                    )
                ],
                "unique_together": {("gerencia", "usuario", "papel")},
            },
        ),
    ]
