# Generated by Django 5.1 on 2025-12-05
# Migration: Criar estrutura de grupos SETOR + FUNÇÃO para RBAC

from django.db import migrations


def create_rbac_groups(apps, schema_editor):
    """
    Cria os grupos de SETOR e FUNÇÃO para o novo sistema RBAC.

    Estrutura:
    - SETORES: Onde o usuário trabalha (Superintendência, DAT, Controle, Gerência)
    - FUNÇÕES: O que o usuário pode fazer (Formador, Coordenador, Apoio, Gerente)

    Grupos existentes mantidos:
    - Superintendência, DAT, Controle, Gerência (setores)
    - Formador, Coordenador, Apoio de Coordenação (funções)

    Novos grupos criados:
    - Gerente (função) - pode aprovar/reprovar, ver dashboards
    - Apoio (função) - alias simplificado para Apoio de Coordenação
    """
    Group = apps.get_model('auth', 'Group')

    # Grupos de FUNÇÃO que precisam ser criados
    funcao_groups = [
        'Gerente',  # Nova função: pode aprovar/reprovar
    ]

    for group_name in funcao_groups:
        Group.objects.get_or_create(name=group_name)
        print(f'  ✓ Grupo criado/verificado: {group_name}')


def reverse_migration(apps, schema_editor):
    """
    Reverte a migration removendo os grupos criados.
    CUIDADO: Não remove grupos que já existiam antes.
    """
    Group = apps.get_model('auth', 'Group')

    # Apenas remove grupos que foram criados por esta migration
    groups_to_remove = ['Gerente']

    for group_name in groups_to_remove:
        Group.objects.filter(name=group_name).delete()
        print(f'  ✗ Grupo removido: {group_name}')


class Migration(migrations.Migration):
    """
    Migration para criar estrutura de grupos RBAC (Setor + Função).

    Após esta migration, o sistema terá:

    GRUPOS DE SETOR (onde o usuário trabalha):
    - Superintendência
    - DAT
    - Controle
    - Gerência (setor genérico)

    GRUPOS DE FUNÇÃO (o que o usuário pode fazer):
    - Formador: visualiza grade, gerencia bloqueios pessoais
    - Coordenador: cria solicitações de eventos
    - Apoio de Coordenação: auxilia coordenação
    - Gerente: aprova/reprova, acessa dashboards e relatórios

    Exemplo de uso:
    - Maria (Superintendência + Gerente) → pode aprovar solicitações SUPER
    - João (DAT + Gerente) → pode aprovar solicitações DAT
    - Pedro (Superintendência + Formador) → NÃO pode aprovar
    """

    dependencies = [
        ('core', '0041_add_equipe_gerencia'),
    ]

    operations = [
        migrations.RunPython(create_rbac_groups, reverse_migration),
    ]
