# Generated by Django 5.1 on 2025-12-05
# Migration: Adicionar todos os grupos de SETOR (Gerências)

from django.db import migrations


def create_setor_groups(apps, schema_editor):
    """
    Cria todos os grupos de SETOR baseado nas gerências do documento
    MAPEAMENTO_COMPLETO_SETORES_GERENCIAS.md.

    Setores/Gerências:
    - Superintendência (já existe) - Fluxo SUPER
    - Vidas (GERENCIA 2) - Fluxo NAO_SUPER
    - Fluir (GERENCIA 3) - Fluxo NAO_SUPER
    - ACerta (GERENCIA 4) - Fluxo NAO_SUPER
    - Brincando (GERENCIA 5) - Fluxo NAO_SUPER
    - Sou da Paz (GERENCIA 6) - Fluxo NAO_SUPER
    - DAT (já existe) - Administrativo
    - Controle (já existe) - Operacional
    - Gerência (já existe) - Genérico
    """
    Group = apps.get_model('auth', 'Group')

    # Novos grupos de SETOR (Gerências) a criar
    new_setor_groups = [
        'Vidas',      # GERENCIA 2
        'Fluir',      # GERENCIA 3
        'ACerta',     # GERENCIA 4
        'Brincando',  # GERENCIA 5
        'Sou da Paz', # GERENCIA 6
    ]

    for group_name in new_setor_groups:
        obj, created = Group.objects.get_or_create(name=group_name)
        if created:
            print(f'  ✓ Grupo criado: {group_name}')
        else:
            print(f'  - Grupo já existe: {group_name}')


def reverse_migration(apps, schema_editor):
    """Remove os grupos criados por esta migration."""
    Group = apps.get_model('auth', 'Group')

    groups_to_remove = ['Vidas', 'Fluir', 'ACerta', 'Brincando', 'Sou da Paz']

    for group_name in groups_to_remove:
        Group.objects.filter(name=group_name).delete()
        print(f'  ✗ Grupo removido: {group_name}')


class Migration(migrations.Migration):
    """
    Migration para adicionar grupos de SETOR para todas as gerências.

    Após esta migration, teremos os seguintes grupos de SETOR:

    | Grupo | Gerência | Fluxo |
    |-------|----------|-------|
    | Superintendência | SUPERINTENDENCIA | SUPER |
    | Vidas | GERENCIA 2 | NAO_SUPER |
    | Fluir | GERENCIA 3 | NAO_SUPER |
    | ACerta | GERENCIA 4 | NAO_SUPER |
    | Brincando | GERENCIA 5 | NAO_SUPER |
    | Sou da Paz | GERENCIA 6 | NAO_SUPER |
    | DAT | - | Administrativo |
    | Controle | - | Operacional |
    | Gerência | - | Genérico |

    Combinado com grupos de FUNÇÃO (Formador, Coordenador, Apoio, Gerente),
    permite RBAC completo para todos os setores.
    """

    dependencies = [
        ('core', '0042_rbac_setor_funcao_groups'),
    ]

    operations = [
        migrations.RunPython(create_setor_groups, reverse_migration),
    ]
