# Generated by Django 5.1.2 on 2025-12-15 13:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_add_all_setor_groups"),
    ]

    operations = [
        migrations.CreateModel(
            name="DATRegistro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aluno_qtde",
                    models.PositiveIntegerField(
                        help_text="Total de alunos na turma",
                        verbose_name="Quantidade de Alunos",
                    ),
                ),
                (
                    "professor_qtde",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Total de professores (necessário para cálculo de códigos)",
                        null=True,
                        verbose_name="Quantidade de Professores",
                    ),
                ),
                (
                    "reuniao_dat",
                    models.DateField(
                        blank=True,
                        help_text="Data da reunião de alinhamento DAT",
                        null=True,
                        verbose_name="Data Reunião DAT",
                    ),
                ),
                (
                    "turma_formar_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="ID do curso na plataforma FORMAR",
                        null=True,
                        verbose_name="ID Turma FORMAR",
                    ),
                ),
                (
                    "turma_formar_status",
                    models.CharField(
                        choices=[
                            ("criada", "Criada"),
                            ("pendente", "Pendente"),
                            ("erro", "Erro"),
                        ],
                        default="pendente",
                        max_length=10,
                        verbose_name="Status Turma FORMAR",
                    ),
                ),
                (
                    "nr_codigos",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Calculado automaticamente baseado em projeto_geral",
                        null=True,
                        verbose_name="Nº de Códigos",
                    ),
                ),
                (
                    "chaves_inscricao_status",
                    models.CharField(
                        choices=[
                            ("concluido", "Concluído"),
                            ("pendente", "Pendente"),
                            ("em_andamento", "Em Andamento"),
                            ("nao_aplicavel", "Não Aplicável"),
                            ("erro", "Erro"),
                        ],
                        default="pendente",
                        max_length=15,
                        verbose_name="Chaves de Inscrição",
                    ),
                ),
                (
                    "chaves_inscricao_data",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Chaves Inscrição"
                    ),
                ),
                (
                    "instrucoes_status",
                    models.CharField(
                        choices=[
                            ("concluido", "Concluído"),
                            ("pendente", "Pendente"),
                            ("em_andamento", "Em Andamento"),
                            ("nao_aplicavel", "Não Aplicável"),
                            ("erro", "Erro"),
                        ],
                        default="pendente",
                        max_length=15,
                        verbose_name="Instruções",
                    ),
                ),
                (
                    "instrucoes_data",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Instruções"
                    ),
                ),
                (
                    "envio_codigos_status",
                    models.CharField(
                        choices=[
                            ("concluido", "Concluído"),
                            ("pendente", "Pendente"),
                            ("em_andamento", "Em Andamento"),
                            ("nao_aplicavel", "Não Aplicável"),
                            ("erro", "Erro"),
                        ],
                        default="pendente",
                        max_length=15,
                        verbose_name="Envio de Códigos",
                    ),
                ),
                (
                    "envio_codigos_data",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Envio Códigos"
                    ),
                ),
                (
                    "obs_formar",
                    models.TextField(
                        blank=True, max_length=1000, verbose_name="Observações FORMAR"
                    ),
                ),
                (
                    "usa_avaliar",
                    models.BooleanField(
                        default=False,
                        help_text="Preenchido automaticamente baseado no Projeto Geral",
                        verbose_name="Usa AVALIAR",
                    ),
                ),
                (
                    "alunos_recebidos_status",
                    models.CharField(
                        choices=[
                            ("concluido", "Concluído"),
                            ("pendente", "Pendente"),
                            ("em_andamento", "Em Andamento"),
                            ("nao_aplicavel", "Não Aplicável"),
                            ("erro", "Erro"),
                        ],
                        default="nao_aplicavel",
                        max_length=15,
                        verbose_name="Alunos Recebidos",
                    ),
                ),
                (
                    "alunos_recebidos_datas",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Array de datas: ['2025-03-12', '2025-04-25']",
                        verbose_name="Datas Recebimento",
                    ),
                ),
                (
                    "alunos_validados_status",
                    models.CharField(
                        choices=[
                            ("concluido", "Concluído"),
                            ("pendente", "Pendente"),
                            ("em_andamento", "Em Andamento"),
                            ("nao_aplicavel", "Não Aplicável"),
                            ("erro", "Erro"),
                        ],
                        default="nao_aplicavel",
                        max_length=15,
                        verbose_name="Alunos Validados",
                    ),
                ),
                (
                    "alunos_validados_datas",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Datas Validação"
                    ),
                ),
                (
                    "alunos_importados_status",
                    models.CharField(
                        choices=[
                            ("concluido", "Concluído"),
                            ("pendente", "Pendente"),
                            ("em_andamento", "Em Andamento"),
                            ("nao_aplicavel", "Não Aplicável"),
                            ("erro", "Erro"),
                        ],
                        default="nao_aplicavel",
                        max_length=15,
                        verbose_name="Alunos Importados",
                    ),
                ),
                (
                    "alunos_importados_datas",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Datas Importação"
                    ),
                ),
                (
                    "obs_avaliar",
                    models.TextField(
                        blank=True, max_length=1000, verbose_name="Observações AVALIAR"
                    ),
                ),
                (
                    "external_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Para idempotência de importação ETL",
                        max_length=64,
                        null=True,
                        unique=True,
                        verbose_name="Hash Externo",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Registro DAT",
                "verbose_name_plural": "Registros DAT",
                "db_table": "core_dat_registro",
                "ordering": ["-created_at", "municipio__nome"],
            },
        ),
        migrations.CreateModel(
            name="ProjetoGeral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        db_index=True,
                        help_text="Ex: ACERTA MATEMÁTICA, VIDA E LINGUAGEM",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "usa_avaliar",
                    models.BooleanField(
                        default=False,
                        help_text="Se o projeto utiliza a plataforma AVALIAR",
                    ),
                ),
                (
                    "tipo_calculo_codigos",
                    models.CharField(
                        choices=[
                            ("por_aluno", "Por Aluno (qtde_alunos / divisor)"),
                            (
                                "por_professor",
                                "Por Professor (qtde_professores * multiplicador)",
                            ),
                            ("nao_aplicavel", "Não Aplicável (não gera códigos)"),
                        ],
                        default="por_professor",
                        help_text="Como calcular número de códigos FORMAR",
                        max_length=15,
                    ),
                ),
                (
                    "divisor_aluno",
                    models.PositiveIntegerField(
                        default=20,
                        help_text="Divisor quando tipo = por_aluno (ex: 200 alunos / 20 = 10 códigos)",
                    ),
                ),
                (
                    "multiplicador_professor",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.1,
                        help_text="Multiplicador quando tipo = por_professor (ex: 10 professores * 1.1 = 11 códigos)",
                        max_digits=3,
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                (
                    "descricao",
                    models.TextField(
                        blank=True, help_text="Descrição adicional do projeto geral"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Projeto Geral",
                "verbose_name_plural": "Projetos Gerais",
                "db_table": "core_projeto_geral",
                "ordering": ["nome"],
            },
        ),
        migrations.AlterModelOptions(
            name="config",
            options={
                "ordering": ["-effective_at", "-updated_at"],
                "verbose_name": "Configuracao",
                "verbose_name_plural": "Configuracoes",
            },
        ),
        migrations.AlterModelOptions(
            name="equipegerencia",
            options={
                "ordering": ["gerencia", "papel", "usuario"],
                "verbose_name": "Equipe de Gerencia",
                "verbose_name_plural": "Equipes de Gerencias",
            },
        ),
        migrations.AlterModelOptions(
            name="gerencia",
            options={
                "ordering": ["nome"],
                "verbose_name": "Gerencia",
                "verbose_name_plural": "Gerencias",
            },
        ),
        migrations.AlterModelOptions(
            name="municipio",
            options={
                "ordering": ["nome"],
                "verbose_name": "Municipio",
                "verbose_name_plural": "Municipios",
            },
        ),
        migrations.AlterModelOptions(
            name="participation",
            options={
                "ordering": ["solicitacao_id", "role", "usuario_id"],
                "verbose_name": "Participacao",
                "verbose_name_plural": "Participacoes",
            },
        ),
        migrations.AlterModelOptions(
            name="solicitacao",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Solicitacao de Evento",
                "verbose_name_plural": "Solicitacoes de Evento",
            },
        ),
        migrations.AlterModelOptions(
            name="usuario",
            options={"verbose_name": "Usuario", "verbose_name_plural": "Usuarios"},
        ),
        migrations.RemoveConstraint(
            model_name="equipegerencia",
            name="apoio_requires_supervisor",
        ),
        migrations.AlterField(
            model_name="acaocontrole",
            name="data_reuniao",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data Reuniao Alinhamento"
            ),
        ),
        migrations.AlterField(
            model_name="acaocontrole",
            name="municipio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="acoes_controle",
                to="core.municipio",
                verbose_name="Municipio",
            ),
        ),
        migrations.AlterField(
            model_name="acaocontrole",
            name="observacao",
            field=models.TextField(blank=True, null=True, verbose_name="Observacao"),
        ),
        migrations.AlterField(
            model_name="acaodat",
            name="municipio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="acoes_dat",
                to="core.municipio",
                verbose_name="Municipio",
            ),
        ),
        migrations.AlterField(
            model_name="acaodat",
            name="observacao",
            field=models.TextField(blank=True, null=True, verbose_name="Observacao"),
        ),
        migrations.AlterField(
            model_name="acaodat",
            name="responsavel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acoes_dat",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsavel",
            ),
        ),
        migrations.AlterField(
            model_name="acaodat",
            name="tipo_acao",
            field=models.CharField(max_length=120, verbose_name="Tipo de acao"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                db_index=True,
                help_text="Acao executada (ex: CELERY_GCAL_SYNC, approve, reject)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="details",
            field=models.JSONField(
                default=dict,
                help_text="Detalhes da operacao (status, applied, reason, etc.)",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que executou a acao (se aplicavel)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="availabilityblock",
            name="inicio",
            field=models.DateTimeField(help_text="Inicio do bloqueio (UTC)"),
        ),
        migrations.AlterField(
            model_name="compra",
            name="codigo",
            field=models.CharField(
                db_index=True,
                help_text="Codigo da compra (ex: COMP-001) - DEPRECATED: Use produto FK",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="compra",
            name="external_hash",
            field=models.CharField(
                db_index=True,
                help_text="Hash SHA256 para idempotencia de import",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="compra",
            name="municipio",
            field=models.ForeignKey(
                help_text="Municipio destino da compra",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="compras",
                to="core.municipio",
            ),
        ),
        migrations.AlterField(
            model_name="compra",
            name="projeto",
            field=models.ForeignKey(
                help_text="Projeto vinculado a compra",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="compras",
                to="core.projeto",
            ),
        ),
        migrations.AlterField(
            model_name="compra",
            name="uso",
            field=models.TextField(
                help_text="Uso/finalidade da compra (ex: Formacao inicial)"
            ),
        ),
        migrations.AlterField(
            model_name="config",
            name="effective_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Data de vigencia (opcional, para config futura)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="config",
            name="key",
            field=models.CharField(
                db_index=True,
                help_text="Chave da configuracao (ex: 'availability', 'gcal_sync')",
                max_length=80,
            ),
        ),
        migrations.AlterField(
            model_name="config",
            name="value",
            field=models.JSONField(
                default=dict, help_text="Valor da configuracao (dict JSON)"
            ),
        ),
        migrations.AlterField(
            model_name="deslocamento",
            name="destino",
            field=models.CharField(
                help_text="Municipio/local de destino", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="deslocamento",
            name="external_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Hash SHA1 para idempotencia de import",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="deslocamento",
            name="observacao",
            field=models.TextField(
                blank=True, help_text="Observacoes sobre o deslocamento", null=True
            ),
        ),
        migrations.AlterField(
            model_name="deslocamento",
            name="origem",
            field=models.CharField(
                help_text="Municipio/local de origem", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="deslocamento",
            name="start_date",
            field=models.DateField(help_text="Data de inicio do deslocamento"),
        ),
        migrations.AlterField(
            model_name="deslocamento",
            name="usuario",
            field=models.ForeignKey(
                help_text="Usuario que realizou o deslocamento",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deslocamentos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="equipegerencia",
            name="ativo",
            field=models.BooleanField(
                default=True, help_text="Se esta atribuicao esta ativa"
            ),
        ),
        migrations.AlterField(
            model_name="equipegerencia",
            name="gerencia",
            field=models.ForeignKey(
                help_text="Gerencia/setor ao qual o usuario pertence",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equipes",
                to="core.gerencia",
            ),
        ),
        migrations.AlterField(
            model_name="equipegerencia",
            name="papel",
            field=models.CharField(
                choices=[
                    ("GERENTE", "Gerente"),
                    ("COORDENADOR", "Coordenador"),
                    ("APOIO", "Apoio de Coordenacao"),
                    ("FORMADOR", "Formador"),
                ],
                help_text="Papel do usuario nesta gerencia",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="equipegerencia",
            name="usuario",
            field=models.ForeignKey(
                help_text="Usuario membro da equipe",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="equipes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="gerencia",
            name="gerente",
            field=models.ForeignKey(
                blank=True,
                help_text="Gerente responsavel pela gerencia",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gerencias_gerenciadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="gerencia",
            name="nome",
            field=models.CharField(
                db_index=True,
                help_text="Nome da gerencia (ex: GERENCIA 2, SUPERINTENDENCIA)",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="googleoauthcredential",
            name="allowed_calendars",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lista de IDs de calendarios que o usuario pode publicar (GAP-5: multi-calendar futuro)",
                verbose_name="Calendarios Permitidos",
            ),
        ),
        migrations.AlterField(
            model_name="googleoauthcredential",
            name="default_calendar_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="ID do calendario padrao (ex: 'primary' ou ID especifico)",
                max_length=255,
                verbose_name="Calendario Padrao",
            ),
        ),
        migrations.AlterField(
            model_name="googleoauthcredential",
            name="scope",
            field=models.CharField(
                default="https://www.googleapis.com/auth/calendar",
                help_text="Permissoes concedidas pelo usuario (separadas por espaco)",
                max_length=500,
                verbose_name="Scopes OAuth",
            ),
        ),
        migrations.AlterField(
            model_name="googleoauthcredential",
            name="token_expiry",
            field=models.DateTimeField(
                help_text="Timestamp UTC de expiracao do access token (geralmente 1h)",
                verbose_name="Expiracao do Token",
            ),
        ),
        migrations.AlterField(
            model_name="googleoauthcredential",
            name="user",
            field=models.OneToOneField(
                help_text="Usuario Controle que conectou sua conta Google",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="google_oauth",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.AlterField(
            model_name="municipio",
            name="ibge_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Codigo IBGE de 7 digitos do municipio",
                max_length=7,
                null=True,
                unique=True,
                verbose_name="Codigo IBGE",
            ),
        ),
        migrations.AlterField(
            model_name="participation",
            name="observacao",
            field=models.TextField(blank=True, null=True, verbose_name="Observacao"),
        ),
        migrations.AlterField(
            model_name="participation",
            name="solicitacao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participations",
                to="core.solicitacao",
                verbose_name="Solicitacao",
            ),
        ),
        migrations.AlterField(
            model_name="participation",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="event_participations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="ativo",
            field=models.BooleanField(default=True, help_text="Produto disponivel"),
        ),
        migrations.AlterField(
            model_name="produto",
            name="codigo",
            field=models.CharField(
                db_index=True,
                help_text="Codigo unico (ex: NL-C1, GE-KB)",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="descricao",
            field=models.TextField(blank=True, help_text="Descricao detalhada"),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="codigo",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Codigo unico do projeto (ex: ACERTA, NLENDO). Unique apenas quando preenchido.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="fluxo",
            field=models.CharField(
                choices=[
                    ("SUPER", "Superintendencia"),
                    ("NAO_SUPER", "Nao-Superintendencia"),
                ],
                db_index=True,
                default="NAO_SUPER",
                help_text="SUPER: requer aprovacao da Superintendencia. NAO_SUPER: auto-aprovado.",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="gerencia",
            field=models.ForeignKey(
                blank=True,
                help_text="Gerencia a qual o projeto pertence (ex: GERENCIA 2 - Vidas)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="projetos",
                to="core.gerencia",
            ),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="is_test",
            field=models.BooleanField(
                default=False,
                help_text="Marca projeto como teste (nao exibir em producao)",
            ),
        ),
        migrations.AlterField(
            model_name="solicitacao",
            name="coordenador",
            field=models.ForeignKey(
                blank=True,
                help_text="Coordenador responsavel pelo evento",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="eventos_coordenados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="solicitacao",
            name="encontro",
            field=models.CharField(
                blank=True,
                help_text="Identificacao do encontro (ex: Encontro 1)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="solicitacao",
            name="external_event_id",
            field=models.CharField(
                blank=True,
                help_text="ID do evento no Google Calendar (para idempotencia)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="solicitacao",
            name="gcal_last_error",
            field=models.TextField(
                blank=True,
                help_text="Mensagem de erro da ultima tentativa de publicacao",
                null=True,
                verbose_name="Ultimo erro GCal",
            ),
        ),
        migrations.AlterField(
            model_name="solicitacao",
            name="gcal_last_sync_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp da ultima tentativa de sincronizacao com GCal",
                null=True,
                verbose_name="Ultimo sync GCal",
            ),
        ),
        migrations.AlterField(
            model_name="solicitacao",
            name="gcal_status",
            field=models.CharField(
                choices=[
                    ("NONE", "Nao publicado"),
                    ("PENDING", "Aguardando publicacao"),
                    ("PUBLISHED", "Publicado"),
                    ("ERROR", "Erro na publicacao"),
                ],
                db_index=True,
                default="NONE",
                help_text="Status de sincronizacao com Google Calendar",
                max_length=16,
                verbose_name="Status GCal",
            ),
        ),
        migrations.AlterField(
            model_name="solicitacao",
            name="inicio",
            field=models.DateTimeField(help_text="Inicio do evento (UTC)"),
        ),
        migrations.AlterField(
            model_name="solicitacao",
            name="last_sync_action",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CREATE", "Create"),
                    ("UPDATE", "Update"),
                    ("ADOPT", "Adopt"),
                    ("DELETE", "Delete"),
                    ("SKIP", "Skip"),
                ],
                help_text="Ultima acao de sync executada",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="solicitacao",
            name="last_sync_error",
            field=models.TextField(
                blank=True,
                help_text="Mensagem de erro da ultima tentativa de sync (se houver)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="solicitacao",
            name="last_synced_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Ultima vez que sync foi executado (sucesso ou falha)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="solicitacao",
            name="municipio",
            field=models.ForeignKey(
                blank=True,
                help_text="Municipio onde ocorrera o evento",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="solicitacoes",
                to="core.municipio",
            ),
        ),
        migrations.AlterField(
            model_name="solicitacao",
            name="observacoes",
            field=models.TextField(
                blank=True, help_text="Observacoes adicionais sobre o evento"
            ),
        ),
        migrations.AlterField(
            model_name="solicitacao",
            name="projeto",
            field=models.ForeignKey(
                blank=True,
                help_text="Projeto associado ao evento (determina fluxo de aprovacao)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="solicitacoes",
                to="core.projeto",
            ),
        ),
        migrations.AlterField(
            model_name="solicitacao",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("aprovado", "Aprovado"),
                    ("reprovado", "Reprovado"),
                ],
                default="pendente",
                help_text="PA-01: Sempre comeca pendente",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="solicitacao",
            name="tipo",
            field=models.CharField(
                blank=True,
                help_text="Tipo de solicitacao (ex: evento, reuniao)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="equipegerencia",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("papel", "APOIO"), _negated=True),
                    ("coordenador_supervisor__isnull", False),
                    _connector="OR",
                ),
                name="apoio_requires_supervisor",
                violation_error_message="Apoio de Coordenacao deve ter um coordenador supervisor",
            ),
        ),
        migrations.AddField(
            model_name="datregistro",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dat_registros_criados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criado por",
            ),
        ),
        migrations.AddField(
            model_name="datregistro",
            name="municipio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dat_registros",
                to="core.municipio",
                verbose_name="Município",
            ),
        ),
        migrations.AddField(
            model_name="datregistro",
            name="projeto",
            field=models.ForeignKey(
                help_text="Ex: VIDA E LINGUAGEM 6, ACERTA BRASIL MATEMATICA",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dat_registros",
                to="core.projeto",
                verbose_name="Projeto Específico",
            ),
        ),
        migrations.AddField(
            model_name="datregistro",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dat_registros_atualizados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Atualizado por",
            ),
        ),
        migrations.AddField(
            model_name="datregistro",
            name="projeto_geral",
            field=models.ForeignKey(
                help_text="Ex: ACERTA MATEMÁTICA, VIDA E LINGUAGEM",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dat_registros",
                to="core.projetogeral",
                verbose_name="Projeto Geral",
            ),
        ),
        migrations.AddField(
            model_name="projeto",
            name="projeto_geral",
            field=models.ForeignKey(
                blank=True,
                help_text="Projeto geral pai (ex: VIDA E LINGUAGEM para VIDA E LINGUAGEM 6)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projetos_especificos",
                to="core.projetogeral",
            ),
        ),
        migrations.AddIndex(
            model_name="datregistro",
            index=models.Index(
                fields=["municipio", "projeto_geral", "projeto"],
                name="core_dat_re_municip_0abe88_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="datregistro",
            index=models.Index(
                fields=["projeto_geral", "usa_avaliar"],
                name="core_dat_re_projeto_3ec655_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="datregistro",
            index=models.Index(
                fields=["external_hash"], name="core_dat_re_externa_6c1a87_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="datregistro",
            index=models.Index(
                fields=["turma_formar_id"], name="core_dat_re_turma_f_c5a31f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="datregistro",
            constraint=models.UniqueConstraint(
                fields=("municipio", "projeto_geral", "projeto"),
                name="unique_dat_registro_municipio_projeto",
            ),
        ),
    ]
