# Generated by Django 5.1.2 on 2025-12-15 13:08
"""
Data migration to seed ProjetoGeral table with initial data.

Data based on:
- entendimento-dat.md (planilha original)
- SPEC_DAT_REGISTROS.md (especificação do módulo)

Projetos que usam AVALIAR (11):
- ACERTA MATEMÁTICA, ACERTA PORTUGUÊS, NOVO LENDO, TEMA
- VIDA E CIÊNCIAS, VIDA E LINGUAGEM, VIDA E MATEMÁTICA
- PROJETO AMMA, SUPERATIVAR - LINGUAGENS, SUPERATIVAR - MATEMÁTICA
- GESTÃO ESCOLAR

Projetos com cálculo por_aluno (3):
- A COR DA GENTE, ED FINANCEIRA, ECS

Projetos sem códigos (1):
- FLUIR DAS EMOÇÕES

Demais projetos: cálculo por_professor (multiplicador 1.1)
"""
from decimal import Decimal

from django.db import migrations


PROJETOS_GERAIS = [
    # nome, usa_avaliar, tipo_calculo, divisor_aluno, multiplicador_professor
    ("A COR DA GENTE", False, "por_aluno", 20, Decimal("1.1")),
    ("ACERTA MATEMÁTICA", True, "por_professor", 20, Decimal("1.1")),
    ("ACERTA PORTUGUÊS", True, "por_professor", 20, Decimal("1.1")),
    ("AVANÇANDO JUNTOS MATEMÁTICA", False, "por_professor", 20, Decimal("1.1")),
    ("AVANÇANDO JUNTOS PORTUGUÊS", False, "por_professor", 20, Decimal("1.1")),
    ("BRINCANDO E APRENDENDO", False, "por_professor", 20, Decimal("1.1")),
    ("CIRANDAR", False, "por_professor", 20, Decimal("1.1")),
    ("ECS", False, "por_aluno", 20, Decimal("1.1")),
    ("ED FINANCEIRA", False, "por_aluno", 20, Decimal("1.1")),
    ("FLUIR DAS EMOÇÕES", False, "nao_aplicavel", 20, Decimal("1.1")),
    ("GESTÃO ESCOLAR", True, "por_professor", 20, Decimal("1.1")),
    ("LEIO, ESCREVO E CALCULO", False, "por_professor", 20, Decimal("1.1")),
    ("LENDO E ESCREVENDO", False, "por_professor", 20, Decimal("1.1")),
    ("LER, OUVIR E CONTAR", False, "por_professor", 20, Decimal("1.1")),
    ("NOVO LENDO", True, "por_professor", 20, Decimal("1.1")),
    ("PROJETO AMMA", True, "por_professor", 20, Decimal("1.1")),
    ("SUPERATIVAR - LINGUAGENS", True, "por_professor", 20, Decimal("1.1")),
    ("SUPERATIVAR - MATEMÁTICA", True, "por_professor", 20, Decimal("1.1")),
    ("TEMA", True, "por_professor", 20, Decimal("1.1")),
    ("VIDA E CIÊNCIAS", True, "por_professor", 20, Decimal("1.1")),
    ("VIDA E LINGUAGEM", True, "por_professor", 20, Decimal("1.1")),
    ("VIDA E MATEMÁTICA", True, "por_professor", 20, Decimal("1.1")),
]


def seed_projetos_gerais(apps, schema_editor):
    """Create initial ProjetoGeral records."""
    ProjetoGeral = apps.get_model("core", "ProjetoGeral")

    for nome, usa_avaliar, tipo_calculo, divisor, multiplicador in PROJETOS_GERAIS:
        ProjetoGeral.objects.get_or_create(
            nome=nome,
            defaults={
                "usa_avaliar": usa_avaliar,
                "tipo_calculo_codigos": tipo_calculo,
                "divisor_aluno": divisor,
                "multiplicador_professor": multiplicador,
                "ativo": True,
            }
        )


def reverse_seed(apps, schema_editor):
    """Remove seeded ProjetoGeral records."""
    ProjetoGeral = apps.get_model("core", "ProjetoGeral")
    nomes = [p[0] for p in PROJETOS_GERAIS]
    ProjetoGeral.objects.filter(nome__in=nomes).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_add_projeto_geral_and_dat_registro"),
    ]

    operations = [
        migrations.RunPython(seed_projetos_gerais, reverse_seed),
    ]
