# Generated by Django 5.1.2 on 2025-12-16 19:52

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_seed_projetos_gerais"),
    ]

    operations = [
        migrations.CreateModel(
            name="DATArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nome da Area"
                    ),
                ),
                (
                    "cor",
                    models.CharField(
                        blank=True,
                        help_text="Cor para exibicao na UI (ex: blue, green, red)",
                        max_length=20,
                        verbose_name="Cor",
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                (
                    "ordem",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Ordem de Exibicao"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Area DAT",
                "verbose_name_plural": "Areas DAT",
                "db_table": "core_dat_area",
                "ordering": ["ordem", "nome"],
            },
        ),
        migrations.AlterField(
            model_name="projetogeral",
            name="multiplicador_professor",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.1"),
                help_text="Multiplicador quando tipo = por_professor (ex: 10 professores * 1.1 = 11 códigos)",
                max_digits=3,
            ),
        ),
        migrations.CreateModel(
            name="DATCoordenador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=200, verbose_name="Nome Completo"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email Principal"
                    ),
                ),
                (
                    "email_alternativo",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email Alternativo"
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone Principal"
                    ),
                ),
                (
                    "telefone_alternativo",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefone Alternativo"
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        help_text="Ex: DAT, Tecnologia, Pedagogico",
                        max_length=100,
                        verbose_name="Area de Atuacao",
                    ),
                ),
                (
                    "cargo",
                    models.CharField(blank=True, max_length=100, verbose_name="Cargo"),
                ),
                ("ativo", models.BooleanField(default=True)),
                (
                    "data_admissao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Admissao"
                    ),
                ),
                (
                    "foto_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="URL da Foto"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(
                        blank=True, max_length=2000, verbose_name="Observacoes"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dat_coordenadores_criados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dat_coordenadores_atualizados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coordenador DAT",
                "verbose_name_plural": "Coordenadores DAT",
                "db_table": "core_dat_coordenador",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="DATAcao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status_carta",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("em_andamento", "Em Andamento"),
                            ("concluido", "Concluído"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendente",
                        max_length=20,
                        verbose_name="Status da Carta",
                    ),
                ),
                (
                    "data_carta",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Envio da Carta"
                    ),
                ),
                (
                    "observacao_carta",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Observação Carta"
                    ),
                ),
                (
                    "status_contato",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("em_andamento", "Em Andamento"),
                            ("concluido", "Concluído"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendente",
                        max_length=20,
                        verbose_name="Status do Contato",
                    ),
                ),
                (
                    "data_contato",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data do Contato"
                    ),
                ),
                (
                    "observacao_contato",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Observação Contato"
                    ),
                ),
                (
                    "status_reuniao",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("em_andamento", "Em Andamento"),
                            ("concluido", "Concluído"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendente",
                        max_length=20,
                        verbose_name="Status da Reunião",
                    ),
                ),
                (
                    "data_reuniao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data da Reunião"
                    ),
                ),
                (
                    "observacao_reuniao",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Observação Reunião"
                    ),
                ),
                (
                    "status_entrega",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("em_andamento", "Em Andamento"),
                            ("concluido", "Concluído"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendente",
                        max_length=20,
                        verbose_name="Status da Entrega",
                    ),
                ),
                (
                    "data_entrega",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data da Entrega"
                    ),
                ),
                (
                    "observacao_entrega",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Observação Entrega"
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                (
                    "prioridade",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="0 = normal, 1+ = alta prioridade",
                        verbose_name="Prioridade",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dat_acoes_criadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "municipio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dat_acoes",
                        to="core.municipio",
                        verbose_name="Município",
                    ),
                ),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dat_acoes",
                        to="core.projeto",
                        verbose_name="Projeto",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dat_acoes_atualizadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
                (
                    "coordenador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dat_acoes",
                        to="core.datcoordenador",
                        verbose_name="Coordenador Responsável",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ação DAT",
                "verbose_name_plural": "Ações DAT",
                "db_table": "core_dat_acao",
                "ordering": ["-prioridade", "municipio__nome"],
            },
        ),
        migrations.CreateModel(
            name="DATFormacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(max_length=200, verbose_name="Título da Formação"),
                ),
                (
                    "descricao",
                    models.TextField(
                        blank=True, max_length=2000, verbose_name="Descrição"
                    ),
                ),
                ("data_formacao", models.DateField(verbose_name="Data da Formação")),
                ("horario_inicio", models.TimeField(verbose_name="Horário de Início")),
                ("horario_fim", models.TimeField(verbose_name="Horário de Término")),
                (
                    "modalidade",
                    models.CharField(
                        choices=[
                            ("presencial", "Presencial"),
                            ("online", "Online"),
                            ("hibrido", "Híbrido"),
                        ],
                        default="presencial",
                        max_length=20,
                        verbose_name="Modalidade",
                    ),
                ),
                (
                    "local",
                    models.CharField(
                        blank=True,
                        help_text="Endereço ou link da reunião online",
                        max_length=300,
                        verbose_name="Local",
                    ),
                ),
                (
                    "quantidade_prevista",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Participantes Previstos"
                    ),
                ),
                (
                    "quantidade_confirmada",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Participantes Confirmados"
                    ),
                ),
                (
                    "quantidade_presente",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Participantes Presentes"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("agendada", "Agendada"),
                            ("confirmada", "Confirmada"),
                            ("em_andamento", "Em Andamento"),
                            ("realizada", "Realizada"),
                            ("cancelada", "Cancelada"),
                            ("adiada", "Adiada"),
                        ],
                        default="agendada",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "motivo_cancelamento",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        verbose_name="Motivo Cancelamento/Adiamento",
                    ),
                ),
                (
                    "material_preparado",
                    models.BooleanField(
                        default=False, verbose_name="Material Preparado"
                    ),
                ),
                (
                    "lista_presenca_enviada",
                    models.BooleanField(
                        default=False, verbose_name="Lista de Presença Enviada"
                    ),
                ),
                (
                    "relatorio_enviado",
                    models.BooleanField(
                        default=False, verbose_name="Relatório Enviado"
                    ),
                ),
                (
                    "fotos_enviadas",
                    models.BooleanField(default=False, verbose_name="Fotos Enviadas"),
                ),
                (
                    "link_material",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="Link do Material"
                    ),
                ),
                (
                    "link_lista_presenca",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        verbose_name="Link Lista de Presença",
                    ),
                ),
                (
                    "link_relatorio",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="Link do Relatório"
                    ),
                ),
                (
                    "link_fotos",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="Link das Fotos"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(
                        blank=True, max_length=2000, verbose_name="Observações"
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "coordenador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dat_formacoes",
                        to="core.datcoordenador",
                        verbose_name="Coordenador Responsável",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dat_formacoes_criadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "municipio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dat_formacoes",
                        to="core.municipio",
                        verbose_name="Município",
                    ),
                ),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dat_formacoes",
                        to="core.projeto",
                        verbose_name="Projeto",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dat_formacoes_atualizadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Formação DAT",
                "verbose_name_plural": "Formações DAT",
                "db_table": "core_dat_formacao",
                "ordering": ["-data_formacao", "horario_inicio"],
            },
        ),
        migrations.CreateModel(
            name="DATCadastro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plataforma",
                    models.CharField(
                        choices=[("FORMAR", "FORMAR"), ("AVALIAR", "AVALIAR")],
                        max_length=10,
                        verbose_name="Plataforma",
                    ),
                ),
                (
                    "status_criacao_curso",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("em_andamento", "Em Andamento"),
                            ("concluido", "Concluído"),
                            ("erro", "Erro"),
                            ("na", "N/A"),
                        ],
                        default="pendente",
                        max_length=20,
                        verbose_name="Criação do Curso",
                    ),
                ),
                (
                    "data_criacao_curso",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Criação Curso"
                    ),
                ),
                (
                    "status_chaves",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("em_andamento", "Em Andamento"),
                            ("concluido", "Concluído"),
                            ("erro", "Erro"),
                            ("na", "N/A"),
                        ],
                        default="pendente",
                        max_length=20,
                        verbose_name="Chaves de Acesso",
                    ),
                ),
                (
                    "data_chaves",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Geração Chaves"
                    ),
                ),
                (
                    "quantidade_chaves",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Quantidade de Chaves"
                    ),
                ),
                (
                    "status_instrucoes",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("em_andamento", "Em Andamento"),
                            ("concluido", "Concluído"),
                            ("erro", "Erro"),
                            ("na", "N/A"),
                        ],
                        default="pendente",
                        max_length=20,
                        verbose_name="Instruções",
                    ),
                ),
                (
                    "data_instrucoes",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Envio Instruções"
                    ),
                ),
                (
                    "status_envio",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("em_andamento", "Em Andamento"),
                            ("concluido", "Concluído"),
                            ("erro", "Erro"),
                            ("na", "N/A"),
                        ],
                        default="pendente",
                        max_length=20,
                        verbose_name="Envio ao Município",
                    ),
                ),
                (
                    "data_envio",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Envio"
                    ),
                ),
                (
                    "status_recebidos",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("em_andamento", "Em Andamento"),
                            ("concluido", "Concluído"),
                            ("erro", "Erro"),
                            ("na", "N/A"),
                        ],
                        default="pendente",
                        max_length=20,
                        verbose_name="Dados Recebidos",
                    ),
                ),
                (
                    "data_recebidos",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Recebimento"
                    ),
                ),
                (
                    "quantidade_recebidos",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Quantidade Recebida"
                    ),
                ),
                (
                    "status_validados",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("em_andamento", "Em Andamento"),
                            ("concluido", "Concluído"),
                            ("erro", "Erro"),
                            ("na", "N/A"),
                        ],
                        default="pendente",
                        max_length=20,
                        verbose_name="Dados Validados",
                    ),
                ),
                (
                    "data_validados",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Validação"
                    ),
                ),
                (
                    "quantidade_validados",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Quantidade Validada"
                    ),
                ),
                (
                    "status_importados",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("em_andamento", "Em Andamento"),
                            ("concluido", "Concluído"),
                            ("erro", "Erro"),
                            ("na", "N/A"),
                        ],
                        default="pendente",
                        max_length=20,
                        verbose_name="Dados Importados",
                    ),
                ),
                (
                    "data_importados",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data Importação"
                    ),
                ),
                (
                    "quantidade_importados",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Quantidade Importada"
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                (
                    "observacoes",
                    models.TextField(
                        blank=True, max_length=1000, verbose_name="Observações"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dat_cadastros_criados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "municipio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dat_cadastros",
                        to="core.municipio",
                        verbose_name="Município",
                    ),
                ),
                (
                    "projeto_geral",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dat_cadastros",
                        to="core.projeto",
                        verbose_name="Projeto Geral",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dat_cadastros_atualizados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cadastro DAT",
                "verbose_name_plural": "Cadastros DAT",
                "db_table": "core_dat_cadastro",
                "ordering": ["plataforma", "municipio__nome"],
                "indexes": [
                    models.Index(
                        fields=["municipio", "projeto_geral"],
                        name="core_dat_ca_municip_23107b_idx",
                    ),
                    models.Index(
                        fields=["plataforma", "ativo"],
                        name="core_dat_ca_platafo_25f028_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("municipio", "projeto_geral", "plataforma"),
                        name="unique_dat_cadastro_mun_proj_plat",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DATCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao_produto",
                    models.CharField(
                        blank=True,
                        help_text="Use quando produto não está cadastrado",
                        max_length=300,
                        verbose_name="Descrição do Produto",
                    ),
                ),
                (
                    "quantidade",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Quantidade Adquirida"
                    ),
                ),
                (
                    "quantidade_utilizada",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Quantidade Utilizada"
                    ),
                ),
                (
                    "valor_unitario",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Valor Unitário (R$)",
                    ),
                ),
                (
                    "ano_uso",
                    models.PositiveSmallIntegerField(
                        help_text="Ano em que o material será/foi utilizado",
                        verbose_name="Ano de Uso",
                    ),
                ),
                (
                    "data_compra",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data da Compra"
                    ),
                ),
                (
                    "status_uso",
                    models.CharField(
                        choices=[
                            ("disponivel", "Disponível"),
                            ("em_uso", "Em Uso"),
                            ("esgotado", "Esgotado"),
                            ("devolvido", "Devolvido"),
                        ],
                        default="disponivel",
                        max_length=20,
                        verbose_name="Status de Uso",
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                (
                    "observacoes",
                    models.TextField(
                        blank=True, max_length=1000, verbose_name="Observações"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dat_compras_criadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "municipio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dat_compras",
                        to="core.municipio",
                        verbose_name="Município",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dat_compras",
                        to="core.produto",
                        verbose_name="Produto",
                    ),
                ),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dat_compras",
                        to="core.projeto",
                        verbose_name="Projeto",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dat_compras_atualizadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compra DAT",
                "verbose_name_plural": "Compras DAT",
                "db_table": "core_dat_compra",
                "ordering": ["-ano_uso", "municipio__nome"],
                "indexes": [
                    models.Index(
                        fields=["municipio", "projeto"],
                        name="core_dat_co_municip_d68561_idx",
                    ),
                    models.Index(
                        fields=["ano_uso", "status_uso"],
                        name="core_dat_co_ano_uso_975e01_idx",
                    ),
                    models.Index(
                        fields=["produto"], name="core_dat_co_produto_43ad3a_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="datcoordenador",
            index=models.Index(
                fields=["area", "ativo"], name="core_dat_co_area_6d1ef9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="datcoordenador",
            index=models.Index(fields=["nome"], name="core_dat_co_nome_a35f63_idx"),
        ),
        migrations.AddIndex(
            model_name="datacao",
            index=models.Index(
                fields=["municipio", "projeto"], name="core_dat_ac_municip_804093_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="datacao",
            index=models.Index(
                fields=["coordenador", "ativo"], name="core_dat_ac_coorden_37483d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="datacao",
            index=models.Index(
                fields=["status_carta"], name="core_dat_ac_status__9c65b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="datacao",
            index=models.Index(
                fields=["status_entrega"], name="core_dat_ac_status__d7321a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="datacao",
            constraint=models.UniqueConstraint(
                fields=("municipio", "projeto"),
                name="unique_dat_acao_municipio_projeto",
            ),
        ),
        migrations.AddIndex(
            model_name="datformacao",
            index=models.Index(
                fields=["municipio", "projeto"], name="core_dat_fo_municip_122384_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="datformacao",
            index=models.Index(
                fields=["coordenador", "status"], name="core_dat_fo_coorden_d2e335_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="datformacao",
            index=models.Index(
                fields=["data_formacao", "status"],
                name="core_dat_fo_data_fo_410295_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="datformacao",
            index=models.Index(
                fields=["modalidade"], name="core_dat_fo_modalid_dbb8ad_idx"
            ),
        ),
    ]
