# Generated by Django 5.1.2 on 2025-12-16 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_dat_module"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datcadastro",
            name="projeto_geral",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dat_cadastros",
                to="core.projetogeral",
                verbose_name="Projeto Geral",
            ),
        ),
    ]
