# Generated by Django 5.1.2 on 2025-12-22 20:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_fix_dat_cadastro_fk"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanoFormacoes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ch_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Soma das cargas horarias das formacoes",
                        max_digits=6,
                        verbose_name="CH Total Formacoes",
                    ),
                ),
                (
                    "ch_estudo",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Carga horaria adicional de estudo",
                        max_digits=6,
                        verbose_name="CH Estudo",
                    ),
                ),
                (
                    "ch_anual",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="CH total anual (formacoes + estudo)",
                        max_digits=6,
                        verbose_name="CH Anual",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(
                        blank=True, max_length=2000, verbose_name="Observacoes"
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "coordenador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planos_formacoes",
                        to="core.datcoordenador",
                        verbose_name="Coordenador Responsavel",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="planos_formacoes_criados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "municipio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="planos_formacoes",
                        to="core.municipio",
                        verbose_name="Municipio",
                    ),
                ),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="planos_formacoes",
                        to="core.projeto",
                        verbose_name="Projeto",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planos_formacoes_atualizados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plano de Formacoes",
                "verbose_name_plural": "Planos de Formacoes",
                "db_table": "core_plano_formacoes",
                "ordering": ["municipio__nome", "projeto__nome"],
            },
        ),
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_formacao",
                    models.PositiveSmallIntegerField(
                        help_text="Numero sequencial da formacao (1 a 15)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(15),
                        ],
                        verbose_name="Numero da Formacao",
                    ),
                ),
                (
                    "data_formacao",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data da Formacao"
                    ),
                ),
                (
                    "carga_horaria",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("4.00"),
                        help_text="Carga horaria em horas",
                        max_digits=4,
                        verbose_name="Carga Horaria",
                    ),
                ),
                (
                    "modalidade",
                    models.CharField(
                        choices=[("presencial", "Presencial"), ("online", "Online")],
                        default="presencial",
                        max_length=20,
                        verbose_name="Modalidade",
                    ),
                ),
                (
                    "horario_inicio",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Horario de Inicio"
                    ),
                ),
                (
                    "horario_fim",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Horario de Termino"
                    ),
                ),
                (
                    "local_formacao",
                    models.CharField(
                        blank=True,
                        help_text="Endereco ou link da reuniao online",
                        max_length=200,
                        verbose_name="Local",
                    ),
                ),
                (
                    "formador_nome",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Nome do Formador"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("agendada", "Agendada"),
                            ("realizada", "Realizada"),
                            ("cancelada", "Cancelada"),
                            ("reagendada", "Reagendada"),
                        ],
                        default="agendada",
                        max_length=30,
                        verbose_name="Status",
                    ),
                ),
                (
                    "realizada",
                    models.BooleanField(default=False, verbose_name="Realizada"),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plano",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formacoes",
                        to="core.planoformacoes",
                        verbose_name="Plano de Formacoes",
                    ),
                ),
            ],
            options={
                "verbose_name": "Formacao",
                "verbose_name_plural": "Formacoes",
                "db_table": "core_formacao",
                "ordering": ["plano", "numero_formacao"],
            },
        ),
        migrations.CreateModel(
            name="Acompanhamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("primeiro", "1o Acompanhamento"),
                            ("segundo", "2o Acompanhamento"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Acompanhamento",
                    ),
                ),
                (
                    "data_acompanhamento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data do Acompanhamento"
                    ),
                ),
                (
                    "realizado",
                    models.BooleanField(default=False, verbose_name="Realizado"),
                ),
                (
                    "observacoes",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Observacoes"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plano",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acompanhamentos",
                        to="core.planoformacoes",
                        verbose_name="Plano de Formacoes",
                    ),
                ),
            ],
            options={
                "verbose_name": "Acompanhamento",
                "verbose_name_plural": "Acompanhamentos",
                "db_table": "core_acompanhamento",
                "ordering": ["plano", "tipo"],
            },
        ),
        migrations.CreateModel(
            name="Prova",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_prova",
                    models.PositiveSmallIntegerField(
                        help_text="Numero sequencial da prova (1 a 3)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3),
                        ],
                        verbose_name="Numero da Prova",
                    ),
                ),
                (
                    "data_prova",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data da Prova"
                    ),
                ),
                (
                    "realizada",
                    models.BooleanField(default=False, verbose_name="Realizada"),
                ),
                (
                    "observacoes",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Observacoes"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plano",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provas",
                        to="core.planoformacoes",
                        verbose_name="Plano de Formacoes",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prova",
                "verbose_name_plural": "Provas",
                "db_table": "core_prova",
                "ordering": ["plano", "numero_prova"],
            },
        ),
        migrations.AddIndex(
            model_name="planoformacoes",
            index=models.Index(
                fields=["municipio", "projeto"], name="core_plano__municip_2827c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="planoformacoes",
            index=models.Index(
                fields=["coordenador", "ativo"], name="core_plano__coorden_739349_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="planoformacoes",
            constraint=models.UniqueConstraint(
                fields=("municipio", "projeto"), name="unique_plano_municipio_projeto"
            ),
        ),
        migrations.AddIndex(
            model_name="formacao",
            index=models.Index(
                fields=["plano", "numero_formacao"],
                name="core_formac_plano_i_ee3f7e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="formacao",
            index=models.Index(
                fields=["data_formacao", "status"],
                name="core_formac_data_fo_8c6c43_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="formacao",
            index=models.Index(
                fields=["realizada"], name="core_formac_realiza_754bc5_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="formacao",
            constraint=models.UniqueConstraint(
                fields=("plano", "numero_formacao"), name="unique_formacao_plano_numero"
            ),
        ),
        migrations.AddConstraint(
            model_name="formacao",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("numero_formacao__gte", 1), ("numero_formacao__lte", 15)
                ),
                name="formacao_numero_range",
            ),
        ),
        migrations.AddIndex(
            model_name="acompanhamento",
            index=models.Index(
                fields=["plano", "tipo"], name="core_acompa_plano_i_21fed0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="acompanhamento",
            index=models.Index(
                fields=["data_acompanhamento"], name="core_acompa_data_ac_180cc7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="acompanhamento",
            index=models.Index(
                fields=["realizado"], name="core_acompa_realiza_098b6d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="acompanhamento",
            constraint=models.UniqueConstraint(
                fields=("plano", "tipo"), name="unique_acompanhamento_plano_tipo"
            ),
        ),
        migrations.AddIndex(
            model_name="prova",
            index=models.Index(
                fields=["plano", "numero_prova"], name="core_prova_plano_i_2ff417_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prova",
            index=models.Index(
                fields=["data_prova"], name="core_prova_data_pr_8ba8d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prova",
            index=models.Index(
                fields=["realizada"], name="core_prova_realiza_02ccdd_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="prova",
            constraint=models.UniqueConstraint(
                fields=("plano", "numero_prova"), name="unique_prova_plano_numero"
            ),
        ),
        migrations.AddConstraint(
            model_name="prova",
            constraint=models.CheckConstraint(
                condition=models.Q(("numero_prova__gte", 1), ("numero_prova__lte", 3)),
                name="prova_numero_range",
            ),
        ),
    ]
