# Generated by Django 5.1.2 on 2025-12-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_create_plano_formacoes_structure"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacao",
            name="local",
            field=models.CharField(
                blank=True,
                help_text="Endereco ou local especifico do evento (ex: Escola Municipal X, Sala 5)",
                max_length=300,
                verbose_name="Local do Evento",
            ),
        ),
    ]
