# Generated by Django 5.1.2 on 2025-12-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_add_auditlog_gin_index"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="auditlog",
            name="idx_auditlog_details_gin",
        ),
        migrations.AlterUniqueTogether(
            name="equipegerencia",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="equipegerencia",
            constraint=models.UniqueConstraint(
                fields=("gerencia", "usuario", "papel"),
                name="unique_equipe_gerencia_usuario_papel",
            ),
        ),
    ]
