# Generated by Django 5.1.2 on 2026-02-06 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_migrate_unique_together_to_constraint"),
    ]

    operations = [
        migrations.CreateModel(
            name="Colecao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(help_text="Nome da colecao (ex: A COR DA GENTE 1)", max_length=200)),
                ("descricao", models.TextField(blank=True, help_text="Descricao da colecao")),
                ("ativo", models.BooleanField(default=True, help_text="Colecao ativa")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "projeto",
                    models.ForeignKey(
                        help_text="Projeto vinculado",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="colecoes",
                        to="core.projeto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Colecao",
                "verbose_name_plural": "Colecoes",
                "db_table": "core_colecao",
                "ordering": ["projeto", "nome"],
            },
        ),
        migrations.AddField(
            model_name="produto",
            name="colecao",
            field=models.ForeignKey(
                blank=True,
                help_text="Colecao do produto",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="produtos",
                to="core.colecao",
            ),
        ),
        migrations.AddConstraint(
            model_name="colecao",
            constraint=models.UniqueConstraint(fields=("nome", "projeto"), name="unique_colecao_nome_projeto"),
        ),
    ]
