# Generated by Django 5.1 on 2026-02-06
# Migration: Criar grupo Diretoria (setor)

from django.db import migrations


def create_diretoria_group(apps, schema_editor):
    """Cria o grupo Diretoria (setor) para RBAC."""
    Group = apps.get_model("auth", "Group")
    Group.objects.get_or_create(name="Diretoria")


def reverse_migration(apps, schema_editor):
    """Remove o grupo Diretoria criado por esta migration."""
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name="Diretoria").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0051_migrate_unique_together_to_constraint"),
    ]

    operations = [
        migrations.RunPython(create_diretoria_group, reverse_migration),
    ]
