# Generated by Django 5.1.2 on 2026-02-06 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_add_diretoria_group"),
        ("core", "0055_update_municipio_unique_nome_uf"),
    ]

    operations = []
