# Generated by Django 5.1.2 on 2026-03-04 13:30

from __future__ import annotations

import re
import unicodedata

from django.db import migrations, models

TIPO_ACAO_CANONICO = {
    "CRIACAO_CURSO": "FORMAR - Criação de Curso",
    "CRIACAO_CHAVES": "FORMAR - Criação de Chaves",
    "CRIACAO_INSTRUCOES": "FORMAR - Criação de Instruções",
    "CHAVES_ENVIADAS": "FORMAR - Chaves enviadas",
    "CODIGOS_ENVIADOS": "Códigos enviados",
    "REUNIAO_DAT": "Reunião DAT",
}

NORMALIZACOES = {
    # FORMAR - Criação de Curso
    "formar - criacao de curso": TIPO_ACAO_CANONICO["CRIACAO_CURSO"],
    "formar-criacao de curso": TIPO_ACAO_CANONICO["CRIACAO_CURSO"],
    "formar criacao de curso": TIPO_ACAO_CANONICO["CRIACAO_CURSO"],
    "formar criacao curso": TIPO_ACAO_CANONICO["CRIACAO_CURSO"],
    # FORMAR - Criação de Chaves
    "formar - criacao de chaves": TIPO_ACAO_CANONICO["CRIACAO_CHAVES"],
    "formar-criacao de chaves": TIPO_ACAO_CANONICO["CRIACAO_CHAVES"],
    "formar criacao de chaves": TIPO_ACAO_CANONICO["CRIACAO_CHAVES"],
    "formar criacao chaves": TIPO_ACAO_CANONICO["CRIACAO_CHAVES"],
    # FORMAR - Criação de Instruções
    "formar - criacao de instrucoes": TIPO_ACAO_CANONICO["CRIACAO_INSTRUCOES"],
    "formar-criacao de instrucoes": TIPO_ACAO_CANONICO["CRIACAO_INSTRUCOES"],
    "formar criacao de instrucoes": TIPO_ACAO_CANONICO["CRIACAO_INSTRUCOES"],
    "formar criacao instrucoes": TIPO_ACAO_CANONICO["CRIACAO_INSTRUCOES"],
    # FORMAR - Chaves enviadas
    "formar - chaves enviadas": TIPO_ACAO_CANONICO["CHAVES_ENVIADAS"],
    "formar-chaves enviadas": TIPO_ACAO_CANONICO["CHAVES_ENVIADAS"],
    "formar chaves enviadas": TIPO_ACAO_CANONICO["CHAVES_ENVIADAS"],
    "formar - chave enviada": TIPO_ACAO_CANONICO["CHAVES_ENVIADAS"],
    # Códigos enviados
    "codigos enviados": TIPO_ACAO_CANONICO["CODIGOS_ENVIADOS"],
    "codigo enviado": TIPO_ACAO_CANONICO["CODIGOS_ENVIADOS"],
    # Reunião DAT
    "reuniao dat": TIPO_ACAO_CANONICO["REUNIAO_DAT"],
    "reuniao - dat": TIPO_ACAO_CANONICO["REUNIAO_DAT"],
}


def _norm_text(value: str) -> str:
    value = value.strip()
    value = re.sub(r"\s+", " ", value)
    value = unicodedata.normalize("NFKD", value)
    value = value.encode("ascii", "ignore").decode("ascii")
    return value.lower()


def normalize_acao_dat_tipo_acao(apps, schema_editor):
    if apps is None:
        from apps.core.models import AcaoDAT as AcaoDATModel

        AcaoDAT = AcaoDATModel
    else:
        AcaoDAT = apps.get_model("core", "AcaoDAT")

    qs = AcaoDAT.objects.exclude(tipo_acao__isnull=True).exclude(tipo_acao="")
    for acao in qs.only("id", "tipo_acao").iterator():
        canonical = NORMALIZACOES.get(_norm_text(acao.tipo_acao))
        if canonical and canonical != acao.tipo_acao:
            AcaoDAT.objects.filter(pk=acao.pk).update(tipo_acao=canonical)


def reverse_noop(apps, schema_editor):
    return None


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0056_merge_20260206_1404"),
    ]

    operations = [
        migrations.RunPython(normalize_acao_dat_tipo_acao, reverse_noop),
        migrations.AlterField(
            model_name="acaodat",
            name="tipo_acao",
            field=models.CharField(
                choices=[
                    ("FORMAR - Criação de Curso", "FORMAR - Criação de Curso"),
                    ("FORMAR - Criação de Chaves", "FORMAR - Criação de Chaves"),
                    ("FORMAR - Criação de Instruções", "FORMAR - Criação de Instruções"),
                    ("FORMAR - Chaves enviadas", "FORMAR - Chaves enviadas"),
                    ("Códigos enviados", "Códigos enviados"),
                    ("Reunião DAT", "Reunião DAT"),
                ],
                max_length=120,
                verbose_name="Tipo de Ação",
            ),
        ),
    ]
