# Generated by Django 5.1.15 on 2026-03-04 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0057_normalize_acao_dat_tipo_acao_choices"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="municipioreferencia",
            new_name="core_munici_nome_391dc0_idx",
            old_name="core_municipi_nome_90d16f_idx",
        ),
    ]
