# Generated by Django 5.1.15 on 2026-03-13 12:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0058_rename_core_municipi_nome_90d16f_idx_core_munici_nome_391dc0_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcaoTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ordem", models.PositiveIntegerField(db_index=True, unique=True)),
                ("nome", models.CharField(max_length=255)),
                (
                    "descricao_prazo",
                    models.TextField(help_text="Descricao original da regra de prazo (texto de negocio)."),
                ),
                (
                    "tipo_ancora",
                    models.CharField(
                        choices=[
                            ("EVENTO_EXTERNO", "Evento Externo"),
                            ("ACAO_ANTERIOR", "Acao Anterior"),
                            ("MARCO_CALENDARIO", "Marco de Calendario"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "ref_evento_externo",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Identificador de evento externo quando tipo_ancora != ACAO_ANTERIOR.",
                        max_length=120,
                    ),
                ),
                ("dias_prazo_uteis", models.PositiveIntegerField(help_text="Prazo em dias uteis a partir da ancora.")),
                ("ativo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ref_acao_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acoes_dependentes",
                        to="core.acaotemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Acao Template",
                "verbose_name_plural": "Acoes Template",
                "db_table": "core_acao_template",
                "ordering": ["ordem"],
            },
        ),
        migrations.CreateModel(
            name="AcaoTemplateExecutor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ativo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "acao_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="executores", to="core.acaotemplate"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="acoes_template", to="auth.group"
                    ),
                ),
            ],
            options={
                "verbose_name": "Executor de Acao Template",
                "verbose_name_plural": "Executores de Acoes Template",
                "db_table": "core_acao_template_executor",
                "ordering": ["acao_template__ordem", "group__name"],
            },
        ),
        migrations.CreateModel(
            name="CicloAcoes",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("semestre", models.CharField(choices=[("1S", "1º Semestre"), ("2S", "2º Semestre")], max_length=2)),
                ("ano", models.PositiveIntegerField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EM_ANDAMENTO", "Em andamento"),
                            ("CONCLUIDO", "Concluido"),
                            ("CONCLUIDO_COM_ATRASO", "Concluido com atraso"),
                        ],
                        default="EM_ANDAMENTO",
                        max_length=25,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ciclos_acoes_criados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "municipio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="ciclos_acoes", to="core.municipio"
                    ),
                ),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="ciclos_acoes", to="core.projeto"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ciclo de Acoes",
                "verbose_name_plural": "Ciclos de Acoes",
                "db_table": "core_ciclo_acoes",
                "ordering": ["-ano", "semestre", "projeto__nome", "municipio__nome"],
            },
        ),
        migrations.CreateModel(
            name="AcaoInstancia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ordem", models.PositiveIntegerField(db_index=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("AGUARDANDO_ANCORA", "Aguardando ancora"),
                            ("EM_ANDAMENTO", "Em andamento"),
                            ("CONCLUIDA", "Concluida"),
                            ("ATRASADA", "Atrasada"),
                        ],
                        default="AGUARDANDO_ANCORA",
                        max_length=20,
                    ),
                ),
                ("data_ancora", models.DateField(blank=True, null=True)),
                ("data_vencimento", models.DateField(blank=True, null=True)),
                ("data_realizacao", models.DateField(blank=True, null=True)),
                ("observacao_conclusao", models.TextField(blank=True, default="")),
                ("concluida_em", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "concluida_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acoes_instancia_concluidas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="instancias", to="core.acaotemplate"
                    ),
                ),
                (
                    "ciclo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="acoes", to="core.cicloacoes"
                    ),
                ),
            ],
            options={
                "verbose_name": "Acao Instancia",
                "verbose_name_plural": "Acoes Instancia",
                "db_table": "core_acao_instancia",
                "ordering": ["ciclo", "ordem"],
            },
        ),
        migrations.CreateModel(
            name="FeriadoLocal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("data", models.DateField(db_index=True)),
                ("nome", models.CharField(max_length=150)),
                (
                    "abrangencia",
                    models.CharField(
                        choices=[
                            ("NACIONAL", "Nacional (Brasil)"),
                            ("ESTADUAL_CE", "Estadual (Ceara)"),
                            ("MUNICIPAL_FORTALEZA", "Municipal (Fortaleza)"),
                        ],
                        max_length=25,
                    ),
                ),
                ("ativo", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Feriado Local",
                "verbose_name_plural": "Feriados Locais",
                "db_table": "core_feriado_local",
                "ordering": ["data", "abrangencia", "nome"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("data", "abrangencia", "nome"), name="unique_feriado_local_data_abrangencia_nome"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificacaoInterna",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("titulo", models.CharField(max_length=200)),
                ("mensagem", models.TextField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("LEMBRETE", "Lembrete"),
                            ("VENCIMENTO", "Vencimento"),
                            ("ATRASO", "Atraso"),
                            ("ESCALONAMENTO", "Escalonamento"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("RESPONSAVEL", "Responsavel"),
                            ("COORDENADOR", "Coordenador"),
                            ("GERENTE", "Gerente"),
                            ("DAT", "DAT"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "prioridade",
                    models.CharField(
                        choices=[("BAIXA", "Baixa"), ("MEDIA", "Media"), ("ALTA", "Alta"), ("CRITICA", "Critica")],
                        default="MEDIA",
                        max_length=10,
                    ),
                ),
                (
                    "fase_disparo",
                    models.CharField(blank=True, default="", help_text="Exemplo: D-7, D0, D+1, D+3.", max_length=10),
                ),
                ("referencia_data", models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ("lida", models.BooleanField(db_index=True, default=False)),
                ("lida_em", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "acao_instancia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificacoes",
                        to="core.acaoinstancia",
                    ),
                ),
                (
                    "destinatario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificacoes_internas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificacao Interna",
                "verbose_name_plural": "Notificacoes Internas",
                "db_table": "core_notificacao_interna",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RegistroAncora",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("data_ancora", models.DateField()),
                ("observacao", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "acao_instancia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros_ancora",
                        to="core.acaoinstancia",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registros_ancora",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Ancora",
                "verbose_name_plural": "Registros de Ancora",
                "db_table": "core_registro_ancora",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RegistroConclusaoAcao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("data_realizacao", models.DateField()),
                ("observacao", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "acao_instancia",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registro_conclusao",
                        to="core.acaoinstancia",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registros_conclusao_acao",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Conclusao da Acao",
                "verbose_name_plural": "Registros de Conclusao da Acao",
                "db_table": "core_registro_conclusao_acao",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="acaotemplate",
            constraint=models.CheckConstraint(condition=models.Q(("ordem__gt", 0)), name="acao_template_ordem_gt_zero"),
        ),
        migrations.AddConstraint(
            model_name="acaotemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(("dias_prazo_uteis__gt", 0)), name="acao_template_prazo_gt_zero"
            ),
        ),
        migrations.AddConstraint(
            model_name="acaotemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("tipo_ancora", "ACAO_ANTERIOR"), _negated=True),
                    ("ref_acao_template__isnull", False),
                    _connector="OR",
                ),
                name="acao_template_ancora_acao_requer_ref",
            ),
        ),
        migrations.AddConstraint(
            model_name="acaotemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("tipo_ancora", "ACAO_ANTERIOR"),
                    models.Q(("ref_evento_externo", ""), _negated=True),
                    _connector="OR",
                ),
                name="acao_template_ancora_evento_requer_ref",
            ),
        ),
        migrations.AddConstraint(
            model_name="acaotemplateexecutor",
            constraint=models.UniqueConstraint(
                fields=("acao_template", "group"), name="unique_acao_template_executor_group"
            ),
        ),
        migrations.AddConstraint(
            model_name="cicloacoes",
            constraint=models.UniqueConstraint(
                fields=("projeto", "municipio", "semestre", "ano"), name="unique_ciclo_acoes_contexto"
            ),
        ),
        migrations.AddConstraint(
            model_name="cicloacoes",
            constraint=models.CheckConstraint(condition=models.Q(("ano__gte", 2020)), name="ciclo_acoes_ano_min_2020"),
        ),
        migrations.AddConstraint(
            model_name="acaoinstancia",
            constraint=models.UniqueConstraint(fields=("ciclo", "ordem"), name="unique_acao_instancia_ciclo_ordem"),
        ),
        migrations.AddConstraint(
            model_name="acaoinstancia",
            constraint=models.UniqueConstraint(
                fields=("ciclo", "template"), name="unique_acao_instancia_ciclo_template"
            ),
        ),
        migrations.AddConstraint(
            model_name="acaoinstancia",
            constraint=models.CheckConstraint(
                condition=models.Q(("ordem__gt", 0)), name="acao_instancia_ordem_gt_zero"
            ),
        ),
        migrations.AddConstraint(
            model_name="acaoinstancia",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("estado", "CONCLUIDA"), _negated=True),
                    ("data_realizacao__isnull", False),
                    _connector="OR",
                ),
                name="acao_instancia_concluida_requer_data_realizacao",
            ),
        ),
        migrations.AddConstraint(
            model_name="acaoinstancia",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("estado", "CONCLUIDA"), _negated=True),
                    models.Q(("observacao_conclusao", ""), _negated=True),
                    _connector="OR",
                ),
                name="acao_instancia_concluida_requer_observacao",
            ),
        ),
        migrations.AddIndex(
            model_name="notificacaointerna",
            index=models.Index(fields=["destinatario", "lida", "created_at"], name="core_notifi_destina_aa0405_idx"),
        ),
        migrations.AddIndex(
            model_name="notificacaointerna",
            index=models.Index(fields=["acao_instancia", "created_at"], name="core_notifi_acao_in_6297d1_idx"),
        ),
        migrations.AddConstraint(
            model_name="notificacaointerna",
            constraint=models.UniqueConstraint(
                fields=("destinatario", "acao_instancia", "fase_disparo", "referencia_data"),
                name="unique_notificacao_interna_escopo_disparo",
            ),
        ),
        migrations.AddIndex(
            model_name="registroancora",
            index=models.Index(fields=["acao_instancia", "created_at"], name="core_regist_acao_in_898946_idx"),
        ),
    ]
