# Generated by Django 5.1.15 on 2026-03-13 14:05
"""
Data migration (frozen) for 32 action templates and executor mapping.

Do not import runtime constants/services in this migration.
"""

from __future__ import annotations

from django.db import migrations, transaction

_GROUPS = [
    "Comercial",
    "Relacionamento",
    "Logística Viagens",
    "Logística Galpão",
    "DAT",
    "Coordenador",
    "Gerente",
]

_SEED_ACTIONS = [
    {
        "ordem": 1,
        "nome": "ENTREGA DOS MATERIAIS",
        "descricao_prazo": "Até 21 dias úteis após ordem fornecimento",
        "tipo_ancora": "EVENTO_EXTERNO",
        "dias_prazo_uteis": 21,
        "ref_evento_externo": "ORDEM_FORNECIMENTO",
        "ref_acao_ordem": None,
    },
    {
        "ordem": 2,
        "nome": "BOAS VINDAS",
        "descricao_prazo": "Até 7 dias úteis após entrega prazo",
        "tipo_ancora": "ACAO_ANTERIOR",
        "dias_prazo_uteis": 7,
        "ref_evento_externo": "",
        "ref_acao_ordem": 1,
    },
    {
        "ordem": 3,
        "nome": "PRIMEIRO CONTATO/SME",
        "descricao_prazo": "Até 5 dias úteis após coordenação ser informada sobre o Município",
        "tipo_ancora": "EVENTO_EXTERNO",
        "dias_prazo_uteis": 5,
        "ref_evento_externo": "COORDENACAO_INFORMADA_MUNICIPIO",
        "ref_acao_ordem": None,
    },
    {
        "ordem": 4,
        "nome": "REUNIÃO DE ARTICULAÇÃO/ SME",
        "descricao_prazo": "Até 5 dias úteis após a a reunião de alinhamento (formato virtual) / Até 10 dias se formato presencial",
        "tipo_ancora": "EVENTO_EXTERNO",
        "dias_prazo_uteis": 5,
        "ref_evento_externo": "REUNIAO_ALINHAMENTO",
        "ref_acao_ordem": None,
    },
    {
        "ordem": 5,
        "nome": "PRIMEIRA FORMAÇÃO / PRESENCIAL OU HÍBRIDA",
        "descricao_prazo": "Até 20 dias úteis após a reunião de alinhamento",
        "tipo_ancora": "ACAO_ANTERIOR",
        "dias_prazo_uteis": 20,
        "ref_evento_externo": "",
        "ref_acao_ordem": 4,
    },
    {
        "ordem": 6,
        "nome": "FEEDBACK DA EQUIPE TECNICA",
        "descricao_prazo": "Até 5 dias úteis após a 1ª formação",
        "tipo_ancora": "ACAO_ANTERIOR",
        "dias_prazo_uteis": 5,
        "ref_evento_externo": "",
        "ref_acao_ordem": 5,
    },
    {
        "ordem": 7,
        "nome": "SEGUNDA FORMAÇÃO / REMOTA",
        "descricao_prazo": "Até 30 dias úteis após a 1ª Formação",
        "tipo_ancora": "ACAO_ANTERIOR",
        "dias_prazo_uteis": 30,
        "ref_evento_externo": "",
        "ref_acao_ordem": 5,
    },
    {
        "ordem": 8,
        "nome": "FEEDBACK DA EQUIPE TECNICA",
        "descricao_prazo": "Até 5 dias úteis após a 1ª formação",
        "tipo_ancora": "ACAO_ANTERIOR",
        "dias_prazo_uteis": 5,
        "ref_evento_externo": "",
        "ref_acao_ordem": 5,
    },
    {
        "ordem": 9,
        "nome": "APLICAÇÃO PRIMEIRA AVALIAÇÃO",
        "descricao_prazo": "Até 60 dias úteis após o inicío do trabalho na sala de aula com o material",
        "tipo_ancora": "EVENTO_EXTERNO",
        "dias_prazo_uteis": 60,
        "ref_evento_externo": "INICIO_TRABALHO_SALA",
        "ref_acao_ordem": None,
    },
    {
        "ordem": 10,
        "nome": "INSERÇÃO DOS DADOS NA PLATAFORMA PELO MUNICÍPIO PRIMEIRA AVALIAÇÃO",
        "descricao_prazo": "Até 20 dias úteis após a Consolidação dos Dados coletados",
        "tipo_ancora": "EVENTO_EXTERNO",
        "dias_prazo_uteis": 20,
        "ref_evento_externo": "CONSOLIDACAO_DADOS_AVALIACAO_1",
        "ref_acao_ordem": None,
    },
    {
        "ordem": 11,
        "nome": "RELATÓRIO PARA O MUNICÍPIO PRIMEIRA AVALIAÇÃO",
        "descricao_prazo": "Até 10 dias úteis após a Consolidação dos Dados coletados",
        "tipo_ancora": "EVENTO_EXTERNO",
        "dias_prazo_uteis": 10,
        "ref_evento_externo": "CONSOLIDACAO_DADOS_AVALIACAO_1",
        "ref_acao_ordem": None,
    },
    {
        "ordem": 12,
        "nome": "PRIMEIRO ACOMPANHAMENTO",
        "descricao_prazo": "Até 90 dias úteis após o início do trabalho na sala de aula com o material",
        "tipo_ancora": "EVENTO_EXTERNO",
        "dias_prazo_uteis": 90,
        "ref_evento_externo": "INICIO_TRABALHO_SALA",
        "ref_acao_ordem": None,
    },
    {
        "ordem": 13,
        "nome": "COMPILAÇÃO DOS DADOS PELO FORMADOR(A) PRIMEIRO ACOMPANHAMENTO",
        "descricao_prazo": "Até 15 dias úteis após a realização do acompanhamento de sala",
        "tipo_ancora": "ACAO_ANTERIOR",
        "dias_prazo_uteis": 15,
        "ref_evento_externo": "",
        "ref_acao_ordem": 12,
    },
    {
        "ordem": 14,
        "nome": "RELATÓRIO DOS DADOS PARA O MUNICÍPIO DO SEGUNDO ACOMPANHAMENTO",
        "descricao_prazo": "Até 15 dias úteis após a realização do acompanhamento de sala",
        "tipo_ancora": "ACAO_ANTERIOR",
        "dias_prazo_uteis": 15,
        "ref_evento_externo": "",
        "ref_acao_ordem": 12,
    },
    {
        "ordem": 15,
        "nome": "TERCEIRA FORMAÇÃO/ PRESENCIAL OU HÍBRIDA",
        "descricao_prazo": "Até 30 dias úteis após a 2ª Formação",
        "tipo_ancora": "ACAO_ANTERIOR",
        "dias_prazo_uteis": 30,
        "ref_evento_externo": "",
        "ref_acao_ordem": 7,
    },
    {
        "ordem": 16,
        "nome": "FEEDBACK DA EQUIPE TECNICA",
        "descricao_prazo": "Até 5 dias úteis após a 3ª formação",
        "tipo_ancora": "ACAO_ANTERIOR",
        "dias_prazo_uteis": 5,
        "ref_evento_externo": "",
        "ref_acao_ordem": 15,
    },
    {
        "ordem": 17,
        "nome": "QUARTA FORMAÇÃO/ REMOTA",
        "descricao_prazo": "Até 20 dias úteis após início do semestre",
        "tipo_ancora": "MARCO_CALENDARIO",
        "dias_prazo_uteis": 20,
        "ref_evento_externo": "INICIO_SEMESTRE",
        "ref_acao_ordem": None,
    },
    {
        "ordem": 18,
        "nome": "FEEDBACK DA EQUIPE TECNICA",
        "descricao_prazo": "Até 5 dias úteis após a 4ª formação",
        "tipo_ancora": "ACAO_ANTERIOR",
        "dias_prazo_uteis": 5,
        "ref_evento_externo": "",
        "ref_acao_ordem": 17,
    },
    {
        "ordem": 19,
        "nome": "SEGUNDO ACOMPANHAMENTO",
        "descricao_prazo": "Até 10 dias úteis após a 4ª Formação",
        "tipo_ancora": "ACAO_ANTERIOR",
        "dias_prazo_uteis": 10,
        "ref_evento_externo": "",
        "ref_acao_ordem": 17,
    },
    {
        "ordem": 20,
        "nome": "COMPILAÇÃO DOS DADOS PELO FORMADOR(A) SEGUNDO ACOMPANHAMENTO",
        "descricao_prazo": "Até 15 dias úteis após a realização do acompanhamento de sala",
        "tipo_ancora": "ACAO_ANTERIOR",
        "dias_prazo_uteis": 15,
        "ref_evento_externo": "",
        "ref_acao_ordem": 19,
    },
    {
        "ordem": 21,
        "nome": "RELATÓRIO DOS DADOS PARA O MUNICÍPIO DO SEGUNDO ACOMPANHAMENTO",
        "descricao_prazo": "Até 15 dias úteis após a realização do acompanhamento de sala",
        "tipo_ancora": "ACAO_ANTERIOR",
        "dias_prazo_uteis": 15,
        "ref_evento_externo": "",
        "ref_acao_ordem": 19,
    },
    {
        "ordem": 22,
        "nome": "QUINTA FORMAÇÃO/ PRESENCIAL OU HÍBRIDA",
        "descricao_prazo": "Até 30 dias úteis após a 4ª Formação",
        "tipo_ancora": "ACAO_ANTERIOR",
        "dias_prazo_uteis": 30,
        "ref_evento_externo": "",
        "ref_acao_ordem": 17,
    },
    {
        "ordem": 23,
        "nome": "FEEDBACK DA EQUIPE TECNICA",
        "descricao_prazo": "Até 5 dias úteis após a 5ª formação",
        "tipo_ancora": "ACAO_ANTERIOR",
        "dias_prazo_uteis": 5,
        "ref_evento_externo": "",
        "ref_acao_ordem": 22,
    },
    {
        "ordem": 24,
        "nome": "APLICAÇÃO DA SEGUNDA AVALIAÇÃO",
        "descricao_prazo": "Até 7 dias úteis após a 5ª formação",
        "tipo_ancora": "ACAO_ANTERIOR",
        "dias_prazo_uteis": 7,
        "ref_evento_externo": "",
        "ref_acao_ordem": 22,
    },
    {
        "ordem": 25,
        "nome": "INSERÇÃO DOS DADOS NA PLATAFORMA PELO MUNICÍPIO SEGUNDA AVALIAÇÃO",
        "descricao_prazo": "Até 20 dias úteis após a Consolidação dos Dados coletados",
        "tipo_ancora": "EVENTO_EXTERNO",
        "dias_prazo_uteis": 20,
        "ref_evento_externo": "CONSOLIDACAO_DADOS_AVALIACAO_2",
        "ref_acao_ordem": None,
    },
    {
        "ordem": 26,
        "nome": "RELATÓRIO PARA O MUNICÍPIO SEGUNDA AVALIAÇÃO",
        "descricao_prazo": "Até 10 dias úteis após a Consolidação dos Dados coletados",
        "tipo_ancora": "EVENTO_EXTERNO",
        "dias_prazo_uteis": 10,
        "ref_evento_externo": "CONSOLIDACAO_DADOS_AVALIACAO_2",
        "ref_acao_ordem": None,
    },
    {
        "ordem": 27,
        "nome": "SEXTA FORMAÇÃO/ REMOTA",
        "descricao_prazo": "Até 15 dias úteis após a 5ª formação",
        "tipo_ancora": "ACAO_ANTERIOR",
        "dias_prazo_uteis": 15,
        "ref_evento_externo": "",
        "ref_acao_ordem": 22,
    },
    {
        "ordem": 28,
        "nome": "FEEDBACK DA EQUIPE TECNICA",
        "descricao_prazo": "Até 5 dias úteis após a 6ª formação",
        "tipo_ancora": "ACAO_ANTERIOR",
        "dias_prazo_uteis": 5,
        "ref_evento_externo": "",
        "ref_acao_ordem": 27,
    },
    {
        "ordem": 29,
        "nome": "SÉTIMA FORMAÇÃO/ REMOTA",
        "descricao_prazo": "Até 25 dias úteis após a 6ª formação",
        "tipo_ancora": "ACAO_ANTERIOR",
        "dias_prazo_uteis": 25,
        "ref_evento_externo": "",
        "ref_acao_ordem": 27,
    },
    {
        "ordem": 30,
        "nome": "FEEDBACK DA EQUIPE TECNICA",
        "descricao_prazo": "Até 5 dias úteis após a 6ª formação",
        "tipo_ancora": "ACAO_ANTERIOR",
        "dias_prazo_uteis": 5,
        "ref_evento_externo": "",
        "ref_acao_ordem": 27,
    },
    {
        "ordem": 31,
        "nome": "ATIVIDADE DE ESTUDO",
        "descricao_prazo": "Até 15 dias úteis após a 6ª formação",
        "tipo_ancora": "ACAO_ANTERIOR",
        "dias_prazo_uteis": 15,
        "ref_evento_externo": "",
        "ref_acao_ordem": 27,
    },
    {
        "ordem": 32,
        "nome": "FEEDBACK DA EQUIPE TECNICA",
        "descricao_prazo": "Até 5 dias úteis após a atividade de estudo",
        "tipo_ancora": "ACAO_ANTERIOR",
        "dias_prazo_uteis": 5,
        "ref_evento_externo": "",
        "ref_acao_ordem": 31,
    },
]


def _executores_por_ordem(ordem: int) -> list[str]:
    if ordem == 1:
        return ["Logística Galpão"]
    if ordem == 2:
        return ["Comercial", "Relacionamento", "DAT"]
    return ["Coordenador", "Gerente"]


def _validar_seed() -> None:
    ordens = sorted(item["ordem"] for item in _SEED_ACTIONS)
    if ordens != list(range(1, 33)):
        raise RuntimeError("Seed invalido: ordens devem cobrir 1..32 sem gaps.")


def seed_acoes_notificacao(apps, schema_editor):
    _validar_seed()
    Group = apps.get_model("auth", "Group")
    AcaoTemplate = apps.get_model("core", "AcaoTemplate")
    AcaoTemplateExecutor = apps.get_model("core", "AcaoTemplateExecutor")

    with transaction.atomic():
        groups_by_name = {}
        for group_name in _GROUPS:
            group, _ = Group.objects.get_or_create(name=group_name)
            groups_by_name[group_name] = group

        templates_by_ordem = {}
        for item in sorted(_SEED_ACTIONS, key=lambda seed: seed["ordem"]):
            ref_template = None
            ref_acao_ordem = item["ref_acao_ordem"]
            if ref_acao_ordem is not None:
                ref_template = templates_by_ordem[ref_acao_ordem]

            template, _ = AcaoTemplate.objects.update_or_create(
                ordem=item["ordem"],
                defaults={
                    "nome": item["nome"],
                    "descricao_prazo": item["descricao_prazo"],
                    "tipo_ancora": item["tipo_ancora"],
                    "dias_prazo_uteis": item["dias_prazo_uteis"],
                    "ref_evento_externo": item["ref_evento_externo"],
                    "ref_acao_template": ref_template,
                    "ativo": True,
                },
            )
            templates_by_ordem[item["ordem"]] = template

        for item in _SEED_ACTIONS:
            template = templates_by_ordem[item["ordem"]]
            desired_ids = {groups_by_name[name].id for name in _executores_por_ordem(item["ordem"])}
            existing_ids = set(
                AcaoTemplateExecutor.objects.filter(acao_template=template).values_list("group_id", flat=True)
            )

            for group_id in desired_ids - existing_ids:
                AcaoTemplateExecutor.objects.create(
                    acao_template=template,
                    group_id=group_id,
                    ativo=True,
                )

            stale_ids = existing_ids - desired_ids
            if stale_ids:
                AcaoTemplateExecutor.objects.filter(
                    acao_template=template,
                    group_id__in=stale_ids,
                ).delete()


def reverse_seed_acoes_notificacao(apps, schema_editor):
    AcaoTemplate = apps.get_model("core", "AcaoTemplate")
    AcaoTemplateExecutor = apps.get_model("core", "AcaoTemplateExecutor")

    ordens = [item["ordem"] for item in _SEED_ACTIONS]
    templates = AcaoTemplate.objects.filter(ordem__in=ordens)
    AcaoTemplateExecutor.objects.filter(acao_template__in=templates).delete()
    templates.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0059_acaotemplate_acaotemplateexecutor_cicloacoes_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_acoes_notificacao, reverse_seed_acoes_notificacao),
    ]
