# Generated by Django 5.1.15 on 2026-03-13 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0060_seed_acoes_notificacao_templates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acaotemplateexecutor",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="acoes_template", to="auth.group"
            ),
        ),
    ]
