# Generated by Django 5.1.15 on 2026-03-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0063_fix_executor_group_protect"),
    ]

    operations = [
        migrations.CreateModel(
            name="PermissaoFuncional",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "codename",
                    models.SlugField(
                        help_text="Identificador tecnico estavel usado nas regras de autorizacao.",
                        max_length=80,
                        unique=True,
                    ),
                ),
                ("label", models.CharField(help_text="Nome amigavel exibido na UI.", max_length=120)),
                (
                    "description",
                    models.TextField(blank=True, default="", help_text="Descricao opcional da permissao funcional."),
                ),
                (
                    "category",
                    models.CharField(
                        db_index=True,
                        help_text="Categoria para agrupamento (ex.: admin_dat, dashboard, solicitacao).",
                        max_length=50,
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Quando true, permissao faz parte do conjunto base do sistema.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Grupos que recebem esta permissao funcional.",
                        related_name="permissoes_funcionais",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permissao Funcional",
                "verbose_name_plural": "Permissoes Funcionais",
                "db_table": "core_permissao_funcional",
                "ordering": ["category", "label"],
            },
        ),
    ]
