# Generated by Django 5.1.15 on 2026-03-23 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0065_seed_permissoes_funcionais"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipegerencia",
            name="gerencia",
            field=models.ForeignKey(
                help_text="Gerencia/setor ao qual o usuario pertence",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="equipes",
                to="core.gerencia",
            ),
        ),
        migrations.AlterField(
            model_name="equipegerencia",
            name="usuario",
            field=models.ForeignKey(
                help_text="Usuario membro da equipe",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="equipes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="availabilityblock",
            index=models.Index(fields=["usuario", "status", "inicio"], name="idx_avblock_usr_st_ini"),
        ),
        migrations.AddIndex(
            model_name="participation",
            index=models.Index(fields=["solicitacao", "usuario"], name="idx_part_solic_usuario"),
        ),
        migrations.AddIndex(
            model_name="solicitacao",
            index=models.Index(fields=["usuario", "status"], name="idx_solic_usuario_status"),
        ),
        migrations.AddIndex(
            model_name="solicitacao",
            index=models.Index(fields=["municipio", "inicio", "fim"], name="idx_solic_mun_intervalo"),
        ),
    ]
