# Generated by Django 5.1.15 on 2026-03-24 13:32

import django.db.models.deletion
from django.db import migrations, models

SETOR_GROUPS = [
    "Superintendência",
    "Vidas",
    "Fluir",
    "ACerta",
    "Brincando",
    "Sou da Paz",
    "DAT",
    "Controle",
    "Gerência",
    "Diretoria",
    "Comercial",
    "Relacionamento",
    "Logística Viagens",
    "Logística Galpão",
]

FUNCAO_GROUPS = [
    "Formador",
    "Coordenador",
    "Apoio de Coordenação",
    "Gerente",
]


def seed_group_classificacao(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    GroupClassificacao = apps.get_model("core", "GroupClassificacao")

    for group_name in SETOR_GROUPS:
        group, _ = Group.objects.get_or_create(name=group_name)
        GroupClassificacao.objects.update_or_create(
            group=group,
            defaults={"tipo": "setor"},
        )

    for group_name in FUNCAO_GROUPS:
        group, _ = Group.objects.get_or_create(name=group_name)
        GroupClassificacao.objects.update_or_create(
            group=group,
            defaults={"tipo": "funcao"},
        )


def unseed_group_classificacao(apps, schema_editor):
    GroupClassificacao = apps.get_model("core", "GroupClassificacao")
    GroupClassificacao.objects.filter(group__name__in=(SETOR_GROUPS + FUNCAO_GROUPS)).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0066_data_integrity_indexes_on_delete"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupClassificacao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "tipo",
                    models.CharField(choices=[("setor", "Setor"), ("funcao", "Função")], db_index=True, max_length=16),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="rbac_classificacao", to="auth.group"
                    ),
                ),
            ],
            options={
                "verbose_name": "Classificação de Grupo",
                "verbose_name_plural": "Classificações de Grupo",
                "db_table": "core_group_classificacao",
                "ordering": ["group__name"],
            },
        ),
        migrations.RunPython(seed_group_classificacao, unseed_group_classificacao),
    ]
