# Generated by Django 5.1.15 on 2026-03-24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0067_groupclassificacao"),
        ("core", "0068_clear_default_funcperm_group_links"),
    ]

    operations = []
