# Generated by Django 5.2.13 on 2026-04-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0070_drop_dat_ingest_tables"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="equipegerencia",
            index=models.Index(fields=["gerencia", "papel", "ativo"], name="idx_equipe_ger_papel_ativo"),
        ),
    ]
