# Generated by Django 5.2.13 on 2026-04-22 01:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0071_equipegerencia_idx_equipe_ger_papel_ativo"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "import_type",
                    models.CharField(
                        choices=[("bloqueios", "Bloqueios")],
                        db_index=True,
                        help_text="Tipo de import (bloqueios, usuarios, etc.)",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Na fila"),
                            ("RUNNING", "Executando"),
                            ("SUCCESS", "Concluido"),
                            ("FAILED", "Falhou"),
                        ],
                        db_index=True,
                        default="QUEUED",
                        help_text="Estado atual do job",
                        max_length=16,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Arquivo submetido (mantido para auditoria)",
                        max_length=500,
                        upload_to="imports/%Y/%m/%d/",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Nome original do arquivo submetido (preservado separado do FileField)",
                        max_length=500,
                    ),
                ),
                (
                    "dry_run",
                    models.BooleanField(
                        default=True, help_text="Se True, service roda e retorna stats mas da rollback"
                    ),
                ),
                (
                    "stats",
                    models.JSONField(
                        blank=True, default=dict, help_text="Contadores populados pelo service ao concluir"
                    ),
                ),
                (
                    "pendencias",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Linhas rejeitadas/pendentes por categoria (usuarios, dates, outros)",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, default="", help_text="Mensagem curta (ate 500 chars) quando status=FAILED"
                    ),
                ),
                (
                    "error_traceback",
                    models.TextField(
                        blank=True, default="", help_text="Traceback completo do erro (nao exposto na API)"
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="ID da task Celery para correlacao com logs/flower",
                        max_length=255,
                    ),
                ),
                (
                    "duration_ms",
                    models.PositiveIntegerField(
                        blank=True, help_text="Tempo total de execucao (finished_at - started_at) em ms", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Usuario que disparou o import (auditoria)",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Job de Importacao",
                "verbose_name_plural": "Jobs de Importacao",
                "db_table": "core_import_job",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "status"], name="core_import_user_id_343d05_idx"),
                    models.Index(fields=["status", "created_at"], name="core_import_status_2aa1cf_idx"),
                    models.Index(fields=["import_type", "status"], name="core_import_import__6ab585_idx"),
                ],
            },
        ),
    ]
