# Generated by Django 5.2.15 on 2026-07-01 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0082_availability_block_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                db_index=True,
                help_text="Acao executada (use AuditLog.Action enum; legacy strings preservadas)",
                max_length=50,
            ),
        ),
    ]
