# Generated by Django 5.2.16 on 2026-08-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0083_alter_auditlog_action"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="compra",
            name="core_compra_externa_8494aa_idx",
        ),
        migrations.AlterField(
            model_name="compra",
            name="external_hash",
            field=models.CharField(help_text="Hash SHA256 para idempotencia de import", max_length=64),
        ),
    ]
