# Generated by Django 5.2.16 on 2026-08-18 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0084_remove_redundant_external_hash_indexes"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AcaoControle",
        ),
    ]
