# Generated by Django 5.2.16 on 2026-08-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0085_drop_acao_controle"),
    ]

    operations = [
        migrations.AddField(
            model_name="datregistro",
            name="nr_codigos_planilha",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Valor importado da planilha, para reconciliar com nr_codigos calculado.",
                null=True,
                verbose_name="Nº de Códigos (planilha)",
            ),
        ),
    ]
