# Generated by Django 5.2.17 on 2026-08-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0086_add_nr_codigos_planilha"),
    ]

    operations = [
        migrations.AddField(
            model_name="datcompra",
            name="conta_para_codigos",
            field=models.BooleanField(
                default=True,
                help_text="False exclui a compra do cálculo de nr_codigos (ex.: kits AVALIAR de GESTÃO ESCOLAR)",
                verbose_name="Conta para códigos",
            ),
        ),
        migrations.AddField(
            model_name="datcompra",
            name="tipo",
            field=models.CharField(
                blank=True,
                choices=[("Aluno", "Aluno"), ("Professor", "Professor")],
                help_text="Kit de aluno ou de professor — só kit de professor recebe o multiplicador",
                max_length=10,
                null=True,
                verbose_name="Tipo (Aluno/Professor)",
            ),
        ),
        migrations.AlterField(
            model_name="datregistro",
            name="aluno_qtde",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Total de alunos na turma (vazio em registros professor-only)",
                null=True,
                verbose_name="Quantidade de Alunos",
            ),
        ),
    ]
