# Generated by Django 5.2.17 on 2026-08-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0089_dat_registro_ano"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datcompra",
            name="ano_uso",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Ano de uso da coleção; NULL = não classificado (pendente de ano).",
                null=True,
                verbose_name="Ano de Uso",
            ),
        ),
    ]
