# Generated by Django 5.2.17 on 2026-08-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0090_dat_compra_ano_uso_nullable"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="datregistro",
            name="unique_dat_registro_municipio_projeto",
        ),
        migrations.AddConstraint(
            model_name="datregistro",
            constraint=models.UniqueConstraint(
                fields=("municipio", "projeto_geral", "projeto", "ano"),
                name="unique_dat_registro_municipio_projeto_ano",
                nulls_distinct=False,
            ),
        ),
    ]
