# Generated by Django 5.2.17 on 2026-08-24 18:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0095_plano_formacoes_ano_nk"),
    ]

    operations = [
        migrations.AddField(
            model_name="datcoordenador",
            name="cpf",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Somente dígitos (11). Chave de identidade para resolução de import por CPF.",
                max_length=11,
                null=True,
                validators=[
                    django.core.validators.RegexValidator("^\\d{11}$", "CPF deve conter exatamente 11 dígitos.")
                ],
                verbose_name="CPF",
            ),
        ),
    ]
