# Generated by Django 5.2.17 on 2026-08-25 14:11
# Editado (#1849): RunPython que ZERA coordenador_id vem ANTES do AlterField.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _zerar_coordenador(apps, schema_editor):
    """coordenador_id guarda ids de DATCoordenador; a FK vai apontar Usuario. Zerar ANTES do AlterField —
    senão o novo constraint FK (REFERENCES core_usuario) valida contra ids de DATCoordenador e a migração
    aborta. Prod não tem import real (nenhum vínculo a perder); os vínculos de golden/UI são re-resolvidos
    contra Usuario por CPF num import definitivo (clone fresco). #1849."""
    PlanoFormacoes = apps.get_model("core", "PlanoFormacoes")
    PlanoFormacoes.objects.update(coordenador=None)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0096_dat_coordenador_cpf"),
    ]

    operations = [
        migrations.RunPython(_zerar_coordenador, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="planoformacoes",
            name="coordenador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="planos_coordenados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Coordenador Responsavel",
            ),
        ),
    ]
