# Generated by Django 5.2.17 on 2026-08-28 11:14

from django.db import migrations, models


def _backfill_inactive_as_local(apps, schema_editor):
    """Backfill conservador (#1894): todo usuário atualmente INATIVO passa a
    `desativado_localmente=True`.

    No momento da migração não há como distinguir POR QUE alguém está inativo (decisão
    do admin vs. planilha). Assumir que os inativos de hoje foram desligados localmente
    preserva a proteção do #1891/#1902 (o import nunca reativa quem já estava inativo).
    Daqui pra frente a distinção é feita no ponto de escrita: admin desativa -> flag=True;
    planilha cria/atualiza inativo -> flag permanece False (a planilha pode reativá-los).
    """
    Usuario = apps.get_model("core", "Usuario")
    Usuario.objects.filter(is_active=False).update(desativado_localmente=True)


def _noop_reverse(apps, schema_editor):
    # Reverter o AddField remove a coluna; não há dado a desfazer.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0097_plano_coordenador_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="desativado_localmente",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Marca desativação decidida NO SISTEMA (admin/anonimização), não pela planilha. O import nunca reativa (False->True) um usuário com esta flag — reativar é ação humana (#1894). A planilha pode reativar quem ela mesma desativou (flag False).",
            ),
        ),
        migrations.RunPython(_backfill_inactive_as_local, _noop_reverse),
    ]
