# Generated by Django 5.2.17 on 2026-08-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0098_usuario_desativado_localmente"),
    ]

    operations = [
        migrations.AddField(
            model_name="gerencia",
            name="setor_canonico",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Superintendência", "Superintendência"),
                    ("Vidas", "Vidas"),
                    ("Fluir", "Fluir"),
                    ("ACerta", "ACerta"),
                    ("Brincando", "Brincando"),
                    ("Sou da Paz", "Sou da Paz"),
                    ("DAT", "DAT"),
                    ("Controle", "Controle"),
                    ("Diretoria", "Diretoria"),
                    ("Comercial", "Comercial"),
                    ("Relacionamento", "Relacionamento"),
                    ("Logística Viagens", "Logística Viagens"),
                    ("Logística Galpão", "Logística Galpão"),
                ],
                db_index=True,
                default="",
                help_text="Setor canônico (vocabulário SETOR_GROUPS), do de-para do sheets.banco. Eixo do gate de participação/grade por setor (#1893/#1898). Comparar por igualdade de nome_setor barra ~46%; este campo canoniza os dois lados.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="projeto",
            name="setor",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Superintendência", "Superintendência"),
                    ("Vidas", "Vidas"),
                    ("Fluir", "Fluir"),
                    ("ACerta", "ACerta"),
                    ("Brincando", "Brincando"),
                    ("Sou da Paz", "Sou da Paz"),
                    ("DAT", "DAT"),
                    ("Controle", "Controle"),
                    ("Diretoria", "Diretoria"),
                    ("Comercial", "Comercial"),
                    ("Relacionamento", "Relacionamento"),
                    ("Logística Viagens", "Logística Viagens"),
                    ("Logística Galpão", "Logística Galpão"),
                ],
                db_index=True,
                default="",
                help_text="Setor canônico do projeto (vocabulário SETOR_GROUPS), do de-para do sheets.banco. Eixo de autorização por setor (#1893/#1898). Autoritativo; enquanto vazio, o serializer deriva de gerencia.nome_setor (fallback, sem regressão).",
                max_length=100,
            ),
        ),
    ]
