# Generated by Django 5.2.17 on 2026-08-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0099_gerencia_setor_canonico_projeto_setor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gerencia",
            name="setor_canonico",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Setor canônico da PESSOA, no vocabulário de setor-de-PRODUTO (do de-para do sheets.banco, ex.: Vidas, Fluir, Superativar, GESTÃO ESCOLAR) — NÃO os 13 grupos RBAC (SETOR_GROUPS). Compara por igualdade com Projeto.setor no gate de participação/grade (#1893/#1898); igualdade de nome_setor barrava ~46%, este campo canoniza os dois lados.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="setor",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Setor do projeto, no vocabulário de setor-de-PRODUTO (do de-para do sheets.banco, ex.: Vidas, Fluir, Superativar, GESTÃO ESCOLAR) — NÃO os 13 grupos RBAC. Eixo de autorização por setor (#1893/#1898); compara por igualdade com Gerencia.setor_canonico. Autoritativo; enquanto vazio, o serializer deriva de gerencia.nome_setor (fallback, sem regressão).",
                max_length=100,
            ),
        ),
    ]
