# Generated by Django 5.2.17 on 2026-09-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0101_rehash_eventos_external_hash_with_segmento"),
    ]

    operations = [
        migrations.AddField(
            model_name="gerencia",
            name="setor_canonico_confianca",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Confiança do de-para v15 que atribuiu `setor_canonico` (RELAY 50, item 8) — ÚNICO sinal de qualidade, populado por IMPORT, SEM entrada-direta. Exibido na conferência para o humano priorizar as atribuições de baixa confiança; o usuário não digita este campo (read-only na API).",
                max_length=30,
            ),
        ),
    ]
