# Generated by Django 5.2.17 on 2026-09-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0102_gerencia_setor_canonico_confianca"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="participation",
            name="core_participation_user_or_email",
        ),
        migrations.AddField(
            model_name="participation",
            name="guest_nome",
            field=models.CharField(blank=True, default="", max_length=200, verbose_name="Nome do convidado"),
        ),
        migrations.AddConstraint(
            model_name="participation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("usuario__isnull", False),
                    ("guest_email__isnull", False),
                    models.Q(("guest_nome", ""), _negated=True),
                    _connector="OR",
                ),
                name="core_participation_user_or_email",
            ),
        ),
        migrations.AddConstraint(
            model_name="participation",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("usuario__isnull", True),
                    ("guest_email__isnull", True),
                    models.Q(("guest_nome", ""), _negated=True),
                ),
                fields=("solicitacao", "guest_nome", "role"),
                name="core_participation_unique_nome",
            ),
        ),
    ]
