# Generated by Django 5.2.17 on 2026-09-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0103_participation_guest_nome"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="equipegerencia",
            name="apoio_requires_supervisor",
        ),
        migrations.AddField(
            model_name="solicitacao",
            name="solicitante_procedencia",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Import (v16.4): como o solicitante/coordenador do evento foi resolvido — coluna_n, coluna_n_escada (fato), constante_da_aba, cargo_unico (inferencia). Vazio = entrada direta.",
                max_length=30,
            ),
        ),
    ]
