# Generated by Django 5.2.17 on 2026-09-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0105_plano_coordenadores_m2m"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacao",
            name="segmento_norm",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Segmento canônico (de-para do sheets.banco: v15 mapeia 275 grafias → 57 valores). Populado por IMPORT a partir da coluna `segmento_norm` do contrato; o `segmento` cru fica intacto. Autoritativo do import (sem entrada-direta), espelhando `Gerencia.setor_canonico`.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="solicitacao",
            name="segmento_norm_confianca",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Confiança do de-para que atribuiu `segmento_norm` — sinal de qualidade populado por IMPORT, SEM entrada-direta (read-only na API), espelhando `Gerencia.setor_canonico_confianca`.",
                max_length=30,
            ),
        ),
    ]
