# Generated by Django 5.2.17 on 2026-09-03 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0106_solicitacao_segmento_norm"),
    ]

    operations = [
        migrations.AddField(
            model_name="projeto",
            name="sem_operacao",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Marcador v15 (do de-para do sheets.banco, #1897) de projeto SEM operação — variante de catálogo que não gera eventos/operação. Autoritativo do import, SEM entrada-direta.",
            ),
        ),
    ]
