# Generated by Django 5.2.17 on 2026-09-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0107_projeto_sem_operacao"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="participation",
            constraint=models.CheckConstraint(
                condition=models.Q(("role__in", ["COORDENADOR", "FORMADOR", "COORD_ACOMPANHA", "CONVIDADO"])),
                name="core_participation_role_valid",
            ),
        ),
    ]
