# Generated by Django 5.2.17 on 2026-09-14 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0108_participation_role_check"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DATFormacao",
        ),
    ]
