# Generated by Django 5.2.17 on 2026-09-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0109_delete_datformacao"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="datcompra",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantidade_utilizada__lte", models.F("quantidade"))),
                name="dat_compra_utilizada_lte_quantidade",
            ),
        ),
        migrations.AddConstraint(
            model_name="datcompra",
            constraint=models.CheckConstraint(
                condition=models.Q(("valor_unitario__gte", 0)), name="dat_compra_valor_unitario_gte_0"
            ),
        ),
    ]
