# Generated by Django 5.2.17 on 2026-09-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0111_seed_publish_setor_capability"),
    ]

    operations = [
        migrations.AddField(
            model_name="gerencia",
            name="nome_exibicao",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Nome do setor que a tela mostra (ex: Superativar). Vazio = usa `nome_setor`. Alterado pelo admin (Gerências); nenhum import grava este campo.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="gerencia",
            name="nome",
            field=models.CharField(
                db_index=True,
                help_text="Código interno da gerência (ex: GERENCIA 2, SUPERINTENDENCIA). Chave técnica do seed e da aprovação (PR B); não é alterado pela tela nem exibido como nome do setor.",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="gerencia",
            name="nome_setor",
            field=models.CharField(
                help_text="Rótulo do setor nas planilhas (ex: Vidas, ACerta, Fluir). Chave de casamento do import (export-contract, equipe de gerência); alterado pelo import ou pelo admin.",
                max_length=100,
            ),
        ),
    ]
