# Generated by Django 5.2.17 on 2026-10-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0112_gerencia_nome_exibicao"),
    ]

    operations = [
        migrations.AddField(
            model_name="projeto",
            name="eh_serie",
            field=models.BooleanField(
                default=False,
                help_text="Série/variante de um projeto (ex.: A COR DA GENTE 3): não entra na Nova Solicitação; no Plano Anual só aparece se já tiver plano; continua em Compras e DAT. Editável na tela Projetos. O import marca só ao criar o projeto e nunca altera a marca de um projeto existente.",
            ),
        ),
    ]
