# Generated by Django 5.2.17 on 2026-10-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0114_projeto_eh_serie_backfill"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="deve_trocar_senha",
            field=models.BooleanField(
                default=False,
                help_text="Ligado quando a senha em uso foi definida por outra pessoa (administrador ou carga). Enquanto ligado, a API só aceita ler o próprio /me, CSRF, trocar a senha e sair (`TrocaDeSenhaObrigatoriaMiddleware`). Desliga quando a própria pessoa troca a senha.",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="senha_recebida_hash",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                help_text="Hash da última senha recebida de outra pessoa, guardado quando a própria pessoa a troca. Serve só para recusar a volta a ela (a senha padrão é a mesma para todos). Nunca o texto da senha.",
                max_length=128,
            ),
        ),
    ]
