# Generated by Django 5.2.17 on 2026-10-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0114_projeto_eh_serie_backfill"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="deve_trocar_senha",
            field=models.BooleanField(
                default=False,
                help_text="Ligado quando a senha em uso foi definida por outra pessoa (administrador ou carga). Enquanto ligado, a API só aceita ler o próprio /me, CSRF, trocar a senha e sair (`TrocaDeSenhaObrigatoriaMiddleware`). Desliga quando a própria pessoa troca a senha.",
            ),
        ),
    ]
