# Generated by Django 5.2.17 on 2026-10-05 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0115_usuario_deve_trocar_senha"),
    ]

    operations = [
        migrations.AddField(
            model_name="gerencia",
            name="pergunta_avaliar_formador",
            field=models.BooleanField(
                default=True,
                help_text="Nova Solicitação de projeto desta gerência pergunta 'Você pretende avaliar o formador nesse evento?'. False = a gerência não usa a pergunta (decisão do dono, 05/10/2026).",
            ),
        ),
        migrations.AddField(
            model_name="solicitacao",
            name="formador_avaliado",
            field=models.ForeignKey(
                blank=True,
                help_text="Formador que quem criou pretende avaliar (só com pretende_avaliar_formador=True).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="eventos_como_avaliado",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="solicitacao",
            name="pretende_avaliar_formador",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Resposta a 'Você pretende avaliar o formador nesse evento?'. None = não perguntado ou não informado (eventos antigos, gerência que não pergunta, evento sem formador avaliável).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="solicitacao",
            name="coordenador_acompanha",
            field=models.BooleanField(
                default=False,
                help_text="Resposta a 'O coordenador responsável vai acompanhar o evento?'. True: a agenda do coordenador responsável é conferida (RD-01..04) como a dos formadores (decisão do dono, 05/10/2026). Obrigatória na criação pela API; os eventos antigos ficam como estão.",
            ),
        ),
    ]
