# Generated by Django 5.2.17 on 2026-10-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0116_agenda_acompanha_e_avaliar_formador"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipegerencia",
            name="papel",
            field=models.CharField(
                choices=[
                    ("GERENTE", "Gerente"),
                    ("COORDENADOR", "Coordenador"),
                    ("APOIO", "Apoio de Coordenacao"),
                    ("FORMADOR", "Formador"),
                    ("EQUIPE", "Equipe administrativa"),
                ],
                help_text="Papel do usuario nesta gerencia",
                max_length=15,
            ),
        ),
    ]
