# Generated by Django 5.2.17 on 2026-10-06 17:10
#
# Coleção é a família (ProjetoGeral), regra do dono de 05/10/2026: o cadastro `Colecao` sai. Em produção
# a tabela tinha 0 linhas e nenhum produto apontava para ela (medido em 06/10/2026), então nada se perde.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0117_equipegerencia_papel_equipe"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produto",
            name="colecao",
        ),
        migrations.DeleteModel(
            name="Colecao",
        ),
    ]
