# Generated by Django 5.2.17 on 2026-10-06 17:21
#
# Só o rótulo: a família (ProjetoGeral) aparece como "Coleção" nas mensagens (decisão do dono, 06/10/2026).
# Sem SQL; tabela, model e campos continuam com o nome de sempre.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0118_remove_colecao"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projetogeral",
            options={"ordering": ["nome"], "verbose_name": "Coleção", "verbose_name_plural": "Coleções"},
        ),
    ]
